### ISSUE TITLE
Command line switch to open file and follow it

### ISSUE THREAD

**Issue by shvez** [variar/klogg#101]
Hi, there

is there a command line switch so that all files passed through command line will be opened and followed?

if there is such switch is it possible to add it?

best,
ilya

**Comment by variar** [comment]
Added flag `-f` or `--follow` in build  19.9.0.488

**Comment by shvez** [comment]
Thanks a lot.
I will test it soon

**Comment by shvez** [comment]
yes, it looks working.
thank you
