### ISSUE TITLE
Allow multiple instances

### ISSUE THREAD

**Issue by wiz0u** [variar/klogg#105]
Sometimes I'd like to watch multiple log files in parallel (for example, splitting my screen in two to view 2 log files at the same time)
With klogg tab system, I don't think it's possible to view multiple log files in parallel.
So the solution would be either to allow "detaching" some tabs into their own window, or to allow running multiple instance of klogg in parallel.
Maybe a checkbox in the Options dialog could allow that.
There might be an issue with maintaining the list of opened files though.. (or fighting over the .ini settings)
Maybe the second instance could start with an empty list of files and not try to add its files to the main list of opened files

**Comment by variar** [comment]
Multiple instances are already possible with command line switches. However, they will "fight" for same configuration. I think that switching from Tab Widget to Docking Widgets shouldn't be very hard and will solve the problem

**Comment by variar** [comment]
Actually this commit looks promising https://github.com/sergei-dyshel/glogg/commit/419ce2687b5069da9b9bf87f98cd9b30b3431bee

Maybe this can be integrated to klogg

**Comment by variar** [comment]
Initial very experimental implementation in build >= 19.11.0.502. After enabling in options there will be an item in File menu to create new windows

**Comment by variar** [comment]
@wiz0u could you try it and see if this solution is ok for your case?

**Comment by wiz0u** [comment]
It seems to work.
However it would be nice for secondary windows to be suffixed by "#2", "#3", etc in the caption bar, and then to have a context menu item when right-clicking a tab that allows to "Move tab to window #2"... or something like that

**Comment by wiz0u** [comment]
When closing klogg (File>Exit), then restarting klogg, it lost all my windows configuration (position/size) and opened files

**Comment by wiz0u** [comment]
> When closing klogg (File>Exit), then restarting klogg, it lost all my windows configuration (position/size) and opened files

This does happen even if "Allow multiple windows" is unchecked
(but with the multiple windows feature, people will start using File>Exit more often instead of closing a single window)

**Comment by variar** [comment]
Thanks for testing. File->Exit path indeed has been modified, I'll look into it.

Moving tabs between windows is on todo list :)

**Comment by variar** [comment]
19.12.0.525 brings fixes for configuration saving for multi-window case. On exit from menu position and content for all opened windows should be written to configuration file. When windows are closed individually then the last closed window stays in configuration.

Moving tabs between windows requires more work and ui class structure really needs refactoring to make such changes easier.

**Comment by wiz0u** [comment]
Looks good now.
