### ISSUE TITLE
Feature request: Copy pathname of file

### ISSUE THREAD

**Issue by wiz0u** [variar/klogg#108]
Allow the user to copy the full pathname of the file currently viewed to the clipboard

Some ideas where to add this feature: 
- [ ] Right-click on the pathname displayed on top of window => 'Copy file path'
- [x] Right-click on the tab header => 'Copy file path' (could also work for non-current files)
- [x] In the Edit menu => 'Copy file path'

**Comment by variar** [comment]
All options except "In the Edit menu" surprisingly require many small changes because only topmost main window and low level file reading classes store actual file path, no one in between (where we want to add a menu option) have access to this data (hey it's, encapsulation 😄 ).

However, I've been thinking of reworking that part of source code long ago and now there is an excuse to spend some time on it.

**Comment by wiz0u** [comment]
Actually the first 2 options are my preferred.
I didn't particularly expect this command to be available under the Edit menu.

So it's up to you if you find it simpler to implement on the first 2 options.

**Comment by wiz0u** [comment]
The "copy full path" works, thanks!

I see you added also "Open containing folder"

However, it never works in the Edit menu.
And on right-click tab header, it works only if the path is not an UNC path

When it works, it would be nice if it opens the folder and preselect the file
(explorer /select,<file>)

**Comment by variar** [comment]
Moved Edit menu to separate issue #112.

As for "Open containing folder",  I use Qt provided [QDesktopServices::openUrl](https://doc.qt.io/qt-5/qdesktopservices.html#openUrl) to do this cross-platform. UNC paths might be bug in my code (not using file:// url scheme properly), but preselecting a file is definitely system specific.  I'll check if there is some library that provides better cross-platform support for this.

**Comment by variar** [comment]
Fixed Open containing folder in build 19.9.0.487 using code from Qt Creator sources

**Comment by wiz0u** [comment]
Works great now!

**Comment by wiz0u** [comment]
I really miss a "Copy full path" menu item when right-clicking on the path textbox.
That seems like the most obvious place where one would expect this feature.

**Comment by variar** [comment]
> I really miss a "Copy full path" menu item when right-clicking on the path textbox.
> That seems like the most obvious place where one would expect this feature.

Yes, that's on the todo list

**Comment by variar** [comment]
Added a context menu item to top line with path

**Comment by wiz0u** [comment]
Can you rename it as "Copy full path" rather than "Copy all"?
It would be more clear, and more consistent with the same option from the Edit menu and the tab header context menu.

**Comment by wiz0u** [comment]
Also make sure this copies only the path name (currently it copies the textbox content, which may contain "Indexing N%")
