### ISSUE TITLE
Hide "X Line 1" when not parsing

### ISSUE THREAD

**Issue by wiz0u** [variar/klogg#109]
On the top right corner of the window, I see a permanent "X Line 1"

This is possibly useful when parsing of a long file occurs, but when parsing is done and no background parsing operation is happening, I think this part should be hidden

**Comment by variar** [comment]
Than "line 1" part should show the number of currently selected line. Useful if option to show line numbers is turned off. Perhaps, we should move this to status line in the bottom, like notepad++ and many others.

**Comment by wiz0u** [comment]
Oh I didn't notice it was the line number.
I agree you shouldn't waste vertical space.

Maybe rework the area below the file view:
- merge the "N matches founds." with the 'Line number' into a new status line just below the main file view (above the search box).. That status line could also include the size/nb lines/modifed/format info that is currently after the file path
- move the "Auto-refresh" and "Marks/Matches" buttons on the same line as the search box

**Comment by wiz0u** [comment]
The new search page single-line layout seems nice now.
I really feel you should also move the file stats out of the file path textbox, and put them in statusbar-like separators
Something like that:
![image](https://user-images.githubusercontent.com/11647984/66757025-83cb6f80-ee9b-11e9-9bf5-17edb73501d8.png)

**Comment by variar** [comment]
Did some redesign in 19.10.0.495

**Comment by variar** [comment]
The problem with this approach is that in fullscreen mode information about file is pushed to far right. Looks like more space is needed between status labels to make it look less packed.

**Comment by wiz0u** [comment]
> pushed to far right

I don't see it as a problem. It's not information you're always looking at. And when you really need to look at it, it's a better eye-reflex to look to the top right corner than to a random position depending on the length of the filepath as it was before. (didn't check build 495 yet)

**Comment by variar** [comment]
Used for some time. Looks okay.

**Comment by wiz0u** [comment]
I didn't have a chance to look at it. Looks nice to me.

However I would replace "System" with "System locale (<name of locale>)" (and possibly put this also in the Encoding menu)
And also I would switch the "Displayed as" logic for a "Detected as" logic.

Which means:
- Replace "XYZ" with "Detected as XYZ" (to clearly state this is the result of the auto-detection of encoding)
- Replace "Displayed as XYZ" with "XYZ" (nothing more to say because it's the explicit choice of the user)
