### ISSUE TITLE
Open containing folder does not work from Edit menu

### ISSUE THREAD

**Issue by variar** [variar/klogg#112]
It works form tab context meny

**Comment by variar** [comment]
Actually, only copy full path works. Might be some issue in wiring signals from menu actions

**Comment by variar** [comment]
To preselect file this code can be merged https://github.com/qt-creator/qt-creator/blob/master/src/plugins/coreplugin/fileutils.cpp#L67

**Comment by variar** [comment]
Fixed in 19.9.0.487

**Comment by wiz0u** [comment]
Works great now!
