### ISSUE TITLE
Ctrl-PgUp/PgDown to change active tab

### ISSUE THREAD

**Issue by wiz0u** [variar/klogg#113]
I believe Ctrl-PgUp/PgDown is currently identical to Ctrl-Home/End.

It would be better if Ctrl-PgUp/PgDown allowed to navigate to the previous/next tab to switch the active file.

**Comment by variar** [comment]
shift+Left/Right arrow should work for this, but they aren't in build 19.9.0.484 ( I'll fix it and add Ctrl-PgUp/PgDown.

**Comment by wiz0u** [comment]
Thanks. Ctrl-PgUp/PgDown seems more standard to me, as I see it supported by Firefox tabs and a few other apps

**Comment by variar** [comment]
Arrows work on keypad as Ctrl+Alt+Left\Right, no bug here. Alsow Ctrl+Tab|Ctrl+Shit+Tab do work.

PgUp/PgDown should work in builds 19.9.0.489

**Comment by wiz0u** [comment]
Ctrl-PgUp/PgDown is reversed! PgUp should navigate to the tab on the left

Ctrl-Alt-Left/Right doesn't seem to work for me.

**Comment by variar** [comment]
> Ctrl-PgUp/PgDown is reversed

Oops :blush:

> Ctrl-Alt-Left/Right doesn't seem to work for me

For some unclear reasons Nicolas made it work only with arrows on numpad

**Comment by wiz0u** [comment]
> For some unclear reasons Nicolas made it work only with arrows on numpad

ah right, with numlock off... weird
