### ISSUE TITLE
Possibility to assign titles to file tabs?

### ISSUE THREAD

**Issue by dia-susca** [variar/klogg#114]
When working with multiple servers in multiple locations, usually the filename is the same (eg: System.log). So one might have 4 opened tabs named "System.log".

 It would be useful to be able to assign a label to each window tab, other than the filename. Or any other solution that would make the logs distinguishable. 

For example, the tab title could be editable - if anything is entered, that is the new tab title, if  it is left blank, the tab title is reverted to the file name

**Comment by variar** [comment]
I've seen something like that in one of the forks. Now I get the use case and try to merge changes form there.

**Comment by variar** [comment]
Added a context menu item to rename tabs in 19.12.0.544. Names are not saved to any configuration.

**Comment by m47730** [comment]
Thanks for this feature!
It will be cool if the named tabs info will be saved somewhere... Like last files opened.

Use case:
open every single log file for each application i own (still preserved across session of klogg) and name each tab accordingly based on application's name
a customer/collegue screams about a bug
reopen klogg (each tab is now named log.txt. ouch!)
search for exceptions in logs
