### ISSUE TITLE
Minor: Last line cut in follow mode file is screen long

### ISSUE THREAD

**Issue by wiz0u** [variar/klogg#117]
When the file has exactly the number of lines to fill klogg window without a vertical scrollbar, and you activate follow mode, the last line is painted over by the yellow/grey stripes, and you cannot scroll to view it

![image](https://user-images.githubusercontent.com/11647984/66549364-6ddc4880-eb43-11e9-9317-8620861b5972.png)

**Comment by nowhszh** [comment]
@variar  Does the status of the issue need to be updated

**Comment by variar** [comment]
Should be fixed in 23.06.0.1479+
