### ISSUE TITLE
On Linux (ubuntu) previous sessios is not saved

### ISSUE THREAD

**Issue by dia-susca** [variar/klogg#121]
Instead of opening the same files as in the last session, there is a tab saying: 
/home/username/.cache/.fr-TrUJtx/server.log (0 B - 0 lines - UTF-8)

The files were opened in a mounted directory, but it's the same directory every time.

**Comment by dia-susca** [comment]
I don't know if this helps, but here is the terminal output when files get opened:

> Gtk-Message: 08:00:08.490: GtkDialog mapped without a transient parent. This is discouraged.
> 08:00:18.364 ERROR [7015] [LogFilteredData::findLogDataLine@405] Index too big in LogFilteredData: 0 cache size 0
> 08:00:18.498 ERROR [7015] [LogFilteredData::findLogDataLine@405] Index too big in LogFilteredData: 0 cache size 0
> 08:00:19.538 ERROR [7015] [LogFilteredData::findLogDataLine@405] Index too big in LogFilteredData: 0 cache size 0
> 08:00:21.090 ERROR [7015] [LogFilteredData::findLogDataLine@405] Index too big in LogFilteredData: 0 cache size 0

**Comment by variar** [comment]
Looks like some caching is happening on level lower than klogg, so it receives file from that cache directory. Not sure what can be done to get real filename

**Comment by variar** [comment]
@dia-susca could you check if those files in /home/username/.cache are symlinks to mounted directory? It that is the case then klogg can store paths that these links point to.

**Comment by dia-susca** [comment]
so, the file it tries to open is :
/home/diana/.cache/.fr-TrUJtx/server.log 

But in that folder, there is no such sub-folder: .fr-TrUJtx
the folder is specified in this file: klogg_session.conf 

I created the folder by hand. Let's see if it will work at least sometimes.

In Ubuntu 18.04 LTS (which I use) - 75% of the time, clicking on open with previous session opens a fresh session, without any history saved. 25% of the time, I get the error with the path to the temp folder, and I can see under File menu the last files I used, and I can retrieve my session from there.

**Comment by dia-susca** [comment]
Ok, so now I made a lot more tests.

First, the problem occurs for any files - mounted folders or not.
Second, the .cache/... folder is not a symlink. It did not exist, but I created it myself. including a server.log file that I assumed was supposed to be there
Third, I call klogg from a desktop shortcurt, that I created based on instructions off the internet:
  Basically, I created a usr/share/applications/klogg.desktop  file with this content:
```
[Desktop Entry]
Name=klogg
GenericName=Log file viewer
Exec=klogg %F
Icon=klogg
Type=Application
Comment=A smart interactive log explorer.
Terminal=true
Categories=Utility;TextTools;Development;
MimeType=text/plain;
Actions=Session;NewInstance;

[Desktop Action Session]
Exec=klogg --load-session %F
Name=Open With Previous Session

[Desktop Action NewInstance]
Exec=klogg --multi %F
Name=Open In A New klogg Window

```
Could this be relevant?
These are the commands called when I click on the klogg icon. 
Basically, 'Open with previous session' also sets the parameter --load-session. But, even when I click on 'New window' I get the same problems, so I probably don't need the 'Open With previous session entry'?

Now, searching in the whole / by klogg got me a /home/diana/.config/klogg/klogg_session.conf  file, with the following (truncated)content:

```
[General]
version=1

[OpenFiles]
openFiles\1\fileName=/home/diana/.cache/.fr-TrUJtx/server.log
openFiles\1\topLine=0
openFiles\1\viewContext="{\"AR\":false,\"FF\":false,\"IC\":false,\"M\":[],\"RE\":true,\"S\":[753,248]}"
openFiles\size=1
version=1

[RecentFiles]
filesHistory\1\name=/home/diana/.cache/.fr-TrUJtx/server.log
filesHistory\2\name=/home/diana/logs/Server1/SystemOut.log
filesHistory\3\name=/home/diana/logs/Server2/SystemOut.log
filesHistory\size=3
version=1
.....
```

The good news is that even though most of the time I get a blank klogg application, occasionally I will get an empty 'opened' file  (/home/diana/.cache/.fr-TrUJtx/server.log (0 B - 0 lines - modified on 09.10.2019 15:13 - UTF-8) ), and when that happens, I can see under File menu the history of my previously opened files, and I can open them directly from there. 



I don't know if it's relevant, but the app starts in a new terminal window, and I can see the following error many times:
12:52:34.829 ERROR [19270] [LogFilteredData::findLogDataLine@405] Index too big in LogFilteredData: 0 cache size 0

**Comment by variar** [comment]
Thanks for more information. Looks like I need to get myself a VM with Ubuntu and try to reproduce this issue.

That error is fine. I'll remove false logging in next builds

**Comment by variar** [comment]
I've tried it on ubuntu VM. Restoring last session seems working fine in simple cases. There might be issues if log files are opened from "remote" filesystems using gvfs. Need some time to test this.

@dia-susca could you enable logging at level 5 in advanced options, open some files that end up with .cache folder in path, restart klogg and attach both log files before and after restart to this issue? Logs should be in /tmp/klogg_2020-....log.

**Comment by variar** [comment]
Session restore behaviour changed a bit. Please check latest nightly builds and feel free to reopen.
