### ISSUE TITLE
A bit hard to get out of 'follow mode' using mouse wheel

### ISSUE THREAD

**Issue by wiz0u** [variar/klogg#125]
When 'Follow mode' is active and you use the mouse wheel to scroll up, expecting the follow mode to get disabled in the process, it can be quite hard.
I have sometimes to retry 6 times using the mouse wheel to scroll up to get the 'follow mode' disabled and finally can scroll up the file. Most of the time, the 'follow mode' remains active and the file scrolls back immediately to the end.

My mouse control panel has the mouse wheel configured with the default settings of 3 lines per wheel bit (not sure the english terms for that)

**Comment by variar** [comment]
Should be easier now. @wiz0u please check if it is ok.

p.s.
I can make this needed scrolling configurable, but don't want to complicate code.

**Comment by wiz0u** [comment]
Seems good to me now. Thanks!
