### ISSUE TITLE
Clarify encoding display in status bar

### ISSUE THREAD

**Issue by variar** [variar/klogg#127]
Replace "System" with "System locale (XYZ)" (and possibly put this also in the Encoding menu instead of "Local")
And also I would switch the "Displayed as" logic for a "Detected as" logic.

Which means:
- Replace "XYZ" with "Detected as XYZ" (to clearly state this is the result of the auto-detection of encoding)
- Replace "Displayed as XYZ" with "XYZ" (nothing more to say because it's the explicit choice of the user)

_Originally posted by @wiz0u in https://github.com/variar/klogg/issues/109#issuecomment-552936687_

**Comment by variar** [comment]
I think it might be better to leave "displayed as" and add "detected as". Otherwise there might be a confusing idea that klogg is changing encoding of opened file.

**Comment by wiz0u** [comment]
> 
> 
> I think it might be better to leave "displayed as" and add "detected as". Otherwise there might be a confusing idea that klogg is changing encoding of opened file.

ok

**Comment by variar** [comment]
done in build >502

**Comment by wiz0u** [comment]
You fixed the "displayed as" and add "detected as" part but not the confusing "system" captions.
Currently, the Encoding menu shows item "System (System)" and when selected, the status bar shows "Displayed as System". This gives no clue as what the actual System encoding is.

Note that when I select Auto, status bar displays "ISO-8859-1" which seems right and might be my system ACP/ANSI codepage, although I think it's CP1252 to be precise.
Also note that either "ISO-8859-1" or "CP1252" are not available options in the Encoding menu (which is fine with me if the "System" options become "System (CP1252)" or something like that, according to the system codepage)

**Comment by wiz0u** [comment]
Ohh apparently the "ASCII" option in the encoding menu gives "Displayed as ISO-8859-1".
Please rename "ASCII" as "ISO-8859-1" or something more precise, because ASCII only defines precisely the character values 0-127

**Comment by variar** [comment]
I try to use Qt names for text codecs. For some reason on Linux this does the right thing and I get System(UTF-8), and on Windows we are getting System(System). Might be some name aliasing issue.

**Comment by variar** [comment]
In build 19.12.0.527 I am using GetACP() from Window API to get ANSI codepage and text codec for it. This should produce meaningful name for system encoding on windows. Also added other encodings supported by Qt without ICU.

**Comment by wiz0u** [comment]
Looks fine now
(I like the new Encoding menu)
