### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by variar** [variar/klogg#129]
Consider providing dark theme variant like one from lengocthuong15/dark-klogg@b623d0e8d25c93734f0aecce2de295c08ad2285f

**Comment by variar** [comment]
Also checkout qdarkstyle from https://github.com/sergei-dyshel/glogg/commit/c144d004c9eaa9068bda51ad4acded37f3f0bc06

**Comment by johnsonzhuangsh** [comment]
Waiting on this.

**Comment by variar** [comment]
Fixed some color palette issues and added auto-inversion for icon loading in b78b2ed0aa60646476566ef396da264412bb2f3c.

Klogg now looks ok using either light or dark Breeze themes from KDE. Need more testing in Windows and Mac environments.

**Comment by variar** [comment]
Suppor for windows will be with Qt 5.15. See https://bugreports.qt.io/browse/QTBUG-72028

**Comment by variar** [comment]
Same issue in Glogg nickbnf/glogg#274

**Comment by redfellow** [comment]
Partial dark support can be done via highlighters, but it doesn't indeed resolve the app itself being light.

I hope the Qt issue is resolved soon. If not, perhaps you could add color options to the app itself?

![image](https://user-images.githubusercontent.com/1110164/92393063-eec30c00-f127-11ea-8397-90be36660b33.png)

**Comment by variar** [comment]
Switched builds 20.9.+ to Qt 5.15 on Windows. However, looking at Qt BUG 72028 Dark style is still experimental there.

**Comment by variar** [comment]
Added [QDarkStyle](https://github.com/ColinDuquesnoy/QDarkStyleSheet) and combobox to select styles in Tools->Options->View. Should land in 20.9.0.674+.

![image](https://user-images.githubusercontent.com/1620716/94104146-047e4400-fe3f-11ea-9eca-7f7e2be4ff13.png)

**Comment by redfellow** [comment]
Works for me. 

I'm not sure if it's related to enabling the dark mode, but on 20.9.0.680 the highliters no longer work. They worked until I exported, removed, and imported one back. Now I can't get any to highlight anything, and reverting to default theme does not affect it.

**Comment by variar** [comment]
There is still much to improve. Contrast is arguably too high and marks outline should be dark. But creating themes is not really my area of expertise. If anyone can suggest better dark stylesheet for qt, I'll be glad to try.

**Comment by xhargh** [comment]
There seems to be an issue in the QDarkSheet that shows itself here also:
https://github.com/ColinDuquesnoy/QDarkStyleSheet/issues/200

<img width="620" alt="image" src="https://user-images.githubusercontent.com/8505258/94451450-b2c31a00-01ae-11eb-8a39-3ed2bfd8360d.png">

Tested on a Mac with Catalina 10.15.7

**Comment by variar** [comment]
QDarkSheet authors recommend using Qt LTS version. I'm thinking about it for CI builds

**Comment by variar** [comment]
@xhargh Indeed switching to Qt 5.12 on Mac seems to fix this issue with combo-boxes.

**Comment by variar** [comment]
I'm closing this issue as general request for dark theme is complete. Please open separate issues for any glitches.
