### ISSUE TITLE
Minor annoyance: caret in path textbox visible even after focusing elsewhere

### ISSUE THREAD

**Issue by wiz0u** [variar/klogg#130]
When you click in the path textbox, a (non-blinking) caret appears allowing for (read-only) selection.

The annoying part is that this caret doesn't disappear when I click somewhere else, or if I move/resize/unfocus the whole window.

Strangely, if there are characters in the selection (not just a caret) then the selection correctly disappear when clicking somewhere else.

Probably a QT issue, but annoying anyway.

**Comment by variar** [comment]
It is a Qt issue for labels with selectable text, Labels can be replaced with read-only edit boxes, they don't have such problem.

**Comment by wiz0u** [comment]
You can close this bug as WONTFIX if you don't want to use a read-only edit box

**Comment by variar** [comment]
Looks like that has been fixed in Qt 5.15
