### ISSUE TITLE
Closing a file should put it in front of the recent files menu entries

### ISSUE THREAD

**Issue by wiz0u** [variar/klogg#131]
I often get in the situation where I inadvertently close a file, and surprised by the fact that it doesn't show up in the recent files entries.

I think a file that was just closed should be inserted/moved in first position of the recent files menu entries, for quick reopening.

**Comment by variar** [comment]
Should be fixed in 21.07.0.1073. Adjusting recent files works only when tabs are closed manually. If klogg is shut down all together, recent files are not changed.
