### ISSUE TITLE
Crashes on startup when prior file no longer exists

### ISSUE THREAD

**Issue by jeffjensen** [variar/klogg#133]
Starting with a release after v501, (I verified problem exists with 504, 505, 506), Klogg crashes when reopening files from last session and one of the files no longer exists.

Prior, Klogg successfully opened and the tab existed with an empty content pane.
This was useful because of "clean builds" removing log files and Klogg keep them in the tab list (and startup successfully!).

**Comment by variar** [comment]
Should be ok in 507. But need more test in CI to prevent such issues.

**Comment by jeffjensen** [comment]
Works again!  :-)  Thank you for the very fast turn around.
