### ISSUE TITLE
Open file in follow mode

### ISSUE THREAD

**Issue by wiz0u** [variar/klogg#136]
Could you add a setting in the Options dialog so that any newly opened file is automatically opened with Follow mode active?

**Comment by variar** [comment]
Done in 19.12.0.521

**Comment by wiz0u** [comment]
The feature works (thanks!). But the option is not saved on exit

**Comment by variar** [comment]
Fixed configuration saving in 19.12.0.528

**Comment by wiz0u** [comment]
Works fine now
