### ISSUE TITLE
Opening files through sftp does not automatically update file content

### ISSUE THREAD

**Issue by dia-susca** [variar/klogg#140]
Ideally, one should be able to tail a log on a remote server location. 

I can open a log file with a sftp:// location, but I need to manually click the reload button to get it to refresh. It would be great if it worked like a tail command, to automatically update the file content as it is written.

**Comment by variar** [comment]
I am afraid OS does not notify on such file changes. However,  polling for file changes could work. It can be enabled from File tab in Options dialog

**Comment by variar** [comment]
@dia-susca does polling help to get file updated?

**Comment by dia-susca** [comment]
I mean, it gets refreshed, but it's not a 'tail' quality like other log viewers :)
still, better than nothing

**Comment by variar** [comment]
I'm afraid it is as good as it gets for now

**Comment by Shentoza** [comment]
Wait sftp is possible? When I try to enter a sftp url to the open url field, it says "protocol sftp is not supported
