### ISSUE TITLE
When copying multiple lines, empty lines are missing

### ISSUE THREAD

**Issue by wiz0u** [variar/klogg#143]
Select a series of lines from the main window, then select Copy
=> Empty lines are missing in the clipboard (except maybe if it is the first line)

**Comment by variar** [comment]
Should be ok in 19.12.0.545

**Comment by wiz0u** [comment]
nok
empty lines are now output as 0D 0D 0A (in Windows) instead of 0D 0A

**Comment by wiz0u** [comment]
seems fine now
