### ISSUE TITLE
On klogg restart, follow mode not active/in-sync for the search panel of already-opened files

### ISSUE THREAD

**Issue by wiz0u** [variar/klogg#144]
After closing klogg with files opened in follow mode, restarting klogg reload those files but the follow mode is correctly applied only on the content view, not on the search pane.

(exception: the first tab doesn't seem to have this problem, other tabs do)

**Comment by variar** [comment]
Should be fixed in 19.12.0.540

**Comment by wiz0u** [comment]
seems ok now
