### ISSUE TITLE
Highlighter window not rendering properly

### ISSUE THREAD

**Issue by federico-piazza** [variar/klogg#146]
When creating highlights on Mac (Catalina) the rendering does not work properly.

Video recording:
https://gofile.io/?c=vwRYfd

**Comment by variar** [comment]
Can't reproduce it on my High Sierra virtual machine using latest build :( Maybe there are some steps required that are not on that video?

**Comment by federico-piazza** [comment]
High Sierra is very old and it's using APIs that were deprecated, some don't exist in Mojave and later in Catalina there was whole new refactor.

**Comment by variar** [comment]
Updated my VM to Catalina. It works way better, thanks for the push ) However, still can't reproduce this issue. I strongly suspect that VM is using software rendering and on real MacOS some opengl hardware acceleration is used and this is causing troubles. I'll try to look through code to see if there is something unusual in this particular dialog.

**Comment by variar** [comment]
Googling for some clues I've found this thread https://www.qtcentre.org/threads/32256-QListWidget-refreshing-issue. Tried the solution form it to cause selection change in QListWidget using event loop instead of direct call

**Comment by variar** [comment]
@federico-piazza could you try build 19.12.0.548 or higher?

**Comment by variar** [comment]
Got subscription for MacStadium to get access to real hardware. I can confirm problem with 19.12.0.543 and it is not reproduced in 19.12.0.550

**Comment by federico-piazza** [comment]
@variar I can confirm this issue is fixed, but now there is a new one. I will create the bug and upload the video
