### ISSUE TITLE
Highlighter window not rendering properly when removing rule

### ISSUE THREAD

**Issue by federico-piazza** [variar/klogg#149]
After the fix of https://github.com/variar/klogg/issues/146 the rule addition is working properly, however when we try to remove a rule the rendering is not working well.

Check the video link:
https://gofile.io/?c=Nxm4U6

**Comment by variar** [comment]
Could you check if move up/down work well?

**Comment by federico-piazza** [comment]
@variar, yes... up/down work well.

**Comment by variar** [comment]
Tried the same trick as with adding in build 19.12.0.544

**Comment by federico-piazza** [comment]
I tested `build 19.12.0.544` and works perfectly well now. Thanks a lot!
