### ISSUE TITLE
Open dialog preselected path is wrong (Windows)

### ISSUE THREAD

**Issue by wiz0u** [variar/klogg#150]
When clicking "Open...", it seems the Open dialog now tries to preselect the folder of the currently opened file, but it does not work correctly.

In the example below, you can see the current file path (behind) and the Open dialog opens in the wrong folder with a typed-in filename showing a path containing forward slashes and missing drive letter
![image](https://user-images.githubusercontent.com/11647984/71591836-1c35cf80-2b2e-11ea-9c2a-877d33348448.png)

**Comment by variar** [comment]
Looks like allowing url in open dialog breaks it on windows. Will revert to original behavoir as there is  dedicated menu item to open remote file

**Comment by variar** [comment]
Should be fixed in 19.12.0.556

**Comment by wiz0u** [comment]
It's fixed.
Note: strangely, when launching 556 the first time, I got an empty klogg window instead of the previously opened files

**Comment by variar** [comment]
That's surely is unexpected. Are other settings in place or  switched back to defaults?

**Comment by wiz0u** [comment]
The other options (like highlights) seems still good

**Comment by wiz0u** [comment]
My update process is the following: Close klogg_portable, open the new portable zip version, extract all files to the klogg binary folder, run klogg_portable

**Comment by wiz0u** [comment]
I found the problem. See https://github.com/variar/klogg/issues/153
