### ISSUE TITLE
Prompt when Favorites is not found

### ISSUE THREAD

**Issue by wiz0u** [variar/klogg#152]
When opening a missing file from the Favorites menu, a message box should be stating "File not found" with the full file path.
(Currently, nothing happens)

Optionally you could add a question to the message: "Do you want to remove it from Favorites menu?" with Yes/No (and default option being No)

**Comment by redfellow** [comment]
Even without fancier gui options, a way to remove favourites that don't exist is needed.

**Comment by variar** [comment]
@wiz0u added a message box for Favorites and Recent files. Should be in 20.9.0.674.

@redfellow there is a menu option to remove any file from favorites list. A combobox there allows to select files that do not exitst

**Comment by redfellow** [comment]
I was confused where the combobox was, but after clicking on random, I realized it's just not visible for me. (Windows 10). 

![image](https://user-images.githubusercontent.com/1110164/94140775-6efda700-fe74-11ea-8506-578e8412aa64.png)

**Comment by variar** [comment]
Looks ok in my tests. Closing for now. Feel free to reopen if this issue reproduces in builds > 20.10.0.746
