### ISSUE TITLE
Closing new empty window => problem on restart

### ISSUE THREAD

**Issue by wiz0u** [variar/klogg#153]
Open klogg and a bunch of file
Click on "New window"
Close the empty new window

Case A:
Close the main window with the X in the corner
=> Problem: When restarting klogg, you get an empty window instead of your previously opened files

Case B:
Select File > Exit
=> Problem: When restarting klogg, you get your previously opened files and another empty window

**Comment by variar** [comment]
Logic behind closing windows got broken. It should work like this:
1. When exiting application using Exit from the menu then for all windows positions and open files are saved.
2. When closing some window usign X button then if it is not last window then it is removed from saved windwos and will not reopen on next start.
3. When closing last window using X button then its open files and geometry is saved (this is same behavior as if "new windows" feature was disabled in options).

**Comment by wiz0u** [comment]
> Logic behind closing windows got broken. It should work like this: [snip]
I agree with this logic. Same as Firefox tabs.

**Comment by variar** [comment]
Looks fine in 20.1.0.578

**Comment by wiz0u** [comment]
Seems fine now.
