### ISSUE TITLE
Add keyboard shortcut to "Filtered View search criteria" field

### ISSUE THREAD

**Issue by jeffjensen** [variar/klogg#155]
Alt+s executes the search and I want to avoid using the mouse to navigate to the search criteria field to replace or update its text.

IIRC, I found Alt+s some time ago by trying various keystrokes looking for this shortcut.  Hopefully one exists and I have not found it yet!

**Comment by variar** [comment]
I didn't know about Alt+S :) Need to update documentations

**Comment by variar** [comment]
Added shortcut Shift+F to focus search string. Ctrl+F is already binded to quickfind.

Alt+S was an accident. Alt+<letter> is reserved for menu accelerators. I removed it.

**Comment by variar** [comment]
Changed to Ctrl+S to avoid printing capital F in case search string is already selected

**Comment by jeffjensen** [comment]
FYI Shift+f stopped working a couple of builds ago.  Not working with current 579.

**Comment by jeffjensen** [comment]
> FYI Shift+f stopped working a couple of builds ago. Not working with current 579.

Not working with 582 too.

**Comment by variar** [comment]
Shift+F has been replaced with Ctrl+S. That way no new characters are added to search string if it is already selected. However, it works only if focus is in log view that can be annoying. I'll see what can be done.

**Comment by variar** [comment]
Should work in 20.1.0.586

**Comment by jeffjensen** [comment]
Ctrl+S and Ctrl+Shift+F have been working well for some time.  Thank you!
