### ISSUE TITLE
Add Help -> Keyboard Shortcuts popup

### ISSUE THREAD

**Issue by jeffjensen** [variar/klogg#156]
Related to #155, please add a keyboard shortcuts info panel for users to easily learn the available options.

Could also add shortcuts in controls' tooltips.

**Comment by variar** [comment]
May be done by #26

**Comment by jeffjensen** [comment]
Where is https://github.com/variar/klogg/blob/master/doc/documentation.rst published to?  I cannot find it - haven't seen links or hints from README, github topic desc, About in app, etc.

**Comment by jeffjensen** [comment]
Created PR https://github.com/variar/klogg/pull/158 to help with exposing the doc page.

**Comment by variar** [comment]
Documentation.rst It should end up in installer as readme.html file. I'll add a link to it in UI. Looks like it should be renamed to DOCUMENTATION.rst and moved to the root of repository.

**Comment by variar** [comment]
Add an item in Help menu that opens embedded html documentation.
