### ISSUE TITLE
UI: change Follow button icon

### ISSUE THREAD

**Issue by wiz0u** [variar/klogg#160]
I'm not really fond of the new "Follow" button icon which convey more a 'recycle/reload' feeling rather than 'follow'.

I would prefer a double down arrow (something like this: ![image](https://user-images.githubusercontent.com/11647984/72055648-80455a00-32cb-11ea-9e63-78b3fcd609d9.png)) which convey a 'fast-forward to the bottom of file' feeling.

**Comment by variar** [comment]
Changed icon to  "double down arrow" in 20.1.0.578. I try to use icons from https://icons8.com/icons/small set so that they have consistent style. If there is anything more suitable for "follow" concept I'll be glad to use it.

**Comment by wiz0u** [comment]
Thanks. And thank for the link
