### ISSUE TITLE
Horizontal scroll page-step is too small

### ISSUE THREAD

**Issue by wiz0u** [variar/klogg#163]
When clicking in the middle of the horizontal scrollbar, it only scroll 10 characters to the right or so...

It is supposed to scroll one viewpage to the right
(however for a better user experience, I would suggest to scroll 7/8 of the visible line width to the right, not a full page)

Also, when you're done indexing the file on load, it should be possible for the horizontal scrollbar thumb to be sized adequately to match the longest line of the full file (instead of the current very small size)
(I don't know Qt, but maybe solving the page-step issue will automatically resize the scrollbar thumb adequately)

**Comment by variar** [comment]
Should be fixed in 21.07.0.1073
