### ISSUE TITLE
Issue with Search expression letter case & search history

### ISSUE THREAD

**Issue by wiz0u** [variar/klogg#164]
First, you input "Test" in the search pane and validate with Enter.

Then you can no longer search for "test" (with lowercase T), because each time you validate with Enter, klogg tries to match with the "Test" entry that is added to the drop-down search history.
(it happens even if you discard the suggested completion with Escape before validating with Enter)

This is an issue when the "Match case" option is active and you really want to search for a letter-case variant of a previously entered search expression.

**Comment by variar** [comment]
That's an unexpected issue with QCompleter. Setting it to Case Sensitive mode doesn't help. Some more research is required. Meanwhile canceling completion with Escape and then searching not by Enter, but by clicking search button works as expected

**Comment by variar** [comment]
Tried setting QCompleter case sensitivity mode once again. For some reason now it looks fine. Should be in build 20.9.0.657.
