### ISSUE TITLE
"/" keycommand cannot work

### ISSUE THREAD

**Issue by eikei54** [variar/klogg#169]
In version 20.1.0.586, (Windows10, x64.), "/" key cannot work for search.
Please support to fix it.

**Reproduce_Step:**
- Open Log
- By inputting "search key" in Edit Box, the filter window shows the filtered result.
- **Type "/" key in keyboard, no action happen**
   ->  instead of "/" typing, "Ctrl + F" key combination will open "search" window
            that has "Ignore case", "Previous", "Next" option.

In glogg, "/" key can work for the selected text in bottom window that was result for "find text".

**Comment by variar** [comment]
"/" is used to search for the previous occurrence of the currently selected text. If no text is selected then this key has no action.

**Comment by eikei54** [comment]
Thanks for your comment.
But even if the selected text exist, "/" is not seemed to work so far.

in glogg, "/" key can work for the selected text in bottom window that was result for "find text".

My environment is Windows10, x64.

**Comment by variar** [comment]
I’ve reworked hotkeys in klogg, could you try your scenario in 21.07.0.1066?
