### ISSUE TITLE
Panel position is not remembered when launching file from command line

### ISSUE THREAD

**Issue by safield** [variar/klogg#174]
When I close and then reopen klogg, it remembers the last position of the bottom search panel. If I slide the search panel out of view, when I open klogg again, the search panel will be how I left it.

If I launch a file from the command line eg "klogg log1.log", the search panel is always in it default visible position.

**Comment by variar** [comment]
Indeed launching from command line with specific file name does not restore last session settings including geometry. I think that panel positions should be saved and restored in this case.

**Comment by variar** [comment]
#166 might be related

**Comment by variar** [comment]
In builds 21.05.0.912 default splitter position can be saved using context menu. It should be applied for all new files.

**Comment by variar** [comment]
In builds 21.05.0.912 default splitter position can be saved using context menu. It should be applied for all new files.

**Comment by variar** [comment]
Closing for now. Feel free to reopen if behavior should  be changed.
