### ISSUE TITLE
ctrl+pgUp / pgDown to cycle open file tabs

### ISSUE THREAD

**Issue by safield** [variar/klogg#175]
In all applications I use that use tabbed windows (firefox, chrome, various terminals on windows and linux, Sublime Text, vscode), all use the keyboard shortcuts of ctrl+page_up and ctrl+page_down to cycle through open tabs.

It would be nice if klogg also had this default keyboard shortcut to match this ubiquitous behaviour.

**Comment by variar** [comment]
What klogg version are you using? This looks like #113 that was fixed in current pre-release builds

**Comment by safield** [comment]
Thanks for reply.

Klogg Version: 19.9.0.467.

**Comment by variar** [comment]
Than that issue is fixed in latest version. I expect to prepare a release by the end of February
