### ISSUE TITLE
Add key shortcuts Ctrl+Up Ctrl+Down for scroll window cursor stays

### ISSUE THREAD

**Issue by jeffjensen** [variar/klogg#177]
Similar to editors, using Ctrl+Up|Down arrows scroll the window accordingly and keep the cursor on the same line.  This is same behavior as the Up / Down arrows.  It's simply a usability issue that I regularly try to use them with the Ctrl key out of habit!  It takes me a second to realize the issue when the scrolling doesn't happen.

**Comment by variar** [comment]
Those shortcuts might do something else and that code might be broken. Shortcuts handling code is more like spaghetti. I'll look into it.
