### ISSUE TITLE
Add list of open tabs to select one to view

### ISSUE THREAD

**Issue by jeffjensen** [variar/klogg#180]
When having many tabs open, I miss having a list/menu of tabs to pick the tab to view as it is more convenient and faster than scrolling the tabs with the mouse or keyboard.

**Comment by variar** [comment]
Thanks for the idea. It really is annoying to cycle through tabs using those small arrows.

**Comment by variar** [comment]
Added submenu in View menu. Should be in 20.5.0.601. Any ideas on making this more usable are welcome.

**Comment by jgscherber** [comment]
I think VS2019 has a nice UI for this - there's a small toggle on the far right that drops down a list of open files

![image](https://user-images.githubusercontent.com/6207661/82248575-fe66dc80-990d-11ea-886d-521acc18d4b9.png)

**Comment by jeffjensen** [comment]
I try to stay on the keyboard as much as possible so appreciate any design having keyboard nav.

My immediate suggestion is with the file names in the list - all of mine have long dir paths, so the current truncation strategy keeps the file name (a good thing), keeps the path starting dirs, and truncates/removes the last dirs - I cannot tell which file it is because most of the names are the same.

Is it possible to increase the length of the file names in the menu?
Is it possible to truncate the path differently?  For me, the last few dirs are most important.  I suggest keeping the last 2-3 dirs, truncate the ones before it, keep some in the beginning.

**Comment by variar** [comment]
I've increased truncation limit to 128 characters. And added a simple dialog to select opened files. Should open via Ctrl+Shift+O shortcut. Combo-box can be expanded with space.

**Comment by jeffjensen** [comment]
Thank you!  It's now long enough that I can see the full path and file name in the list. :)

Nice popup and shortcut for it too.  An improvement idea for it is typing to find path/file in the list - perhaps a list box and typing filters the entries.

**Comment by variar** [comment]
Thanks for the idea. I've already used this popup several times today. Really useful :)

List box with filtering is definitely on todo list.

**Comment by variar** [comment]
@jeffjensen I've added filtering like you suggested. Should land in 20.10.0.747.

**Comment by jeffjensen** [comment]
Works great!  Thank you very much.
