### ISSUE TITLE
Unable to to open URL over https - Download failed: SSL handshake failed

### ISSUE THREAD

**Issue by fflatorre** [variar/klogg#182]
Details for the issue
--------------------

#### What did you do?
Tried to "Open from URL..." using an URL in the form of https://company.bamboo.co.uk/plan/logs.file.log

#### What did you expect to see?
The log file downloaded and made available in the editor

#### What did you see instead?
Nothing, not even an error message.
Enabled logs (verbosity 6) and got this message : 

> 13:18:34.649 INFO  [9332] [Downloader::download@44] Downloading https://company.bamboo.co.uk/plan/logs.file.log
> 13:18:34.661 VERB  [9332] [AbstractLogView::event@746] Event! Type: 103
> 13:18:34.661 VERB  [9332] [AbstractLogView::event@746] Event! Type: 103
> 13:18:34.661 VERB  [9332] [AbstractLogView::event@746] Event! Type: 103
> 13:18:34.661 VERB  [9332] [AbstractLogView::event@746] Event! Type: 103
> 13:18:34.683 VERB  [9332] [AbstractLogView::event@746] Event! Type: 12
> 13:18:34.683 VERB  [9332] [AbstractLogView::paintEvent@807] paintEvent received, firstLine=0 lastLineAligned=0 rect: 0, 0, 2549, 236
> 13:18:34.684 VERB  [9332] [AbstractLogView::paintEvent@898] End of repaint 608
> 13:18:34.684 VERB  [9332] [AbstractLogView::event@746] Event! Type: 12
> 13:18:34.684 VERB  [9332] [AbstractLogView::paintEvent@807] paintEvent received, firstLine=0 lastLineAligned=0 rect: 0, 0, 2530, 1026
> 13:18:34.688 VERB  [9332] [AbstractLogView::paintEvent@898] End of repaint 3012
> 13:18:34.701 VERB  [9332] [AbstractLogView::event@746] Event! Type: 12
> 13:18:34.702 VERB  [9332] [AbstractLogView::paintEvent@807] paintEvent received, firstLine=0 lastLineAligned=0 rect: 0, 0, 2549, 236
> 13:18:34.703 VERB  [9332] [AbstractLogView::paintEvent@898] End of repaint 655
> 13:18:34.703 VERB  [9332] [AbstractLogView::event@746] Event! Type: 12
> 13:18:34.704 VERB  [9332] [AbstractLogView::paintEvent@807] paintEvent received, firstLine=0 lastLineAligned=0 rect: 0, 0, 2530, 1026
> 13:18:34.708 VERB  [9332] [AbstractLogView::paintEvent@898] End of repaint 3632
> 13:18:34.716 VERB  [9332] [AbstractLogView::event@746] Event! Type: 25
> 13:18:34.716 VERB  [9332] [AbstractLogView::event@746] Event! Type: 25
> 13:18:34.722 DEBUG [9332] [EfswFileWatcher::notifyOnFileAction@262] fileChangedOnDisk C:/Users/xxxxx/AppData/Local/Temp/klogg_temp_.ooelsG application.log.QQlyun, old name 
> 13:18:34.723 DEBUG [9332] [EfswFileWatcher::findChangedFilename@304] fileChangedOnDisk - call but no file monitored
> 13:18:34.737 VERB  [9332] [AbstractLogView::event@746] Event! Type: 12
> 13:18:34.737 VERB  [9332] [AbstractLogView::paintEvent@807] paintEvent received, firstLine=0 lastLineAligned=0 rect: 0, 0, 2549, 236
> 13:18:34.738 VERB  [9332] [AbstractLogView::paintEvent@898] End of repaint 578
> 13:18:34.738 VERB  [9332] [AbstractLogView::event@746] Event! Type: 12
> 13:18:34.738 VERB  [9332] [AbstractLogView::paintEvent@807] paintEvent received, firstLine=0 lastLineAligned=0 rect: 0, 0, 2530, 1026
> 13:18:34.743 VERB  [9332] [AbstractLogView::paintEvent@898] End of repaint 4052
> 13:18:34.756 VERB  [9332] [AbstractLogView::event@746] Event! Type: 12
> 13:18:34.756 VERB  [9332] [AbstractLogView::paintEvent@807] paintEvent received, firstLine=0 lastLineAligned=0 rect: 0, 0, 2549, 236
> 13:18:34.758 VERB  [9332] [AbstractLogView::paintEvent@898] End of repaint 2053
> 13:18:34.759 VERB  [9332] [AbstractLogView::event@746] Event! Type: 12
> 13:18:34.760 VERB  [9332] [AbstractLogView::paintEvent@807] paintEvent received, firstLine=0 lastLineAligned=0 rect: 0, 0, 2530, 1026
> 13:18:34.765 VERB  [9332] [AbstractLogView::paintEvent@898] End of repaint 4562
> 13:18:34.864 ERROR [9332] [Downloader::downloadFinished@54] Download failed: SSL handshake failed
> 13:18:34.865 VERB  [9332] [AbstractLogView::event@746] Event! Type: 104
> 13:18:34.865 VERB  [9332] [AbstractLogView::event@746] Event! Type: 104
> 13:18:34.865 VERB  [9332] [AbstractLogView::event@746] Event! Type: 104
> 13:18:34.866 VERB  [9332] [AbstractLogView::event@746] Event! Type: 104
> 13:18:34.867 DEBUG [19896] [EfswFileWatcher::handleFileAction@241] Notification from esfw for C:/Users/xxxxx/AppData/Local/Temp/klogg_temp_.ooelsG\

**It's worth to mention I can access the same URL with other editors.**

Useful extra information
-------------------------
> Klogg version 20.1.0.588 (built on 2020-01-22 from commit 8eb87c4) [built for x86_64-little_endian-llp64]
> running on Windows 10 Version 1803 (winnt/10.0.17134) [x86_64]
> and Qt 5.14.0

**Comment by variar** [comment]
Thanks for bug report. Klogg uses Qt and openssl to handle https traffic on Windows. What certificate is used for https://company.bamboo.co.uk? Is it self signed or from some trusted provider?

**Comment by fflatorre** [comment]
@variar thanks for the prompt response, the certificate is self-signed ...

**Comment by fflatorre** [comment]
@variar please let me know if you need any other information to triage this issue. Thanks

**Comment by variar** [comment]
@fflatorre The root cause of this issue is that Qt does not trust self-signed certificates by default. I plan to add an option to allow such certs in one of next builds

**Comment by fflatorre** [comment]
Thanks @variar that would be super!!

**Comment by variar** [comment]
@fflatorre I've added an option to disable https certificates verification. It should appear under Options->File->File download in build 20.5.0.594

**Comment by fflatorre** [comment]
@variar just tested and works like a charm ! Thanks a mill :)
