### ISSUE TITLE
Does possible to add the string type for highlight ?

### ISSUE THREAD

**Issue by jimmy123j** [variar/klogg#183]
Highlight function is great, but only support the "Regexp", not support the "string"
I hope can highlight the string with operator e.g. (F) or (A) ... etc.
Sorry for bad english and thanks for great S/W

**Comment by variar** [comment]
@jimmy123j thanks for suggestion. Should be available in builds 20.9.0.689+

**Comment by variar** [comment]
Looks ok in my tests. Closing for now. Feel free to reopen if this issue reproduces in builds > 20.10.0.746
