### ISSUE TITLE
Highlighters: toggle to highlight only the match, not the whole line

### ISSUE THREAD

**Issue by duke1995** [variar/klogg#189]
At the moment when a match is found for a pattern, the whole line is always highlighted.
It would be nice to be able to highlight only the match, not the whole line.
A checkbox could be added to select which mode is wanted for each pattern so that by default the whole line would be highlighted (the current behaviour).

This is similar to the "word mode" feature in LogExpert (which is only available for Windows though, not for Linux).

Both modes could then also be mixed. For example a first pattern could highlight the whole line whereas subsequent patterns could highlight different parts of the same line in other colors.

**Comment by variar** [comment]
Thanks for suggestion. Looks useful

**Comment by variar** [comment]
Implemented a checkbox to toggle each highlighter mode. Merging several pattern works like this:
 1. Highlighters priority is from top to bottom, top one has the most priority.
 2. Highlighters with lower priority are overridden. 

So if there is some whole-line highlighter in the middle of the set, then all lower highlighters will not be visible, but all higher highlighter that are in only-match mode will be applied.

![image](https://user-images.githubusercontent.com/1620716/93527448-8eab4180-f941-11ea-8e6b-f891e1731cbe.png)

Special thanks to @treissler for great idea about highlight patterns merging algorithm.

**Comment by variar** [comment]
Found a bug with highlighting lines with expanded tab characters. Coloring is off by some columns.

**Comment by variar** [comment]
Fixed highlights for lines with tabs. Should be ok in 20.9.0.671+

**Comment by variar** [comment]
Nope, there are still issues if tab is part of the match.

Also this is not very useful to highlight something like "third column based on spaces". Need to add support for capturing groups in highlighter regex.

**Comment by variar** [comment]
Now highlighting capture groups solves tab problem somewhat:
![image](https://user-images.githubusercontent.com/1620716/94246442-695f9a00-ff24-11ea-8f96-0a70d6b34688.png)

**Comment by variar** [comment]
Looks ok in my tests. Closing for now. Feel free to reopen if this issue reproduces in builds > 20.10.0.746
