### ISSUE TITLE
Re-opening files from a network drive causes klogg to hang

### ISSUE THREAD

**Issue by jgscherber** [variar/klogg#193]
STR
1. Have "Load last session" option enabled
2. Open a log file on a network drive
3. Close klogg
4. Disconnect from network drive (e.g. disconnect from VPN)
5. Open a local log file

ER: Local log file opens immediately
AR: klogg UI hangs with nothing displayed

Workaround
* delete `klogg_session.ini` in `%appdata%`
* disable "Load last session" option

**Comment by variar** [comment]
Looks like very large timeout before klogg gets notified that file is unavailable. Loading initial files should be moved to separate thread.

**Comment by variar** [comment]
Looks ok with new file open scheme in 20.9.0.680

**Comment by variar** [comment]
Looks ok in my tests. Closing for now. Feel free to reopen if this issue reproduces in builds > 20.10.0.746
