### ISSUE TITLE
Open an empty tab for non-existent CLI-specified files

### ISSUE THREAD

**Issue by jeffjensen** [variar/klogg#194]
When Klogg has a file open and it's then deleted, Klogg keeps the tab open but removes the contents.  I like this behavior.  This works well for clean builds.

However, when starting Klogg with dirs in a "clean state", Klogg ignores specified files.  I have scripts to launch Klogg with multiple files.  At startup, if the files exist, Klogg displays them and if the files do not exist, Klogg ignores them.  When the missing files exist again, I restart Klogg with a script to have them opened together.

This request is to have Klogg open tabs for all CLI-specified files and not ignore ones that don't exist as, in my case, soon they will exist.

**Comment by variar** [comment]
@jeffjensen should be in 20.9.0.676+

**Comment by jeffjensen** [comment]
Works great, thank you!
