### ISSUE TITLE
Build release on older platform like centos/rhel 6/ubuntu 14.04?

### ISSUE THREAD

**Issue by owlfox** [variar/klogg#195]
Hi variar,
Thank you for maintaining such a wonder tool.
Just wondering if klogg supported on older linux platforms like centos/rhel 6?

I have tried the appimage, and other packed binaries but got:
```
fuse: warning: library too old, some operations may not work
./klogg-17.12.0.245-x86_64.AppImage: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by ./klogg-17.12.0.245-x86_64.AppImage)
./klogg-17.12.0.245-x86_64.AppImage: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by ./klogg-17.12.0.245-x86_64.AppImage)
./klogg-17.12.0.245-x86_64.AppImage: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.19' not found (required by ./klogg-17.12.0.245-x86_64.AppImage)
./klogg-17.12.0.245-x86_64.AppImage: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by ./klogg-17.12.0.245-x86_64.AppImage)
./klogg-17.12.0.245-x86_64.AppImage: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./klogg-17.12.0.245-x86_64.AppImage)
./klogg-17.12.0.245-x86_64.AppImage: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ./klogg-17.12.0.245-x86_64.AppImage)
./klogg-17.12.0.245-x86_64.AppImage: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by ./klogg-17.12.0.245-x86_64.AppImage)
./klogg-17.12.0.245-x86_64.AppImage: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./klogg-17.12.0.245-x86_64.AppImage)
./klogg-17.12.0.245-x86_64.AppImage: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/.mount_klogg-8vVRBN/usr/bin/../lib/libQt5Widgets.so.5)
./klogg-17.12.0.245-x86_64.AppImage: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/.mount_klogg-8vVRBN/usr/bin/../lib/libQt5Concurrent.so.5)
./klogg-17.12.0.245-x86_64.AppImage: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/.mount_klogg-8vVRBN/usr/bin/../lib/libQt5Gui.so.5)
./klogg-17.12.0.245-x86_64.AppImage: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/.mount_klogg-8vVRBN/usr/bin/../lib/libQt5Network.so.5)
./klogg-17.12.0.245-x86_64.AppImage: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/.mount_klogg-8vVRBN/usr/bin/../lib/libQt5Core.so.5)
./klogg-17.12.0.245-x86_64.AppImage: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /tmp/.mount_klogg-8vVRBN/usr/bin/../lib/libQt5Core.so.5)
./klogg-17.12.0.245-x86_64.AppImage: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/.mount_klogg-8vVRBN/usr/bin/../lib/libpng12.so.0)
./klogg-17.12.0.245-x86_64.AppImage: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/.mount_klogg-8vVRBN/usr/bin/../lib/libicui18n.so.52)
./klogg-17.12.0.245-x86_64.AppImage: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/.mount_klogg-8vVRBN/usr/bin/../lib/libicuuc.so.52)
```

I'm also trying building from source but without luck:
```
[ 93%] Generating ../../generated/documentation.html
../../output/maddy: ... libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ../../output/maddy)
gmake[2]: *** [generated/documentation.html] Error 1
gmake[1]: *** [src/app/CMakeFiles/klogg.dir/all] Error 2
gmake: *** [all] Error 2
```

Is there a workaround to build klogg on there platforms?
Thank you.

**Comment by variar** [comment]
Looks like https://github.com/AppImageCrafters/appimage-builder/ can do the trick. It claims to be able to produce self-contained AppImage packages. I'll look into it.

**Comment by owlfox** [comment]
Feel free to let me know if anything I could help. I have access a few in-house RHEL5,6ish machines to do the build or test.

**Comment by variar** [comment]
I'm currently on vacation. Might look at this issue next week. 

Appimage builder requires some python modules that makes build scripts complicated. 

Supporting old compilers to build klogg from source in RHEL5/6 is not an option. That would limit future development.

**Comment by variar** [comment]
@owlfox could you try appimage from https://github.com/variar/klogg/suites/1162110038/artifacts/16852250? It is made using Appimage builder, and according to docs it should be self-contained.

**Comment by owlfox** [comment]
Hi @variar ,
Thanks for the latest build with appimage, it looks like I'm on a platform too old to run appImage 😂.
Red Hat Enterprise Linux Workstation release 6.5 (Santiago)
```
./klogg-latest-x86_64.AppImage
fuse: warning: library too old, some operations may not work
FATAL: kernel too old
```

**Comment by variar** [comment]
Thanks, that is some progress. Appimage was built in Ubuntu 18.04 with glibc 2.27 which requires kernel 3.2. I'll try to build it in Ubuntu 16.04. It has glibc 2.23 that should work with 2.6.32 kernel.

**Comment by variar** [comment]
@owlfox could you try new appimage https://github.com/variar/klogg/suites/1185595424/artifacts/17388336. Klogg does not run, but it fails after all shared libraries has been resolved with some strange shared-memory error:
```
SingleApplication: Unable to attach to shared memory block.
"QSharedMemory::attach (shmget): permission denied"
```

If this appimage runs on rhel 6.5 up to shared memory error, I'll try to figure out what to do next

**Comment by owlfox** [comment]
Hi @variar ,
Thanks for the reply and the new image, now it looks better(not fatal) as the new messages shown below:
```
fuse: warning: library too old, some operations may not work
/tmp/.mount_klogg-lOxdHv/opt/klogg/bin/klogg: error while loading shared libraries: libQt5Widgets.so.5: cannot open shared object file: No such file or directory
```

**Comment by variar** [comment]
I'm sorry but I will not be able to provide support for old distributions. Klogg is moving forward. PRs are welcome, however they need to be crafted in such a way that builds on recent distributions may use standard C++17 features.

**Comment by owlfox** [comment]
Got it, thank you on reviewing this issue :).
