### ISSUE TITLE
Ubuntu 20.02 dependency problems libqt5widgets5

### ISSUE THREAD

**Issue by benreaves** [variar/klogg#202]
I'm migrating from ubuntu 18.04LTS to 20.04LTS and unable to install glogg on it. On AWS.
```
Preparing to unpack klogg-20.7.0-r650-Linux.deb ...
Unpacking klogg (20.7.0-r650) ...
dpkg: dependency problems prevent configuration of klogg:
 klogg depends on libqt5widgets5 (>= 5.9.5); however:
  Package libqt5widgets5 is not installed.
 klogg depends on libqt5concurrent5 (>= 5.9.5); however:
  Package libqt5concurrent5 is not installed.
 klogg depends on libqt5xml5 (>= 5.9.5); however:
  Package libqt5xml5 is not installed.
```
try installing the first of those dependencies:
```
Package libqt5widgets5 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libqt5widgets5' has no installation candidate
```

I've gotten lost in the dependencies here... Getting a similar problem when running spyder and qt5 seems to be the problem. Any idea on installing qt5 on Ubuntu 20.04 on intel 64bit?
sudo apt install qt5-default also fails

**Comment by benreaves** [comment]
qt5 seems to be the problem. Any idea on installing qt5 on Ubuntu 20.04 on intel 64bit?

**Comment by variar** [comment]
Hi, looks like libqt5widgets5 should be in universe repository https://www.ubuntuupdates.org/package/core/focal/universe/base/libqt5widgets5

**Comment by benreaves** [comment]
I tried again today, I still get the error
`klogg depends on libqt5widgets5 (>= 5.9.5)`

and if you try installing that you get an error about a broken install
So this sequence of 3 commands works:
```
sudo apt --fix-broken install  # takes a while, lots of output
sudo apt install libqt5widgets5 libqt5xml5
sudo dpkg -i klogg-20.9.0-r672-Linux.deb
```

**Comment by variar** [comment]
On fresh ubuntu docker containter this works as exptected installing all dependencies
```
docker run -ti --rm -v "$(pwd)":/usr/local ubuntu:focal /bin/bash
(inside container)
apt-get update
apt install /usr/local/packages/klogg-20.9.0-r0-Linux.deb
```
