### ISSUE TITLE
New Highlighters

### ISSUE THREAD

**Issue by xhargh** [variar/klogg#207]
I assume it has its perks testing the bleeding edge, maybe this isn't finished yet ;-)
I ran git hash c7778fd0b616823510b401c80468de90b5ae673a in Linux and I noticed a few things regarding the new highlighters.

1. HighligherSetCollection's currentSet is set to "". Which means that if you clear out your current settings (~/.config/klogg/klogg.conf in Linux) you will not get the highlighter to work (or at least, I didn't). When I upgrading an old config, it worked, and when I manually edited klogg.conf and put the guid in the correct place in the config file it worked.

2. I was not able to change which Highlighter set to use in the new dialog

3. Using up/down arrow buttons in the Highlighter dialog overwrites available sets if you have more than one.

Btw, thanks for doing a really great job keeping glogg up to date, I've been using glogg for years and just recently found klogg when I added some features in a fork of my own.

**Comment by xhargh** [comment]
Very strange, now 3 works also. Cannot explain why I saw the issue I described. Sorry about disturbing you about this!

**Comment by variar** [comment]
The more people test bleeding edge builds the better. My daily use cases unfortunately do not cover all scenarios. 

Context menu for highlighter might be hard to find. I'll think about some more visible place to show current active set.
