### ISSUE TITLE
#settings #defaults #win Scrolling\selecting text is very slow when config file is empty

### ISSUE THREAD

**Issue by wizzard0** [variar/klogg#208]
STR: 
- set windows DPI scaling to 150%
- download 20.4 or 20.9.0.666 x64 portable
- delete klogg.conf
- open any file
- try to select or scroll, observe pixelated text and ~0.3 seconds for each window repaint

workaround:
- open Tools>Options
- don't change anything, press OK
- observe everything works fine now (even without app restart)

Otherwise, thanks for an impressive app! 
Did a similar one myself so I know how many subtle issues you have to deal with %)

**Comment by variar** [comment]
@wizzard0 could you reproduce the issue with latest nightly builds?
