### ISSUE TITLE
#latest (20.9.0.666) new highlighters don't work, only old

### ISSUE THREAD

**Issue by wizzard0** [variar/klogg#209]
20.9.0.666

probably just an unfinished feature, but highlighters configured in new options UI don't work at all, while highlighters configured with 20.4 continue to work :)

**Comment by variar** [comment]
Thanks for the feedback! Could you export you current highlighters configuration and attach it to this issue along with some sample text file? And could you double-check that active highlighters set is selected via context menu in log area?
