### ISSUE TITLE
Chocolatey version is outdated

### ISSUE THREAD

**Issue by bgr** [variar/klogg#212]
Latest version on [Chocolatey ](https://chocolatey.org/packages/klogg) is still v19.9

**Comment by variar** [comment]
Thanks for mentioning it. Next release should be 20.10 in a couple of weeks, so I intend to skip 20.4 on Chocolatey.

**Comment by variar** [comment]
Chocolatey moderators are not very fast to respond to package updates. Seems like 20.12 package will be approved in a week or two.

**Comment by variar** [comment]
If someone would like to test new choco package here is direct link to latest version https://chocolatey.org/packages/klogg/20.12.0.813

**Comment by variar** [comment]
20.12 version is available now
