### ISSUE TITLE
Mark release by CI as alpha

### ISSUE THREAD

**Issue by Mte90** [variar/klogg#215]
I am using a browser extension that notify me about everything I am following on github, it is possible to mark a release in github as pre-release so it is marked not as new stable.

This will help me tracking better when there is a new release for this project.

In my projects I did also a unique release for pre-release with assets of the 3 OS to avoid 3 different releases, if can be an idea useful.

**Comment by variar** [comment]
Thanks for point this out. I've fixed scripts for Travis. Next linux/osx CI builds should be marked as pre-release. Windows builds are already marked as pre-release.
