### ISSUE TITLE
Skipping search box auto-complete

### ISSUE THREAD

**Issue by mpela81** [variar/klogg#218]
Details for the issue
--------------------

#### What did you do?
Type in the search box a word which is the same as a previously entered search, except case
For example:
- search "Products" (in match-case mode)
- realize that you wanted to search "products" (lowercase)
- type "products"

![image](https://user-images.githubusercontent.com/1140981/95436110-c2cbbe00-0953-11eb-8b63-fb793ef5f983.png)

#### What did you expect to see?
Search is made using the newly entered word

#### What did you see instead?
Search is made using the previously cached word

It also happens if you explicitly dismiss the auto-complete box with Esc key

Useful extra information
-------------------------
> Klogg version 20.4.0.589 (built on 2020-04-26 from commit 80a659e) [built for i386-little_endian-ilp32]
> running on Windows 10 Version 2004 (winnt/10.0.19041) [x86_64]
> and Qt 5.14.1

**Comment by variar** [comment]
Hi, thanks for feedback. Should be fixed in recent dev builds.  
@mpela81 could you try one of those?

**Comment by mpela81** [comment]
Hi, thanks. Looks good in latest continuous build, look forward to seeing it into a stable release!
