### ISSUE TITLE
20.10.0.787 install - "MSVCP140_1.dll is missing from your computer"

### ISSUE THREAD

**Issue by gbisaga** [variar/klogg#222]
I just downloaded the latest bleeding edge version klogg-20.10.0.787-x64-setup.exe, because I really want the import/export highlighting feature. Unfortunately, it won't install on one of my machines, says there's a missing DLL MSVCP140_1.dll. I installed it over top of the existing 20.4, which works fine.

**Comment by variar** [comment]
Thanks. Might be caused by last commit with memory reporting api usage. Will look into it today

**Comment by gbisaga** [comment]
I should have mentioned this is running under Windows Server 2016 Data Center. And it installs fine on another VM that has (as far far I know) the same configuration.

**Comment by variar** [comment]
Added MSVCP140_1.dll to installer as well as portable package. However, github actions seem unstable now, can't create new release right now.

**Comment by variar** [comment]
20.10.0.792 should come with MSVCP140_1.dll. @gbisaga could you try x86 and x64 builds on the machine than had this issue?

**Comment by gbisaga** [comment]
It worked! And I tried the highlighters import and it worked great. Thanks!
