### ISSUE TITLE
Allow to build without sentry

### ISSUE THREAD

**Issue by variar** [variar/klogg#226]
Another question, I would like to use this nix package to install klogg on macOS as well, but I didn't managed to build sentry on macOS, it's a bit tricky and requires patching here and there. Is there any simple way to build klogg without sentry? It would be great to have such option, as far as sentry is not required for main functionality.

_Originally posted by @sikmir in https://github.com/variar/klogg/issues/204#issuecomment-717485039_

**Comment by variar** [comment]
@sikmir I've added an option to main CMakeLists.txt to allow builds without Sentry. Try defining `KLOGG_USE_SENTRY:OFF`

**Comment by sikmir** [comment]
Thanks, build with `-DKLOGG_USE_SENTRY:BOOL=OFF` flag works for me.
