### ISSUE TITLE
Highlighting makes display wonky

### ISSUE THREAD

**Issue by gbisaga** [variar/klogg#229]
Windows Datacenter 2016, running latest (20.10.0.800) version. When I highlight in the top window, *sometimes* (not always) part of the line goes blank and the highlighting is offset. Here is a screenshot.

![image](https://user-images.githubusercontent.com/5503641/98879771-235e8700-243b-11eb-9de4-58dfd949b7ef.png)

Note that the highlighted line looks like the others, when it's not highlighted. When I highlight the whole line by clicking on it, it's fine, and the problem fixes itself when I highlight somewhere else. I see what's happening - there's no text missing, just a bunch of empty space being inserted both BEFORE the highlighted section, and WITHIN the end of the highlighted section. You can see the actual text on the highlighted line goes up to (from left) "efau" then "ltSecurityFilterChain -" and finally "Creating filter chain..."

It happens in both the top and bottom view windows. I'm pretty sure I never saw it happen until I recently upgraded to the latest nightly, not in the previous 20.10 pre-releases.

**Comment by variar** [comment]
@gbisaga this looks like one more case when tab-expansion gets in the way of selection highlight. Could you share log file with the line that causes this issue (just that one line should be enough)? I'll try to fix it while waiting for Qt 5.15.2 with drag&drop fixes on Mac.

**Comment by gbisaga** [comment]
I'm not sure what log file you mean. If you mean the log file I'm viewing with klogg, as far as I can tell, _any_ text in either pane has the same problem. I just created a small file (bogus.log) with two lines:

Hello there this is a test line. Hello there this is a test line. Hello there this is a test line. Hello there this is a test line. 
Hello there this is a test line. Hello there this is a test line. Hello there this is a test line. Hello there this is a test line. 

And it demonstrates the same problem.

**Comment by gbisaga** [comment]
Also, I don't know if this might possibly be related (so putting in same bug for now), but it is now cutting off lines in the display, at least sometimes. The line is all there if I highlight it and copy, but the display is messed up.

![image](https://user-images.githubusercontent.com/5503641/99001903-9c2c1480-2509-11eb-8557-ef65c2d459f1.png)

The weird thing is, it's not cutting off at the same place every time. A sampling of 5 cut-off lines shows the display cut off after 212, 215, 216, and 250 characters.

**Comment by gbisaga** [comment]
One more possible clue (sorry to spam you)... it also does the original problem when I use the control-F search feature:

![image](https://user-images.githubusercontent.com/5503641/99002582-a3075700-250a-11eb-851f-ad0c482035b3.png)

**Comment by variar** [comment]
I've unified all code for different kinds of highlight some time ago. This includes highlighters, selection and quickfind. So the bug must be the same. I was able to reproduce in on windows, but it is not reproduced in my linux environment.

**Comment by variar** [comment]
This seems to be a default font size issue. As soon as font is switched to anything using configuration dialog, highlight works great again.

**Comment by variar** [comment]
@gbisaga I've added DejaVu Sans Mono to klogg installer. That way default font exists after installation. Should be ok in 20.11.0.803

**Comment by gbisaga** [comment]
I tried to install the latest. Tried on both Windows 10 and 2016 Datacenter, with same results:

![image](https://user-images.githubusercontent.com/5503641/99255093-62952b00-27e1-11eb-9faf-a3b55d1f0088.png)

**Comment by gbisaga** [comment]
Much better! (Also IMO the font looks better than the one in 800.) Problem seems to be fixed, including the long line cutoff problem. Thanks!
