### ISSUE TITLE
[Feature request] Add Word wrap

### ISSUE THREAD

**Issue by Briy09** [variar/klogg#231]
add "View,Word wrap option" on the menu. Thereafter, all the lines will be wrapped so they fit within the window.
refer: https://windowsreport.com/notepad-line-wrap/

**Comment by variar** [comment]
Thanks for your feedback. This feature has been requested several times. However, implementing it is very difficult and requires major refactoring of text drawing code. Right now I don't have courage to dive into that.

**Comment by Edger** [comment]
> Thanks for your feedback. This feature has been requested several times. However, implementing it is very difficult and requires major refactoring of text drawing code. Right now I don't have courage to dive into that.

Hope that it will be refactored some day in the future, because it is a little inconvenient to read logs with long lines.

**Comment by variar** [comment]
More ideas in #99
