### ISSUE TITLE
Crash on saving log lines to file

### ISSUE THREAD

**Issue by aokulovich** [variar/klogg#234]
Details for the issue
--------------------
1. Select lines in the upper window
2. Using context menu click "Save to file"
3. In the "filemanager" window type the new file name
4. Click "Save"
5. klogg crashed
p.s. It also crashes if I select the existing file and click "Replace"
-------------------------
Crash id
aff780d4-9808-4e50-ab58-ee3266977b26
-------------------------
Useful extra information
-------------------------
> Klogg version 20.12.0.810 (built from commit f473845) [built for x86_64-little_endian-lp64]
> running on Debian GNU/Linux bullseye/sid (linux/5.9.0-4-amd64) [x86_64]
> and Qt 5.12.5

**Comment by variar** [comment]
Thanks! There was a race condition that never triggered on my system. Introduced a year ago, but since there were no easy way to report the crash it has never been mentioned. Should be fixed in 20.12.0.811. I'll have to update 20.12 release binaries once again.

**Comment by aokulovich** [comment]
Great news! Thank you!

**Comment by variar** [comment]
Release updated. Should be fixed

**Comment by aokulovich** [comment]
@variar I've tried the version Built 2020-12-23 from 5adb299. It doesn't crash any more, but the saved file doesn't appear in the filesystem. If I replace some other file, klogg doesn't overwrite it.
Do I need to create another issue?

**Comment by variar** [comment]
My bad. Tested with the same file and did not notice that it is not updating. Should be ok in 20.12.0.813.

**Comment by aokulovich** [comment]
Looks like in version Built 2020-12-24 from 576b91d it saves the whole file instead of selected lines. Is this behaviour expected?

**Comment by variar** [comment]
Yes, it was created to save search results to separate file

**Comment by variar** [comment]
I've created new issue to add saving for selection
