### ISSUE TITLE
Add option to save only selected lines to file

### ISSUE THREAD

**Issue by variar** [variar/klogg#236]
As mentioned by @aokulovich in https://github.com/variar/klogg/issues/234#issuecomment-750871104_

> Looks like in version Built 2020-12-24 from 576b91d it saves the whole file instead of selected lines. Is this behaviour expected?

**Comment by variar** [comment]
Currently klogg is saving the content of either file view or filtered view. So for your usecase it should be possible to fiter the file using some regex and save filtered results to a separate file using the context menu in the buttom view.

**Comment by eyaler** [comment]
my use case can be selecting a 10MB block of text so I guess the easiest way would be by line numbers

**Comment by variar** [comment]
Should be in 23.06 builds
