### ISSUE TITLE
Installation package for Windows self-signed - fails Windows Defender checks

### ISSUE THREAD

**Issue by Lim-Dul** [variar/klogg#238]
**Preconditions**
The system is configured with Windows Defender SmartScreen turned on (Reputation-based protection for Apps is on).
In this case the system is centrally managed and the settings cannot be changed.

**Observed Result**
Upon running the Installer (in this case klogg-20.12.0.813-x64-setup.exe) a pop-up appears with an error that the app is unrecognized (unknown publisher) and installation does not continue.
![image](https://user-images.githubusercontent.com/428324/103905788-5487ca80-50ff-11eb-8287-b14b1d282eb9.png)

**Expected Result**
The Installer is correctly signed and can be run with Windows Defender SmartScreen reputation-based app control turned on.

**Notes**
The installer is self-signed and I believe this to be the problem. For this problem to disappear a certificate by a trusted certification authority would have to be used.
![image](https://user-images.githubusercontent.com/428324/103906264-f90a0c80-50ff-11eb-8faf-7aec6dc5dabd.png)

**Comment by variar** [comment]
Acquiring proper code signing certificate for Windows platform is quite complicated for individual developer in Russia. Most resellers ask for some kind of business entity. I tried to use certificate from Certum, but signing process requires access to windows machine and can't be automated. 

Unless there is an easy and not too expensive way to do code signing (like Let's Encrypt for https for example) I am not going to address this issue.

**Comment by Lim-Dul** [comment]
> Acquiring proper code signing certificate for Windows platform is quite complicated for individual developer in Russia. Most resellers ask for some kind of business entity. I tried to use certificate from Certum, but signing process requires access to windows machine and can't be automated.
> 
> Unless there is an easy and not too expensive way to do code signing (like Let's Encrypt for https for example) I am not going to address this issue.

Didn't realize that. The Chocolatey Installer for 19.9 works fine despite Windows Defender and probably no signature. Does it use a different installer and/or was repackaged by the maintainer? Do you know who manages the package over there? I tried contacting them to upgrade the package but received no reply.

**Comment by variar** [comment]
The only difference is that 19.9 version package was not signed at all. However, that blue screen is based on file reputation. Looks like 19.9 was installed enough times to stop that annoying warning. 

Chocolatey package is just downloading installer from Bintray and launching it in silent mode. 

I've received your message. It looked like sent from chocolatey site, but I couldn't find any reply button there. And as I was planning to release 20.12 package next week, I decided that this could be a 'reply'. Sorry that got delayed for another two weeks.

**Comment by Lim-Dul** [comment]
Ha, didn't look or realize that you were the maintainer on chocolatey as well since I didn't remember the nickname.
The maintainer-contact-function over there is a bit basic, it seems, unless you post in the comments section I guess.
Thanks for updating the chocolatey repo. I have no idea why but my system let me install the package from over there with no problem at all. I wonder if it's because chocolatey spawns the installation process and chocolatey itself is trusted or something.
Won't hazard a guess of how the whole Windows Defender SmartScreen system is working.

As a final workaround/solution:
If anyone else is having the problem I have - and mind you, I cannot choose to ignore the warning since the override is disabled as well - you can just get the latest version from chocolatey.

**Comment by variar** [comment]
I've accuired a proper certificate from Centrum and setup codesigning. Should be ok in dev builds 21.12.0.1189. This will not disable smart screen completly until a package gets more reputation (which is unlikely for dev builds). but at least now the package is from "verified publisher". 

Uninstaller signing is still missing, but should be relatively easy to add.

**Comment by variar** [comment]
Added uninstaller signing. Should be good for now
