### ISSUE TITLE
Suggestion: Substring highlighting in search

### ISSUE THREAD

**Issue by Lim-Dul** [variar/klogg#240]
In another issues porting some features from Chipmunk was mentioned.
Although this related to more advanced stuff, when I looked at Chipmunk I noticed one quick UI improvement that will probably be easy to implement in Klogg:
Substring highlighting.

Basically when you search for a string it would be nice if not only the lines were highlighted, but if the precise match you searched for was displayed with some form of highlight (bold, different font color, different font background). A bonus would be if this highlight was configurable.

What would make browsing the file easier as well would be if the whole line where a match is was highlighted in addition to the small dots on the side that are easy to overlook if not simply jumping between results with keyboard shortcuts.

Reference Screenshot from Chipmunk:
![image](https://user-images.githubusercontent.com/428324/104361083-47f5de80-5512-11eb-90ee-4786554a58e0.png)

**Comment by variar** [comment]
Great idea. Should be easy based on current code for partial highlighters.

**Comment by Lim-Dul** [comment]
Update: I just noticed something. When using Ctrl+F Option the Substrings are highlighted yellow; just not when using the main Search dialog in the bottom half of the window.
That means the code should be even easier to duplicate / integrate.

**Comment by variar** [comment]
Can be tested in 21.05.0.1016. Matches highlight can be enabled in general options.

**Comment by Lim-Dul** [comment]
Test on Windows 10 20H2, Klogg 21.05.0.1018, successful.

Substrings are highlighted correctly:

![image](https://user-images.githubusercontent.com/428324/120173431-4f3d3080-c204-11eb-9197-ca66acbdfd69.png)
