### ISSUE TITLE
[FR]: set start and end of selection

### ISSUE THREAD

**Issue by PetbkA** [variar/klogg#242]
Let's say I have matches on lines 10 000 and 20 000 and I need to select everything between this lines.

The easiest way to do this is similar to Notepad++:
1. Jump to first match from search results and set selection start;
2. Jump to last match and set selection end;
3. Copy the selection.

But I can't see such functionality in klogg, so the only option is to select first match and scroll to last one to make a selection via Shift button.

Is it possible to implement it?

**Comment by variar** [comment]
Thanks, that should be easy to implement

**Comment by variar** [comment]
Add a context menu for this. Should be in 21.04.0.853

**Comment by PetbkA** [comment]
**21.04.0.856-x64** - works like charm, but there's UI problem: I have to _select_ the line with left mouse button or keyboard before setting line start/end, i.e. if I click the _right_ mouse button on the line that's _not_ selected, start/end will still be set on the line that's selected, not on the line that I've clicked with RMB

**Comment by variar** [comment]
Good catch. Should be fixed in >= 21.4.0.864. Selection start/end as well as search start/end should track position of context menu.

**Comment by PetbkA** [comment]
**21.04.0.876-x64** - fixed concerning this issue. Although it would be nice if right mouse button would also select the line, 'cause the other options in the RMB menu still work like in **856** build
