### ISSUE TITLE
Improvements for predefined filters

### ISSUE THREAD

**Issue by variar** [variar/klogg#243]
Some ideas

- [x] Add import/export in predefined filters dialog
- [x] Add context menu to search input to create predefined filter
- [x] Add buttons to move filters up and down in predefined filters dialog (as in highlighters)
- [x] Allow to set individual patterns to "fixed string" mode

**Comment by twardakm** [comment]
Hi @variar , I like the ideas you mentioned and I want to contribute to this feature because I heavily use it at work. For now I'll start with:

- [ ]   Add import/export in predefined filters dialog.

Cheers!

**Comment by variar** [comment]
Thanks, @twardakm! Improving my daily work scenarios is exactly how I got involved in glogg development. Unfortunately @nickbnf has been inactive for a long time, so no klogg features can be merged upstream.

**Comment by twardakm** [comment]
@variar I have one question in context of predefined feature. Is there any particular reason why you refactored collection type to:
```c++
using Collection = std::unordered_map<QString, QString>;
```
`unordered_map` tends to be unordered and it drives me crazy, because I don't have alphabetical order of my filters, which would be preferred way for me.

Thanks!

**Comment by variar** [comment]
@twardakm my bad, I've overlooked ordering issue.  For highlighters manual ordering is important, but for these filters alphabetical should be completely fine. Should be changed to std::map :)

**Comment by variar** [comment]
Fixed unorderd_map in 0974b5787acfd01aa12f0b1a5937fd8527e54075

**Comment by redfellow** [comment]
I like the idea of predefined filters, but it would be nice if we had something that's the opposite. So basically, show everything except lines matching filtered value. Perhaps a checkbox to invert a rule?

**Comment by variar** [comment]
@redfellow inverse checkbox can be helpful. Right now there is no support for such "inverted" filters in klogg internals. I hope to implement it in next release.

**Comment by xaljer** [comment]
predefined filters is a cool feature! I think the simple version of this is the `-f` option of grep, which can specify patterns in text files.
And i think it's would be better if klogg can also support use a file as predefined filter. Using files as predefined filter could split user data from klogg configuration and compatible with the workflow of grep like tools. Single file is also easy to share.

I know it's quite same with the import/export feature by klogg conf file. But the simple file format of grep can be more general and compatible with different workflow, without depend klogg, and klogg own conf file is suite to support more complex options like specify if case sensitive for every pattern.

**Comment by twardakm** [comment]
Hi @xaljer , your idea seems interesting, it would also fit my workflow, but I want to make sure we understand it the same way.

How I would see such feature is to add an option to specify **directory** in which there is a number of files, each file specifies **one filter**, where name of the file is filter name, and content is filter content.

In terms of practical implementation, I think it would be best to implement something similar to Highlighters sets - so you can specify multiple sets of filters, e.g. one set of filters per project you are working on, and for every set you can **either** add filters manually **or** specify directory with grep-like pattern files.

Let's wait for @variar opinion, but I like it very much, and would be eager to help with implementation.

**Comment by xaljer** [comment]
Hi @twardakm , yes, we got the same idea here. But I think can talk more about details.

I think may be we can simplify concepts. We could just say "filter". A filter can be specified by inputting a regex in klogg manually, or specified by a file (could be in any directory).

“specify directory", you said, I think we can understand it as multi-selection of files under a directory, but there is no limitation that files under different directories.
And sorry I am not quit understand you said about "sets of filters". I think klogg could just show predefined filters like currently, and user select one or more of them. If one project use two files, just pick those two filters. I am just worry about group filters may make UI complex.

**Comment by twardakm** [comment]
@xaljer , your idea about specifying file per filter makes more sense that mine :)

I will start implementing it once I have some time!

**Comment by variar** [comment]
> I like the idea of predefined filters, but it would be nice if we had something that's the opposite. So basically, show everything except lines matching filtered value. Perhaps a checkbox to invert a rule?

@redfellow Button to invert match rule is now available in builds >= 21.04.0.886

**Comment by variar** [comment]
Moved ideas about filter patterns in files to separte issue
