### ISSUE TITLE
Goto Command Ignores '0' Digit

### ISSUE THREAD

**Issue by Lim-Dul** [variar/klogg#244]
**Preconditions**
File with more than 10 lines, klogg 20.12.0.813.
Tested on Windows 10 Pro 20H2, not sure if this is OS-specific.

**Observed Result**
When typing in line numbers greater than 9 and containing the digit '0' in them, all '0' digits are ignored after using the Goto-Command (g - shortcut). E.g. 230 becomes 23, so does 203 or 2300 or 2003 etc.

**Expected Result**
The Goto-Command selects the correct lines when typing in numbers containing '0' digits.

**Notes**
Initial suspicions that it was something to do with my keyboard layout, Windows or perhaps NumPad / Function locks were not confirmed. I checked the same functionality and files in glogg and in that application the correct lines are selected.

**Comment by variar** [comment]
Should be fixed in 21.04.0.891

**Comment by Lim-Dul** [comment]
Retest successful on Windows 10 Pro 20H2 Build 19042.928.
