### ISSUE TITLE
Mouse side scroll disabled when "follow file" enabled

### ISSUE THREAD

**Issue by jgscherber** [variar/klogg#247]
STR
1. Enable "follow file"
2. Try to use side-scroll on a mouse (i.e. moving the scroll-wheel to the left and right)

ER: File stays locked to bottom and scrolls left and right
AR: Nothing happens

**Comment by variar** [comment]
Hi, thank. I've never used side-scroll feature. I can reproduce the issue and will try to fix it

**Comment by alvlapo** [comment]
Hi @jgscherber , what version of the klogg are you using, and on what system? I tried it on linux (Mint) on version 20.12.0.813, and mouse bottom side scroll works correctly, when follow file enabled.

**Comment by variar** [comment]
Should be fixed in 21.04.0.903
