### ISSUE TITLE
Horizontal scroll when scrolling while holding shift key

### ISSUE THREAD

**Issue by impegoraro** [variar/klogg#250]
It would be a nice addition if we can scroll horizontally without moving the cursor from the position we are in, most IDE and text editors allow to scroll horizontally by holding the shift key when scrolling. It would be a nice addition

**Comment by chuv1** [comment]
You can scroll horizontally by holding ALT key or scroll faster vertically by holding SHIFT.

**Comment by jeffjensen** [comment]
> You can scroll horizontally by holding ALT key or scroll faster vertically by holding SHIFT.

This is great info I didn't know! (thank you for posting!)

Great to add this to the Help -> Documentation (perhaps a new "Mouse Navigation" section below the "Keyboard commands" section?).  I've made a note to do so but someone will probably do so before I get to it.

**Comment by impegoraro** [comment]
Thanks a lot for the feedback @chuv1.

**Comment by dblachut-adb** [comment]
> You can scroll horizontally by holding ALT key or scroll faster vertically by holding SHIFT.

This should be opposite I think as typically you hols shift for horizontal scroll. Maybe it should be configurable?
