### ISSUE TITLE
White space on left side of window, Windows 10, display scaling, 2nd monitor

### ISSUE THREAD

**Issue by chadgeidel** [variar/klogg#252]
**Note: this is extremely low priority and cosmetic only. I only raise this bug for informational awareness.**

1. What version of Klogg are you using (version is listed in window title and about dialog)?
  I'm using klogg19.9.0.467
2. What operating system are you using?
  Windows 10 Enterprise x64 v1909 (OS build 18363.1139)
3. What did you do?
  I'm opening a log file on my secondary screen which is set to 125% display scaling. 
4. What did you expect to see?
  I expect the log text to be visible the entire width of the window (as it does with 100% or 150% display scaling)
5. What did you see instead?
  I see a vertical white area on the right which covers the text. I can still see all text by using the horizontal scrolling.

Additional notes: 
- I have multiple displays. I have an external monitor plugged into my laptop, and the external monitor is the primary monitor. **If I unplug my external monitor and just use the laptop display only this does not happen.** 
- If I leave Klogg open and adjust the display scaling, 125% works as expected. It only happens when launching a new klogg window.
- The width of the whitespace seems proportional to the width of the window. If I make the window narrower, the white space is narrower.
  
![Klogg-19 9 467-125percent](https://user-images.githubusercontent.com/76024363/108547138-566cae00-72a7-11eb-991e-0a806bb3da56.png)
![Klogg-19 9 467-150percent](https://user-images.githubusercontent.com/76024363/108547151-58cf0800-72a7-11eb-8d94-0a2db71fbbb0.png)
![Klogg-19 9 467-100percent](https://user-images.githubusercontent.com/76024363/108547153-58cf0800-72a7-11eb-87b2-8b622d347d64.png)

**Comment by variar** [comment]
Thanks! Although such bugs don't look very critical, but they can be very irritating. I don't have access to Windows-based system with two monitors at the moment. Some day we will return to office space, and I'll try to see into this issue.

**Comment by variar** [comment]
Could be fixed in dev builds for some time after redoing font measurements correctly.
