### ISSUE TITLE
klogg & encoding

### ISSUE THREAD

**Issue by Cherkah** [variar/klogg#263]
hi,
klogg display my systemd-journald logg this way:
`.... ü7( .T+ ....`
the encoding type is iso-8859-1
for other logg (utf8) there is no problem.

What should i install to read my journald logg via klogg?

**Comment by variar** [comment]
As far as I know journald log files are not text files. Do any simple tools like cat/less/grep work on them?

**Comment by Cherkah** [comment]
ok, i was thinking that klogg was able to read journald log as gnome-log or ksystemlog

thanks
