### ISSUE TITLE
The program crashes, when searching in files, it is greater than 2.5 GB

### ISSUE THREAD

**Issue by Tayeb-Ali** [variar/klogg#267]
Details for the issue
--------------------

#### What did you do?
I try search in big File size like 2.5 gb
some time i get result , and after that the program is auto close 

-------------------------
Crash id
88434f96-5132-4372-8b06-defb759261b1
-------------------------
Useful extra information
-------------------------
> Klogg version 21.04.0.841 (built from commit 4ff1166) [built for x86_64-little_endian-llp64]
> running on Windows 10 Version 2009 (winnt/10.0.21337) [x86_64]
> and Qt 5.15.2

**Comment by variar** [comment]
The same crash as in #268. Dump from there has better stack trace. Will keep #268 open.
