### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by alimagedayad** [variar/klogg#269]
Details for the issue
--------------------

#### What did you do?

-------------------------
Crash id
15beeb83-0f61-4992-bb64-e40b2286319a
-------------------------
Useful extra information
-------------------------
> Klogg version 21.04.0.841 (built from commit 4ff1166) [built for x86_64-little_endian-lp64]
> running on macOS 11.2 (darwin/20.3.0) [x86_64]
> and Qt 5.15.2

**Comment by variar** [comment]
Looks like #268. Should be fixed in 21.04.0.844
