### ISSUE TITLE
Allow to add highlight rules from selected text

### ISSUE THREAD

**Issue by variar** [variar/klogg#270]
That sounds pretty cool, but I'd like to add one more thing: some shortcuts support for this. Such as Ctrl + Shift + Num<1-9> to set a different color. For example, when you select a keyword or a word you want to remember, you can mark it red by Ctrl + Shift +1, and then if others keyword or a word you want to remember again, you can mark it yellow by Ctrl + Shift +2, etc. Of course , the right-click selection is also supported. Hope it can be adopted, thank you!

_Originally posted by @Junbo-Zheng in https://github.com/variar/klogg/issues/259#issuecomment-791889182_

**Comment by Junbo-Zheng** [comment]
Hi~Thank you very much for receiving your reply, and also thank you for treating it as a new feature. I want to continue to add that the "Ctrl + Shift + Num<1-9>" I mentioned is just a reference. What I want to express is to use different shortcut keys to support different color labels. I believe it is very convenient for most users, thanks again!

**Comment by xaljer** [comment]
As my most expectant feature, I'm just curious about is there some progress or plan on this?

**Comment by variar** [comment]
I've been experimenting with this. For now core part is ready but UI is lacking. There are three predefined color labels (red, green and cyan) and shortcuts to assign them (`Ctrl+Shift+1-3`). No context menu yet. And the only way to clear all labels is by using another shortcut `Ctrl+Shift+0`. I'll make this implementation available in next ci builds, so you can play with it.

Ideally there should be a color configuration dialog for labels and context menu to assign and remove them.

**Comment by Junbo-Zheng** [comment]
> I've been experimenting with this. For now core part is ready but UI is lacking. There are three predefined color labels (red, green and cyan) and shortcuts to assign them (`Ctrl+Shift+1-3`). No context menu yet. And the only way to clear all labels is by using another shortcut `Ctrl+Shift+0`. I'll make this implementation available in next ci builds, so you can play with it.
> 
> Ideally there should be a color configuration dialog for labels and context menu to assign and remove them.

So cool, that sounds great, I can’t wait to experience it!

**Comment by variar** [comment]
Can be tested in builds 21.06.0.1050+

**Comment by xaljer** [comment]
This is cool and super useful for me, thanks. 

I found that `Ctrl+Shift+0` is not work, but It's ok when I add another shortcut like `Ctrl+L` for it.

One more optimization, would you like to add the logic that when I press `Ctrl+Shift+1-3` on the same pattern, than clear the highlight on the single pattern. For now, I must clear all patterns when I just want change one of them.

**Comment by variar** [comment]
@xaljer thanks for the feedback. Clearing single pattern should be available in 21.07.0.1069

**Comment by xaljer** [comment]
Just list some further idea on this feature to track:
- [ ] configuration dialog to set predefined colors for labels.
- [ ] context menu to assign and remove them.
- [ ] A single shortcut to do `shift+ctrl+1/2/3` in turn automatically and corresponding context menu.
- [ ] Both background color and font color configurable which may helps when we use like ten colors.

**Comment by variar** [comment]
Added color configuration to current highlighters configuration dialog. Cycling shortcut is `Ctrl+D`. Context menu will require some more effort.

**Comment by xaljer** [comment]
Thanks a lot. A suggestion: cycling shortcut should have same behave as `shift+ctrl+1/2/3`, means when press `ctrl+D` on a colored pattern, it should clear current color but not change it to another color, so that when user don't care specified color, `ctrl+D` can replace `shift+ctrl+1/2/3`. similar function in vim/VSCode also do like this.

**Comment by variar** [comment]
Should be in 21.08.0.1112

**Comment by variar** [comment]
For some reasons colors do not show up in context menu on Windows. Should be like this
![image](https://user-images.githubusercontent.com/1620716/130435127-cb28b66f-5c49-4e9d-b91d-9a04296b9b18.png)

**Comment by xaljer** [comment]
I found that color label setting page is empty if highlighters is never configured. Is that a bug? color label and highlighters should be two separate features.
![image](https://user-images.githubusercontent.com/8309631/131205986-bbd0d21c-dfaa-481b-81d1-e2dd42a3e784.png)

**Comment by variar** [comment]
Yes, this is strange. Color labels are supposed to be reset to default if none are found in current configuration. I'll take a look.

**Comment by variar** [comment]
Fixed default initialization of color labels in 21.08.0.1154

**Comment by variar** [comment]
Fixed colors in menu for Windows in 21.09.0.1159

**Comment by xaljer** [comment]
One more suggestion: default colors can be improved. Some color is not so clear, such as:
![image](https://user-images.githubusercontent.com/8309631/132935684-a00f3a3c-1c58-4c17-8244-a56112637dc0.png)

Some theme from other software could be referenced.
![image](https://user-images.githubusercontent.com/8309631/132935472-3dbc69c2-8ae4-4b2b-8928-fbe97c9dad27.png)

**Comment by speeeeed** [comment]
This feature is pretty cool, now I can uninstall notepad++.

**Comment by xaljer** [comment]
One more suggestion: reset the color label cycle to first when clear all labels. This will make cycling behavior more definite.

**Comment by variar** [comment]
Better default colors are in 21.09.0.1165.

**Comment by variar** [comment]
I consider this finished for current milestone.

**Comment by xaljer** [comment]
> One more suggestion: reset the color label cycle to first when clear all labels. This will make cycling behavior more definite.

@variar would you like to also implement this?

**Comment by variar** [comment]
@xaljer sorry, missed that part. Should be in next builds.
