### ISSUE TITLE
i change encoding

### ISSUE THREAD

**Issue by AbdelhaQ-fullstack** [variar/klogg#277]
Details for the issue
--------------------

#### What did you do?

-------------------------
Crash id
cb648d83-3080-497d-ab86-9b6845dc4494
-------------------------
Useful extra information
-------------------------
> Klogg version 20.12.0.813 (built from commit 576b91d) [built for x86_64-little_endian-llp64]
> running on Windows 7 Version 6.1 (Build 7601: SP 1) (winnt/6.1.7601) [x86_64]
> and Qt 5.15.2

**Comment by variar** [comment]
Hi, thanks for reporting this. I've found a data race that could cause this crash. It has been fixed in recent development version. Could you try builds >= 20.04.0.856?

**Comment by AbdelhaQ-fullstack** [comment]
Yep he work fine now thank you  ^^
