### ISSUE TITLE
Moving to Hyperscan backend

### ISSUE THREAD

**Issue by variar** [variar/klogg#280]
[Hyperscan](https://hyperscan.io) regular expressions engine seems to be about 2 times faster than PCRE2 used in QRegularExpression. However, it does not support some advanced PCRE2 features, so keeping both engines is desirable.

- [x] Add experimental implementation and measure performance
- [x] Allow to select regular expressions backend in configuration
- [x] Allow to build klogg without hyperscan backend
- [x]  Update documentation

**Comment by variar** [comment]
Klogg 21.04.0.876 has experimental hyperscan backend active by default. Results looks promising. Tested searching through 1Gb file using 4 CPU cores.

QRegularExpression
```
Searching done, overall duration 3570.39 ms
Line reading took 814.359 ms
Results combining took 112.078 ms
Matching took 3311.02 ms
Matching took 3343.09 ms
Matching took 3289.59 ms
Matching took 3320.46 ms
Searching perf 2548970 lines/s
Searching io perf 251.642 MiB/s
```

Hyperscan
```
Searching done, overall duration 1804.83 ms
Line reading took 907.165 ms
Results combining took 49.838 ms
Matching took 1428.87 ms
Matching took 1398.59 ms
Matching took 1369.43 ms
Matching took 1404.81 ms
Searching perf 5042484 lines/s
Searching io perf 497.81 MiB/s
```

Indeed about 2 times more throughput.

**Comment by variar** [comment]
.Added cmake options and combobox in advanced settings. Need to update documentation.

**Comment by variar** [comment]
Implemented automatic fallback. No need for explicit documentation.

**Comment by xaljer** [comment]
Are there some differences in using between two engines?

**Comment by variar** [comment]
Hyperscan is a lot faster but supports less PCRE features. For example, lookahead is not implemented. Starting from build 21.04.0.910 Klogg checks whether provided pattern is valid for Hyperscan. If it is not valid, then Qt engine is used as a fallback. So there should not be any visible difference in klogg search behaviour except in many cases results may appear faster.

Right now Hyperscan engine us used only in main search. Quickfind and highlighters are using Qt engine. But that may change in future builds.
