### ISSUE TITLE
RIght mouse button doesn't select the line on which it has been clicked

### ISSUE THREAD

**Issue by PetbkA** [variar/klogg#281]
Following the recent fixes in #242. Clicking the line with the right mouse button should select this line, except when RMB is clicked on the selection itself.

For example, here's the behavior in Notepad++. You can see that the pointer moves to the point of RMB click, except when you're clicking on the selection:

https://user-images.githubusercontent.com/22843816/115135058-1b27fa80-a01e-11eb-8bf1-970f892da57e.mp4

And here's the video of klogg's behavior as of **21.04.0.876-x64:**

https://user-images.githubusercontent.com/22843816/115134955-77d6e580-a01d-11eb-9d9f-329d3be4bb66.mp4

Also I think that the RMB menu's option _Copy this line_ should be renamed to just _Copy_ 'cause it really copies several lines when they are selected

**Comment by variar** [comment]
Should be fixed in 21.04.0.891

**Comment by PetbkA** [comment]
**klogg-21.04.0.902-x64** - fixed. The behavior is the same as in NP++
