### ISSUE TITLE
[FR]: add an option "Enable following file on scrolling beyond the EOF"

### ISSUE THREAD

**Issue by PetbkA** [variar/klogg#283]
Didn't find such option in **21.04.0.876-x64**. The name for the options is quite cumbersome, although I don't know how to express it in a shorter way

**Comment by variar** [comment]
This is actually implemented already. 


https://user-images.githubusercontent.com/1620716/115136935-bd021400-a02b-11eb-9f9a-90d3e94b7cae.mp4

Do you need an option to disable this behaviour?

**Comment by PetbkA** [comment]
> Do you need an option to disable this behaviour?

Yep

**Comment by variar** [comment]
Done in 21.07.0.1069

**Comment by PetbkA** [comment]
**21.07.0.1069-x64** - option appeared in ``File`` section of Options. Works like a charm! Thank you! :)
![klogg_2021-07-26_10-00-41](https://user-images.githubusercontent.com/22843816/126946611-e33e649f-3bb8-4d2c-a9c9-0cc5875136a3.png)
