### ISSUE TITLE
Dark Mode is not working.

### ISSUE THREAD

**Issue by Rubio6321** [variar/klogg#292]
Details for the issue
--------------------
Just in my Options > View i can change the style to Dark Mode
Useful extra information
-------------------------
> Klogg version 21.04.0.881 (built on 2021-04-19 from commit 32238c8) [built for x86_64-little_endian-llp64]
> running on Windows 10 Version 2009 (winnt/10.0.19042) [x86_64]
> and Qt 5.15.2
![image](https://user-images.githubusercontent.com/79482953/116815721-1bb4ab00-ab5f-11eb-9af4-a727eeaa2f72.png)

**Comment by variar** [comment]
Have you restarted klogg? Applying new style without application restart lead to strange bugs

**Comment by variar** [comment]
Closing for now. Feel free to reopen with more information.
