### ISSUE TITLE
Typo in options

### ISSUE THREAD

**Issue by duke1995** [variar/klogg#295]
There's a typo in the "Options" dialog under the "Session options" section of the "General" tab: "**Enabe** multiple windows" should be "**Enable** multiple windows".

![klogg 2021-05-05 19-49-44](https://user-images.githubusercontent.com/4910210/117186927-a9043380-addb-11eb-82ff-74c385eec46e.png)

**Comment by variar** [comment]
Thanks!

**Comment by variar** [comment]
Should be ok in 21.05.0.919
