### ISSUE TITLE
Function for String Selection and Copy Between Line Number's in Seaching Box

### ISSUE THREAD

**Issue by jimmy123j** [variar/klogg#298]
For my job I need to search some target string in a file, and check the string data in part between target string
So I need to find target string position first and copy all string between target than check the string from the copy
Hope you can understand what I say, and sorry for bad English
Thanks for developement !!

btw, if this function could be supported, does possible to join the command line support for it
I'think it might be able to work with batch file for data searching automation

e.g.
![image](https://user-images.githubusercontent.com/46530155/117560369-d133b100-b0bf-11eb-859f-d61b03bc50c8.png)

**Comment by variar** [comment]
I think that this can be achieved using klogg built-in functionality that allows to limit matching to some region of opened file. I've attached a small demo:

https://user-images.githubusercontent.com/1620716/117567845-b0bb2500-b0c6-11eb-8261-0a186c22a609.mp4

**Comment by variar** [comment]
I'm not sure of command line interface for that feature. Maybe some existing command line tools like grep could be better for this kind of task

**Comment by jimmy123j** [comment]
Thanks for reply my post, your demo is good for me, and set search is what I need exactly
the last ver. I download not see the set selection function, btw

about the command line, I used the findstr and other language to achieve function what I want
casue every each file I search over 20GB+, so I need to split each target and order it for couple's data relation
base on compony PIP rules, It's hard to find the good tool to speed-up the data searching
now I use the file split + Batch + AutoIT lanaguage to do the searching, and speed almost limited
so if the klogg can support the line/range search, searchinging in range search and output, it'll more usedful for user
just my suggetion, not need to be serious

thanks for reply and solve my issue again, Thanks !!!

**Comment by variar** [comment]
>I download not see the set selection function, btw

Check latest [nightly builds](https://github.com/variar/klogg/releases/tag/continuous-win) Usually they are stable enough but I recommend keeping stable version around just in case.

**Comment by jimmy123j** [comment]
Thanks a lot, that set search and set selection will increase my/fellow's working efficiency
Both of 2 function is good for user for multi comdition searching
Thanks for develpment and patient, Thanks again !!!

**Comment by variar** [comment]
moved command line search to separate issue
