### ISSUE TITLE
Ragel state machine compiler not found: Please use external dependencies

### ISSUE THREAD

**Issue by yurivict** [variar/klogg#300]
The latest master fails:
```
CMake Error at 3rdparty/hyperscan/CMakeLists.txt:100 (message):
  Ragel state machine compiler not found
```
because there is a copy of the ```hyperscan``` project  in ```3rdparty/hyperscan```.

Could you please use external dependencies for ```hyperscan``` and for other packages?

If every project would bundle all its dependencies their compilation size would snowball and we would need to handle build issues of individual projects in many other places.

For example:
```
In file included from /disk-samsung/freebsd-ports/sysutils/klogg/work/klogg-1e8c20a/3rdparty/sentry/external/crashpad/third_party/mini_chromium/mini_chromium/base/compiler_specific.h:8:
/disk-samsung/freebsd-ports/sysutils/klogg/work/klogg-1e8c20a/3rdparty/sentry/external/crashpad/third_party/mini_chromium/mini_chromium/build/build_config.h:19:2: error: Please add support for your platform in build/build_config.h
#error Please add support for your platform in build/build_config.h
 ^
```
and
```
In file included from /disk-samsung/freebsd-ports/sysutils/klogg/work/klogg-1e8c20a/3rdparty/sentry/external/crashpad/minidump/minidump_annotation_writer.cc:15:
In file included from /disk-samsung/freebsd-ports/sysutils/klogg/work/klogg-1e8c20a/3rdparty/sentry/external/crashpad/minidump/minidump_annotation_writer.h:21:
In file included from /disk-samsung/freebsd-ports/sysutils/klogg/work/klogg-1e8c20a/3rdparty/sentry/external/crashpad/minidump/minidump_byte_array_writer.h:22:
In file included from /disk-samsung/freebsd-ports/sysutils/klogg/work/klogg-1e8c20a/3rdparty/sentry/external/crashpad/minidump/minidump_extensions.h:19:
In file included from /disk-samsung/freebsd-ports/sysutils/klogg/work/klogg-1e8c20a/3rdparty/sentry/external/crashpad/compat/non_win/dbghelp.h:21:
/disk-samsung/freebsd-ports/sysutils/klogg/work/klogg-1e8c20a/3rdparty/sentry/external/crashpad/compat/non_win/timezoneapi.h:30:9: error: no type named 'char16' in namespace 'base'
  base::char16 StandardName[32];
  ~~~~~~^
/disk-samsung/freebsd-ports/sysutils/klogg/work/klogg-1e8c20a/3rdparty/sentry/external/crashpad/compat/non_win/timezoneapi.h:48:9: error: no type named 'char16' in namespace 'base'
  base::char16 DaylightName[32];
  ~~~~~~^
```

**Comment by variar** [comment]
Rewriting cmake script to try find external dependencies is a right thing to do, but I don't have enough experience. Bundling libraries proves to be much easier. I've noticed that using external dependencies sometimes messes up CPack packaging (installing some headers/pkgconfig files that I do not want to distribute). 

PR's are always welcome. 

There is and option to build klogg without heavy dependencies:
* to turn off Sentry pass `-DKLOGG_USE_SENTRY=OFF` to cmake during configuration. Crashpad is optional and useless without uploading symbols to sentry.io.
* to turn off hyperscan pass `-DKLOGG_USE_HYPERSCAN=OFF`. Hyperscan regex engine is about 2x faster, but Qt built-in regex engine is perfectly fine.

**Comment by variar** [comment]
Would it help if klogg used some c++ package manager like conan or vcpkg?

**Comment by yurivict** [comment]
> Rewriting cmake script to try find external dependencies is a right thing to do, but I don't have enough experience. 

Usually ```find_package``` or ```pkg_check_modules``` is sufficient to find external packages.


> Would it help if klogg used some c++ package manager like conan or vcpkg?

It wouldn't help me because I am trying to update the FreeBSD port ```glogg``` to ```klogg``` and FreeBSD ports don't use C++ package managers, only cmake for cmake-based projects.

**Comment by variar** [comment]
@yurivict please try latest master. I've changed `3rdpart/CMakeLists.txt` to try find dependencies from system for hyperscan, tbb, xxhash and uchardet. It should fallback to bundled versions if system-wide packages are not found.

**Comment by variar** [comment]
Removed abseil dependency.  KF5Archive can now be used from build host if found. Remaining bundled external dependencies are rather small and I don't see them in my system's package manager.

**Comment by variar** [comment]
@yurivict any updates on this issue?
