### ISSUE TITLE
Prdefined Filter searching type and List control

### ISSUE THREAD

**Issue by jimmy123j** [variar/klogg#305]
Sorry for bother again, Predefined Filter is good function for me
I think List control (with searching type) as Highlight Option might good for Prdefined Filter to use
And default the Prdefined Filter searching type in Option for using | multiple searching

**List Control for Quick Searching**
![image](https://user-images.githubusercontent.com/46530155/117845203-ea508380-b2b2-11eb-9d0c-954fd13f6904.png)

**No searching type**
![image](https://user-images.githubusercontent.com/46530155/117846466-0c96d100-b2b4-11eb-8bd1-eb669ffa5174.png)

**Prdefined Filter searching type for | multiple searching**
![image](https://user-images.githubusercontent.com/46530155/117845980-9a25f100-b2b3-11eb-9cae-2db28d23ae31.png)

**Comment by variar** [comment]
Changing order of patterns as well as search mode for each pattern has been added. Could you check it out in latest builds?
