### ISSUE TITLE
Feature request: support to remove one or more pattern from search history

### ISSUE THREAD

**Issue by xaljer** [variar/klogg#309]
It looks like klogg manage search history using the ring buffer logic. Analyze log file is a process of trying, so sometimes I want to remove those useless pattern form search history, so that I can better reuse the search history.
Although predefined filter can store some pattern that often use, search history is a quickly way to store and reuse patterns. A button before every pattern which can remove this single item is helpful to maintain the history conveniently.

**Comment by variar** [comment]
Adding custom buttons inside combobox is rather difficult. A dialogue that can be called from context menu of search string input should be ok. It can have buttons to remove items from history as well as pin them, so they never get removed.

**Comment by variar** [comment]
I've added a simple history editor dialog in 21.07.0.1081
