### ISSUE TITLE
Consider tweaks form sergei-dyshel fork

### ISSUE THREAD

**Issue by variar** [variar/klogg#31]

**Comment by variar** [comment]
Consider merging some tweaks from @sergei-dyshel's fork https://github.com/safield/glogg

- [ ] https://github.com/sergei-dyshel/glogg/commit/92ca26acd55ff22394b79f8987c0cd8ea0a46308
- [ ] https://github.com/sergei-dyshel/glogg/commit/7848d9f34ccb3262327520f224d66f94de67cfbf
- [ ] https://github.com/sergei-dyshel/glogg/commit/7ff7031b37d9212de4053a511c0a06529f262b0b
- [ ] https://github.com/sergei-dyshel/glogg/commit/d2265407dcad1e3203e391dc9cd57607f5aa44d5

**Comment by sergei-dyshel** [comment]
The first commit in this list (copy to clipboard) is a tweak for my specific usecase and IMHO contradicts with concept of separated clipboard/selection on Unix. The rest 3 commits are part of search bar behavior rework, which needs a lot of finishing. Unfortunately I'm a little busy right now and won't be able to help you with this, so good luck with `klogg` 😉

**Comment by variar** [comment]
Thanks for clarification. Will do it some time later )
