### ISSUE TITLE
double click select word at underline boundary?

### ISSUE THREAD

**Issue by xaljer** [variar/klogg#310]
In newer version, using double click to select word is stop at underline boundary but not the word boundary. It's not convenient.

For `aaa_bbb_ccc`, I think double click should select the whole word of `aaa_bbbc_ccc`, but not the `aaa` or `bbb`.

**Comment by variar** [comment]
I've seen several text editors/IDEs that do the same for `_`, treating it as a word boundary.  Need some more research and opinions to decide which behaviour is most common.

**Comment by xaljer** [comment]
Older version has different behave.

**Comment by variar** [comment]
Should be implemented in next build.

**Comment by variar** [comment]
Landed in 21.05.0.988+

**Comment by xaljer** [comment]
test OK in 21.05.0.988.
