### ISSUE TITLE
Feature request: quick find: show result postion when typing

### ISSUE THREAD

**Issue by xaljer** [variar/klogg#312]
Just like 'incsearch' in vim:
> While typing a search command, show where the pattern, as it was typed
so far, matches.  The matched string is highlighted.  If the pattern is invalid
or not found, nothing is shown.

**Comment by variar** [comment]
It should work this way if incremental quickfind option is enabled in settings.
![image](https://user-images.githubusercontent.com/1620716/118354114-2e24e080-b572-11eb-970e-157ee77d8f67.png)


https://user-images.githubusercontent.com/1620716/118354167-6fb58b80-b572-11eb-98b5-2c1867fac4c0.mp4

**Comment by xaljer** [comment]
Cool, thanks~

**Comment by xaljer** [comment]
Why incremental quick find only support fixed strings but not regexp?

**Comment by variar** [comment]
That is inherited from glogg. In glogg quick find works in UI thread, so performing regex search makes UI freeze. Klogg performs quick find in a background thread, so in theory this limitation can be dropped. I'll give it a try.

**Comment by variar** [comment]
Looks like at least my development PC can handle regex and incremental quickfind just fine. Should be in next build

**Comment by variar** [comment]
Should be in 21.05.0.988+

**Comment by xaljer** [comment]
It works fine in 21.05.0.988. Thanks.
