### ISSUE TITLE
Crash when opening one or more files

### ISSUE THREAD

**Issue by undecomposed** [variar/klogg#318]
Details for the issue
--------------------

#### What did you do?
Opened a log file

-------------------------
Crash id
ccc1e18d-b8ef-4eb5-aefe-36b2797cb02d
-------------------------
Useful extra information
-------------------------
> Klogg version 20.12.0.813 (built from commit 576b91d) [built for x86_64-little_endian-llp64]
> running on Windows 10 Version 2009 (winnt/10.0.19043) [x86_64]
> and Qt 5.15.2

**Comment by variar** [comment]
Could you check if this crash is still happening it latest [dev-builds](https://github.com/variar/klogg/releases/tag/continuous-win)?

**Comment by variar** [comment]
Looks like another case for #329
