### ISSUE TITLE
[Search]: crash when searching in large files

### ISSUE THREAD

**Issue by PetbkA** [variar/klogg#319]
Details for the issue
--------------------
Searching in pretty large files causes crash after search is finished.

#### What did you do?
1. Search anything in large files (e.g. in [NVD Data Feed for year 2020](https://nvd.nist.gov/vuln/data-feeds))

-------------------------
Crash id
264c94d1-4bd3-40d4-a44c-c7e3dd793c1a
-------------------------
Useful extra information
-------------------------
> Klogg version 21.05.0.978 (built from commit c09d0cc) [built for x86_64-little_endian-llp64]
> running on Windows 10 Version 1809 (winnt/10.0.17763) [x86_64]
> and Qt 5.15.2

**Comment by variar** [comment]
Hi, sorry for that. Should be fixed in 21.05.0.989.

**Comment by PetbkA** [comment]
**klogg-21.05.0.1016-x64** - fixed. Thank you!
