### ISSUE TITLE
New Crash Report for issue #286 (#272)

### ISSUE THREAD

**Issue by GeadSolutions** [variar/klogg#325]
This is a new report adding another informations to those tickets opened before.

Details for the issue
--------------------

#### What did you do?

-------------------------
Crash id
e21ded45-8731-4d96-8d7a-b6b203042e76
-------------------------
Useful extra information
-------------------------
> Klogg version 20.12.0.813 (built from commit 576b91d) [built for x86_64-little_endian-llp64]
> running on Windows 10 Version 2009 (winnt/10.0.19042) [x86_64]
> and Qt 5.15.2

**Comment by variar** [comment]
Thanks for the report. I think that this particular crash should be fixed in dev builds.  Could you try latest [dev-builds](https://github.com/variar/klogg/releases/tag/continuous-win) with the same file? Just grab portable version for quick test, no setup needed.

**Comment by variar** [comment]
Feel free to reopen if crash can be reproduced in dev-builds
