### ISSUE TITLE
Unable to open klogg due to crash

### ISSUE THREAD

**Issue by jgscherber** [variar/klogg#331]
This started happening after a re-start. I tried uninstalling the version of Klogg I had (a dev version), and re-installing the latest dev version (klogg-21.05.0.1018-x64-setup.exe).

Attached is the folder from the klogg_dumb folder

[2bf1099e-b420-44b3-62c4-39146a20f543.run.zip](https://github.com/variar/klogg/files/6576721/2bf1099e-b420-44b3-62c4-39146a20f543.run.zip)

**Comment by variar** [comment]
Hi, sorry for that. There is no crash information in that archive.  Looks more like previous version has left a lock that prevents start of new instance. Could you launch klogg from command line with logging enabled and attach the file to this issue?
Command should be like this:
```
"C:\Program Files\klogg\klogg.exe" -d -l
```

This should create a log file in `%Temp%` directory.

If my guess about stale lock is right, then reboot should help.

**Comment by jgscherber** [comment]
Sorry, I thought the zip would be enough so I uninstalled it and re-installed the stable version. The stable version launched and is running correctly. You can close this if you want.
