### ISSUE TITLE
[Feature] support go to line

### ISSUE THREAD

**Issue by bigdogs** [variar/klogg#334]
hi, 

Can we support the feature of "Go to Line" like vscode? 
![image](https://user-images.githubusercontent.com/20614926/121287506-417a6000-c914-11eb-97d3-ad7de27e8e8c.png)

**Comment by variar** [comment]
Hi, `Alt+G` should show a dialog for this. Maybe this is not very good hotkey on Mac?

In current dev-builds shortcuts can be configured in settings dialog.

**Comment by bigdogs** [comment]
Sorry for the missing...  it's seem a very strange hotkey on mac:(
hot key on macos always combine with "cmd", e.g. hotkey for "go to line" on  VsCode is  `cmd +G`, on  "inteijj idea" is `cmd + L`.
Anyway, it would be grate to add an entry on menu for this feature if possible :) ,  as we can not always remember so many hot keys for different application on different platform even for the same feature

**Comment by variar** [comment]
Looks like `cmd+L` is unused in klogg. I'll change default shortcut to that in next dev-builds. Adding a menu item is on todo list. In fact all actions which have hotkeys should have a corresponding menu item so one can spot them in UI.

**Comment by bigdogs** [comment]
Thanks you very much ~~

**Comment by variar** [comment]
Should be in 21.06.0.1026
