### ISSUE TITLE
Crash while changing the charset (encoding) to UNICODE

### ISSUE THREAD

**Issue by psylinux** [variar/klogg#335]
Details for the issue
--------------------

#### What did you do?

-------------------------
Crash id
55012d47-613e-413e-b429-3339c1cc1081
-------------------------
Useful extra information
-------------------------
> Klogg version 20.12.0.813 (built from commit 576b91d) [built for x86_64-little_endian-lp64]
> running on macOS 11.4 (darwin/20.5.0) [x86_64]
> and Qt 5.15.2

**Comment by variar** [comment]
Could you try latest [dev](https://github.com/variar/klogg/releases/tag/continuous-osx) version? Some data races have been fixed there.

**Comment by variar** [comment]
Can't reproduce on dev builds.
