### ISSUE TITLE
Allow setting alpha value or transparent color in highlighters

### ISSUE THREAD

**Issue by legier** [variar/klogg#337]
Please allow to set alpha value of chosen color (or add transparent color) in highlighters.
When making a rule with only Fore Color specified it becomes very ugly if one changes theme from light to dark and all the set Back Colors are now extremely visible.

**Comment by variar** [comment]
Transparency for highlighters is indeed a great feature.  I've tried it, but there were some rendering issues on Mac, and I don't know whether it is related to my Mac setup inside VirtualBox or a bug in klogg. I wish I had access to real Mac machine, that would make things much easier. I'll try to investigate it further.

**Comment by variar** [comment]
Can be tested in 21.06.0.1053+
