### ISSUE TITLE
Column with lines' numbers being dark with static

### ISSUE THREAD

**Issue by MrMacduckinson** [variar/klogg#340]
Build 20.12.0.813, macOS. When you search lines in file, the column with numbers of lines will appear dark and with static. When you scroll this box, the column will turn completely black. Then you can view the numbers only by expanding/reducing the window.
<img width="514" alt="Снимок экрана 2021-06-15 в 00 10 38" src="https://user-images.githubusercontent.com/49838563/121961183-c11e8980-cd6f-11eb-8918-1c57fea7f6a5.png">
<img width="618" alt="Снимок экрана 2021-06-15 в 00 10 33" src="https://user-images.githubusercontent.com/49838563/121961186-c24fb680-cd6f-11eb-997c-15fec7ee5686.png">
<img width="728" alt="Снимок экрана 2021-06-15 в 00 10 27" src="https://user-images.githubusercontent.com/49838563/121961188-c2e84d00-cd6f-11eb-9f04-812f346a73b9.png">

**Comment by variar** [comment]
Looks the same as #249. Should be fixed in dev-builds. Could you give it a try?

**Comment by variar** [comment]
Closing as duplicate for now

**Comment by MrMacduckinson** [comment]
> Looks the same as #249. Should be fixed in dev-builds. Could you give it a try?

In dev-build it works well. Thanks!
