### ISSUE TITLE
Crash while saving new filter string

### ISSUE THREAD

**Issue by ilev4ik** [variar/klogg#346]
Details for the issue
--------------------

#### What did you do?

Создал строку фильтра, попытался сохранить его через контекстное меню. Переименовал название фильтра, нажал ОК -> crash
Created filter string, saved it by context menu. Renamed filter name, clicked OK -> crash

-------------------------
Crash id:
11b1e5c1-a310-4e58-99f7-129576d77764
-------------------------
Useful extra information
-------------------------
> Klogg version 21.06.0.1026 (built on 2021-06-09 from commit 4c29f49) [built for x86_64-little_endian-llp64]
> running on Windows 7 Version 6.1 (Build 7601: SP 1) (winnt/6.1.7601) [x86_64]
> and Qt 5.15.2

**Comment by variar** [comment]
Thanks. This is the same as of #342. Should be fixed in 21.06.0.1030.
