### ISSUE TITLE
klogg crashed during searching a word in a 15GB file

### ISSUE THREAD

**Issue by necrosword0** [variar/klogg#350]
Details for the issue
--------------------

#### What did you do?

-------------------------
Crash id
8a73301f-a5fe-4cd7-9c48-3a09bc18f682
-------------------------
Useful extra information
-------------------------
> Klogg version 20.12.0.813 (built from commit 576b91d) [built for x86_64-little_endian-lp64]
> running on macOS 11.4 (darwin/20.5.0) [x86_64]
> and Qt 5.15.2

**Comment by variar** [comment]
Thanks for report. Could you try latest [dev](https://github.com/variar/klogg/releases/tag/continuous-osx) version? Support for large files has been improved.
