### ISSUE TITLE
If started from another process, klogg seems to ignore its window position stored in the conf

### ISSUE THREAD

**Issue by ArsMasiuk** [variar/klogg#355]
Details for the issue
--------------------

#### What did you do?
klogg_portable has been started as a process with certain log file name as parameters

#### What did you expect to see?
klogg opens the log file using settings from conf file (highlighters, options, window position & size etc.)

#### What did you see instead?
the conf file seems to be read (as klogg took all the custom highlighters) but window position & size still remain default(?)

When klogg_portable starts from the explorer however, the window position & size are applied correctly.

Useful extra information
-------------------------
> Klogg version 20.12.0.0 (built on 2021-02-12 from commit ) [built for x86_64-little_endian-llp64]
> running on Windows 10 (10.0) (winnt/10.0.19042) [x86_64]
> and Qt 5.13.2

**Comment by variar** [comment]
Thanks for reporting this. The main difference between launching from explorer (without arguments) and starting with some files passed via command line is that without arguments Klogg tries to reload last session, but in case there are some files then new session is created. 

Could you try latest development builds? There were some fixes for session handling (#174, #166).

**Comment by variar** [comment]
Closing for now. Please reopen if this can be reproduced in latest ci builds.

**Comment by variar** [comment]
Another fix landed in 21.07.0.1073

**Comment by ArsMasiuk** [comment]
Looks like fixed with 21.09.
