### ISSUE TITLE
Allow selecting several highlighters

### ISSUE THREAD

**Issue by thestalker** [variar/klogg#360]
Awesome tool, enjoy using it!
I'd like to define several highlighters and turn them on and off as I like, meaning to have an ability to select more than one active highlighter.
Today we can select only one highlighter at a time:
![image](https://user-images.githubusercontent.com/26576702/125431388-6d46ab9e-0578-4ad2-ad2a-27dce6eeac68.png)

**Comment by variar** [comment]
Hi, thanks. This idea seems more user friendly than current behaviour with switching between different sets of highlighters.

**Comment by sovsiann** [comment]
Great:) any estimation when it will be implemented?

**Comment by variar** [comment]
Sorry, can't give any estimation. There is a lot going on right now.

**Comment by variar** [comment]
Can be tested in 21.08.0.1126

**Comment by sovsiann** [comment]
looks exactly what I needed! thanks!!
