### ISSUE TITLE
Maximized state not restored on klogg open

### ISSUE THREAD

**Issue by tomhanak** [variar/klogg#362]
**What did you do?**
klogg is started as associated app for ```.log``` file, or via Start menu, or directly from File Explorer.

**What did you expect to see?**
klogg window opens with stored window position and size, and especially restores its maximized state if the last closed window was maximized.
If I remember well, it worked about a year ago...

**What did you see instead?**
The window position, size and maximized state remain default.

**Useful extra information**
- Tested:
-- Klogg installed via Chocolatey (version 20.12.0.813 (built on 2020-12-24 from commit 576b91d), Qt 5.15.2
-- Klogg portable "continuous-win" (version 21.06.0.1057 (built on 2021-07-06 from commit fabe5a3), Qt 5.15.2
- on Windows 10 Enterprise 64-bit (version 20H2, build 19042)

**Comment by variar** [comment]
Thanks for reporting this. Looks a lot like #355. Need more fixes.

**Comment by variar** [comment]
Could be fixed in 21.07.0.1073

**Comment by tomhanak** [comment]
I have confirmed with 21.07.0.1087 the issue is fixed. Thanks.
