### ISSUE TITLE
Persist the options of checkbox values "Line numbers in main view" and "Line numbers in filtered view" in menu bar

### ISSUE THREAD

**Issue by sken130** [variar/klogg#366]
As titled, so that I don't need to retick/untick them every time I start up klogg.

**Comment by jeffjensen** [comment]
Mine persist.  It's these properties in klogg.conf:
```
view.lineNumbersVisibleInMain=true
view.lineNumbersVisibleInFiltered=true

```

**Comment by sken130** [comment]
For Windows, the config file is at C:\Users\<user name>\AppData\Roaming\klogg\klogg.ini

If I tick it through the UI, these lines won't be updated:

view.lineNumbersVisibleInMain=xxx
view.lineNumbersVisibleInFiltered=xxx

I have to modify the config file manually to make it work.

Note that this is just a the workaround, and I still hope the application can store the config by itself.

**Comment by sken130** [comment]
I found another quicker workaround.
After we tick/untick the "Line numbers in main view" in the menu bar, we can go to Tools --> Options, and click OK. This should trigger the persistence of the configurations. And next time I start up klogg, the "Line numbers in main view" is set to my favorite option now.

I think this also shows where the problem is: Ticking/Unticking of "View --> Line numbers in main view" fails to trigger a config save.

**Comment by variar** [comment]
@sken130 this looks the same as #349. In 20.12 release there was a bug with saving these options. Should be fixed in recent builds.

**Comment by sken130** [comment]
Oh, good, thanks. I should've searched against the closed issues too.
