### ISSUE TITLE
search result may be wrong during auto-refresh file

### ISSUE THREAD

**Issue by xaljer** [variar/klogg#374]
I use `adb logcat > logcat.log` and view the logcat.log with klogg. I found that sometimes I can't get search results corresponding to search pattern. It seems like search cache is not invalidated. reopen the file or klogg can fix that.

**Comment by variar** [comment]
@xaljer could you try turning on/off fast file modification detection?

**Comment by xaljer** [comment]
OK, it will take effect immediately?

**Comment by variar** [comment]
These settings change the context of the index, so file needs to be reloaded manually after changing these settings.

**Comment by xaljer** [comment]
I reproduce this issue when fast file modification detection is off. Search count is shown but there is no search result.

**Comment by variar** [comment]
Thats very disturbing and should not happen. Could you enable logging and collect a log file with this issue? It might contain useful insights.

**Comment by xaljer** [comment]
I reproduce that in an isolate environment, so I can't send log file out. And I think this issue may hard to reproduce, I use klogg  every day but only two or three times it happens. But I can try to check the log if it happen again. Which verbose level of log would be enough?

Does klogg have kind of test program can be invoked from script? so that we can simulate this case, and check if results are right under some test patterns. That would be meaningful for stress test and CI.

**Comment by variar** [comment]
I don't know exact pattern to look for. This kind of log analysis is mostly based on intuition. Let's try to narrow down possible scenarios. Does this happen when search autorefresh is turned on? Or at some point searching for a new pattern results in this situation? And when the issue happened no new search can be done until file is reloaded manually?  Klogg is still in follow file mode at this momen? Does top view continue to update with new lines from logcat.log?

**Comment by xaljer** [comment]
Sorry I am not very sure for all question at that moment.

> Does this happen when search auto-refresh is turned on?

yes.

> And when the issue happened no new search can be done until file is reloaded manually?

reload manually seems not solve this.

> Does top view continue to update with new lines from logcat.log?

yes, I think top view still works fine.

I often do `adb logcat > logcat.log` again and again, so last one will clear the file content and fill new lines. This may break something?

**Comment by variar** [comment]
> last one will clear the file content and fill new lines

That might be the case. I generally test tail mode without overwriting the whole file repeatedly. I'll look into it.

**Comment by variar** [comment]
I think I've found the problem. Search results are cached based on regex pattern and first/last lines of search region.  When the current file is replaced with new one with the same number of lines the key for the search cache stays the same but cached results are completely wrong. In the next builds search results cache will be invalidated on file reload (either manual or auto).

**Comment by variar** [comment]
Thanks for catching this cache invalidation problem :)

**Comment by variar** [comment]
Fix landed in 21.08.0.1096
