### ISSUE TITLE
Find in file 3,36GB

### ISSUE THREAD

**Issue by fernandoog** [variar/klogg#376]
Details for the issue
--------------------

#### What did you do?

-------------------------
Crash id:
e45d191a-8460-47cd-9926-65c9f7f2f0ea
-------------------------
Useful extra information
-------------------------
> Klogg version 21.05.0.998 (built on 2021-05-24 from commit c6701be) [built for i386-little_endian-ilp32]
> running on Windows 10 Version 2009 (winnt/10.0.19043) [x86_64]
> and Qt 5.15.2

**Comment by variar** [comment]
Could you please try recent 64-bit version? x86 builds have stricter limits on file size, number of lines and maximum single line length.
