### ISSUE TITLE
Win32 version

### ISSUE THREAD

**Issue by SeregaKR** [variar/klogg#38]
Hello.
Readme suggests going to AppVeyor to download win32 build, but I'm not familiar with it and there seems to be only file for win64 (latest build).
Can you please tell me how to download win32 build and update Readme?

**Comment by variar** [comment]
Hello, there is no regular build for win32 version at the moment, nobody asked for it. I'll try to figure out how to do it with appveyor.

**Comment by variar** [comment]
Appveyor doesn't have 32-bit Qt5 together with Visual Studio 2017. I don't know if Visual Studio 2015 is capable of building klogg. I don't have visual studio 2015 right now and will be grateful if anyone builds 32 bit klogg and share information.

**Comment by variar** [comment]
I've update appveyor to build 32-bit version. Links to ci build are added to readme
