### ISSUE TITLE
Crash when creating predefined Issue

### ISSUE THREAD

**Issue by ramaralo** [variar/klogg#381]
Details for the issue
--------------------

#### What did you do?

1. Added a new Predefined filter
2. Clicked to move that filter to the top
3. App crashed.

I notice that the following steps do not cause the crash:
1. Added a new Predefined filter
2. Close the Predefined Filters window
3. Reopen Predefined Filters window
4. Reorder last created filer
5. Close the Predefined Filters window

-------------------------
Crash id:
86b720b2-a631-4f3b-a2c4-03f0c1e4506f
-------------------------
Useful extra information
-------------------------
> Klogg version 21.06.0.1042 (built on 2021-06-18 from commit 640c64e) [built for x86_64-little_endian-lp64]
> running on macOS Mojave (10.14) (darwin/18.6.0) [x86_64]
> and Qt 5.15.2

**Comment by variar** [comment]
Thanks for the feedback. This was fixed in recent dev builds. Try 21.08.0.1096.
