### ISSUE TITLE
Crash on start - klogg-21.08.0.1096-Linux.deb

### ISSUE THREAD

**Issue by Shadow505** [variar/klogg#382]
Hi,

I just tried the new testing version _klogg-21.08.0.1096-Linux.deb_ but it immediately crashes on start with the following error:

`klogg: symbol lookup error: klogg: undefined symbol: __cxa_throw_bad_array_new_length, version Qt_5`

**Comment by variar** [comment]
Hi, 

From the error message it seems that compilation flags for klogg and installed Qt version are different.

What distribution are you using? What Qt version is installed?

**Comment by Shadow505** [comment]
Hi,

QMake version 3.1
Using Qt version 5.15.2 in /usr/lib/x86_64-linux-gnu

**Comment by variar** [comment]
Is this a custom built Qt? Or is it installed using package manager? If it is installed using package manager, then could you describe the commands used to install it?

And it would really help if you provide a name of your Linux distribution. Is it Ubuntu/Debian/Mint? Or something else? I can then install it in a virtual machine and check the error.

**Comment by Shadow505** [comment]
No, it's from the ubuntu repo. I am running **Ubuntu 21.04**, the regular qt5 package that bundles all components is not available yet, so I had to install them separately via:

`apt install qtbase5-dev qt5-qmake qtbase5-dev-tools qtchooser `

Thanks!

**Comment by variar** [comment]
Thanks. I've reproduced the issue using docker container. It seems that klogg build bot is using non-standard Qt binaries. I'll try to switch to the binaries from Ubuntu repository.

**Comment by variar** [comment]
@Shadow505  should be fixed in 21.08.0.1101

**Comment by Shadow505** [comment]
@variar Thanks, it's working now!
