### ISSUE TITLE
Color priority

### ISSUE THREAD

**Issue by xaljer** [variar/klogg#385]
Current line has the blue background color, but it should has lowest priority than other highlights.
Quick Find color can be shown on current line, and colors of highlighters and quick highlighters should also be shown.

By the way, could marked lines have a background color like current line?

**Comment by variar** [comment]
Blue background is indicating selected text. When the whole line is highlighted this way that means this line will get copied to the clipboard. I've tried giving it lower priority, but it looks really wired, especially when multiple lines are selected.

**Comment by variar** [comment]
Moved marked lines highlight to #387

**Comment by xaljer** [comment]
> Blue background is indicating selected text.

Not always I think. a mouse click in klogg will select a line but not a word. I don't know what's the advantage of this, but select a word is more common? I mean when i click,  I often don't want to copy the line, but just give myself a focus. So sometimes, I click to focus on this line, but I lost some highlight information. So I may need to click somewhere else.
I don't see the real effect, but I would tend to think background color can give enough visual cues for the selection. We could keep discuss on this and try to look opinions from others.

On the other hand, do you think select a single word by default would be better? and base on it, further feature like highlight current word could be considered.

**Comment by variar** [comment]
Copying some lines from a log file into a bug report is my main use case. Sometimes I do it line by line, so selecting a whole line with single click saves some time. I mostly select words when I need to replace a search pattern. I'll try to change a way that single line selection is displayed and see how it works.

**Comment by jeffjensen** [comment]
FWIW, I mainly copy blocks of lines or a word.  Double-clicking a word already selects just that word!  When needing a few words, click & drag highlights them.

As for the "highlighting current line w/highlights" coloring issue, I suggest also highlight the current line's line number.  Then, don't overwrite any highlighted characters in current line's text.  A current line with whole line highlighted then only has the line number with the current line blue - still easy to see the current line.

**Comment by variar** [comment]
In 21.08.0.1112 current selected line is marked without filling all line with blue background, just top and bottom horizontal lines. Need feedback for this UX.

**Comment by variar** [comment]
Line number area is not always visible. I'll try to add highlight to the area with line type marks, but it might interfere with current match/mark symbols.

**Comment by xaljer** [comment]
It looks good to me, and also positive feedback from my colleague.
