### ISSUE TITLE
Error in expression: ERR006 - Invalid numeric token

### ISSUE THREAD

**Issue by janafrank** [variar/klogg#389]
Is it possible to display more helpful error messages? 

I wanted to try the logical combining mode, but got this error and no clue why would the simplest queries not work. Just assumed it was _because dev build_ 🙃

In my case, it turned out the query needed to be in "quotes". It would be great if klogg could show the user something more helpful when this happens. Alternatively, we can mention this important bit in the tooltip for the button.

**Comment by variar** [comment]
Improved error messages in 21.08.0.1154

**Comment by variar** [comment]
Moved parser improvement to #397
