### ISSUE TITLE
[Highlighters][Color Picker]: can't approve color selection by double click

### ISSUE THREAD

**Issue by PetbkA** [variar/klogg#395]
**OS:** Windows 10 LTSC (version 1809) x64
**App Version:** 21.08.0.1154
![klogg_2021-09-02_06-56-13](https://user-images.githubusercontent.com/22843816/131779589-ddeb092e-27c0-4fa3-b0e4-46e4833d1194.png)

**Comment by variar** [comment]
That dialog comes from Qt. Unfortunately, there is no way to handle double click in klogg.

**Comment by variar** [comment]
There might be a custom color picker widget that works with double clicks.  I've checked https://mattbas.gitlab.io/Qt-Color-Widgets/, but on the screenshots there is no panel with basic/custom colors out of the box, but it can be added

**Comment by PetbkA** [comment]
> but on the screenshots there is no panel with basic/custom colors out of the box

It's  _ColorPaletteWidget and Swatch_ widget, isn't it?
