### ISSUE TITLE
App crash when right click on selected text

### ISSUE THREAD

**Issue by josipoviciwan** [variar/klogg#396]
Details for the issue
--------------------

#### What did you do?
Right click on a select text part, this happened about 10 times now already.

-------------------------
Crash id:
b9d659f3-081c-49e6-bcfa-659c9868886a
-------------------------
Useful extra information
-------------------------
> Klogg version 21.08.0.1112 (built on 2021-08-22 from commit 939e112) [built for x86_64-little_endian-lp64]
> running on Ubuntu 20.04.3 LTS (linux/5.11.0-27-generic) [x86_64]
> and Qt 5.12.8

**Comment by variar** [comment]
@josipoviciwan sorry for that. It is the same as #388. Should be fixed in recent dev-builds https://github.com/variar/klogg/releases/tag/continuous-win
