### ISSUE TITLE
Crash after dragging the file

### ISSUE THREAD

**Issue by Oleiva** [variar/klogg#398]
Details for the issue
--------------------

#### What did you do?

-------------------------
Crash id
43728d33-0067-4945-80cf-e432967d81bf
-------------------------
Useful extra information
-------------------------
> Klogg version 21.01.0.819 (built from commit 0433356) [built for x86_64-little_endian-lp64]
> running on macOS 11.4 (darwin/20.5.0) [x86_64]
> and Qt 5.15.2

**Comment by variar** [comment]
Could you check if this crash is still happening in recent dev builds?

**Comment by Oleiva** [comment]
looks like the last version works ok.
