### ISSUE TITLE
Make window position & size persistent

### ISSUE THREAD

**Issue by ArsMasiuk** [variar/klogg#399]
It would be nice that klogg could remember its position & size when opened again.

**Comment by variar** [comment]
Hi, what version are you using? And how are you launching klogg? There were some quirks with position restoration in 20.12 release, and they were fixed in latest dev builds (which are currently stable for every day use)

**Comment by variar** [comment]
Could be as #174

**Comment by ArsMasiuk** [comment]
Hi, yes, I'm using 20.12 version. klogg is called as a command with parameters (file name to open).
Looks like it has been reported already...

**Comment by variar** [comment]
Could you try latest version and check if your scenarios work as expected?

**Comment by ArsMasiuk** [comment]
I'll try on monday

**Comment by ArsMasiuk** [comment]
Unfortunately I cannot build the recent klogg (21.09) with MSVC 2019 / Qt 5.15.2 because of following issues:

Build started...
1>------ Build started: Project: generate_version, Configuration: Release x64 ------
1>fatal: not a git repository (or any of the parent directories): .git
1>Git branch:
1>fatal: not a git repository (or any of the parent directories): .git
1>Git commit:
1>fatal: not a git repository (or any of the parent directories): .git
1>Git describe:
2>------ Build started: Project: klogg_version, Configuration: Release x64 ------
2>cl : command line warning D9025: overriding '/external:W4' with '/external:W0'
2>klogg_version.cpp
2>klogg_version.vcxproj -> C:\Users\dhdam\Downloads\klogg-master-BUILD\output\Release\klogg_version.lib
2>Done building project "klogg_version.vcxproj".
3>------ Build started: Project: klogg_settings, Configuration: Release x64 ------
3>cl : command line warning D9025: overriding '/external:W4' with '/external:W0'
3>configuration.cpp
3>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(28,64): error C2131: expression did not evaluate to a constant
3>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(28,64): message : failure was caused by call of undefined function or one not declared 'constexpr'
3>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(28,64): message : see usage of 'QLatin1String::QLatin1String'
3>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(29,71): error C2131: expression did not evaluate to a constant
3>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(29,71): message : failure was caused by call of undefined function or one not declared 'constexpr'
3>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(29,71): message : see usage of 'QLatin1String::QLatin1String'
3>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(30,60): error C2131: expression did not evaluate to a constant
3>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(30,60): message : failure was caused by call of undefined function or one not declared 'constexpr'
3>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(30,60): message : see usage of 'QLatin1String::QLatin1String'
3>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(31,61): error C2131: expression did not evaluate to a constant
3>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(31,61): message : failure was caused by call of undefined function or one not declared 'constexpr'
3>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(31,61): message : see usage of 'QLatin1String::QLatin1String'
3>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(32,62): error C2131: expression did not evaluate to a constant
3>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(32,62): message : failure was caused by call of undefined function or one not declared 'constexpr'
3>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(32,62): message : see usage of 'QLatin1String::QLatin1String'
3>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(33,64): error C2131: expression did not evaluate to a constant
3>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(33,64): message : failure was caused by call of undefined function or one not declared 'constexpr'
3>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(33,64): message : see usage of 'QLatin1String::QLatin1String'
3>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(35,59): error C2131: expression did not evaluate to a constant
3>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(35,59): message : failure was caused by call of undefined function or one not declared 'constexpr'
3>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(35,59): message : see usage of 'QLatin1String::QLatin1String'
3>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(36,59): error C2131: expression did not evaluate to a constant
3>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(36,59): message : failure was caused by call of undefined function or one not declared 'constexpr'
3>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(36,59): message : see usage of 'QLatin1String::QLatin1String'
3>styles.cpp
3>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(28,64): error C2131: expression did not evaluate to a constant
3>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(28,64): message : failure was caused by call of undefined function or one not declared 'constexpr'
3>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(28,64): message : see usage of 'QLatin1String::QLatin1String'
3>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(29,71): error C2131: expression did not evaluate to a constant
3>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(29,71): message : failure was caused by call of undefined function or one not declared 'constexpr'
3>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(29,71): message : see usage of 'QLatin1String::QLatin1String'
3>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(30,60): error C2131: expression did not evaluate to a constant
3>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(30,60): message : failure was caused by call of undefined function or one not declared 'constexpr'
3>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(30,60): message : see usage of 'QLatin1String::QLatin1String'
3>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(31,61): error C2131: expression did not evaluate to a constant
3>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(31,61): message : failure was caused by call of undefined function or one not declared 'constexpr'
3>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(31,61): message : see usage of 'QLatin1String::QLatin1String'
3>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(32,62): error C2131: expression did not evaluate to a constant
3>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(32,62): message : failure was caused by call of undefined function or one not declared 'constexpr'
3>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(32,62): message : see usage of 'QLatin1String::QLatin1String'
3>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(33,64): error C2131: expression did not evaluate to a constant
3>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(33,64): message : failure was caused by call of undefined function or one not declared 'constexpr'
3>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(33,64): message : see usage of 'QLatin1String::QLatin1String'
3>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(35,59): error C2131: expression did not evaluate to a constant
3>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(35,59): message : failure was caused by call of undefined function or one not declared 'constexpr'
3>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(35,59): message : see usage of 'QLatin1String::QLatin1String'
3>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(36,59): error C2131: expression did not evaluate to a constant
3>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(36,59): message : failure was caused by call of undefined function or one not declared 'constexpr'
3>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(36,59): message : see usage of 'QLatin1String::QLatin1String'
3>Done building project "klogg_settings.vcxproj" -- FAILED.
4>------ Build started: Project: klogg_versioncheck, Configuration: Release x64 ------
5>------ Build started: Project: klogg_logdata, Configuration: Release x64 ------
4>Automatic MOC for target klogg_versioncheck
5>Automatic MOC for target klogg_logdata
4>cl : command line warning D9025: overriding '/external:W4' with '/external:W0'
4>mocs_compilation.cpp
5>cl : command line warning D9025: overriding '/external:W4' with '/external:W0'
5>compressedlinestorage.cpp
5>C:\Qt\5.15.2\msvc2019_64\include\QtCore/qfloat16.h(75,39): error C2220: the following warning is treated as an error
5>C:\Qt\5.15.2\msvc2019_64\include\QtCore/qfloat16.h(75,39): warning C4242: 'initializing': conversion from 'int' to 'quint16', possible loss of data
4>C:\Qt\5.15.2\msvc2019_64\include\QtCore/qfloat16.h(75,39): error C2220: the following warning is treated as an error
4>C:\Qt\5.15.2\msvc2019_64\include\QtCore/qfloat16.h(75,39): warning C4242: 'initializing': conversion from 'int' to 'quint16', possible loss of data
4>versionchecker.cpp
5>encodingdetector.cpp
4>C:\Qt\5.15.2\msvc2019_64\include\QtCore/qfloat16.h(75,39): error C2220: the following warning is treated as an error
4>C:\Qt\5.15.2\msvc2019_64\include\QtCore/qfloat16.h(75,39): warning C4242: 'initializing': conversion from 'int' to 'quint16', possible loss of data
5>C:\Users\dhdam\Downloads\klogg-master\src\logdata\src\encodingdetector.cpp(69,36): error C2127: 'LineFeed': illegal initialization of 'constexpr' entity with a non-constant expression
5>C:\Qt\5.15.2\msvc2019_64\include\QtCore/qmetatype.h(2089,1): message : failure was because type 'QChar' is not a literal type
5>C:\Qt\5.15.2\msvc2019_64\include\QtCore/qmetatype.h(2089,1): message : type 'QChar' is not a literal type because it is not an aggregate type, a closure type, or does not have a constexpr constructor that is not a copy or move constructor
5>Done building project "klogg_logdata.vcxproj" -- FAILED.
4>C:\Users\dhdam\Downloads\klogg-master\src\versioncheck\src\versionchecker.cpp(48,41): error C2127: '`anonymous-namespace'::OsSuffix': illegal initialization of 'constexpr' entity with a non-constant expression
4>C:\Qt\5.15.2\msvc2019_64\include\QtCore/qregularexpression.h(55,7): message : failure was because type 'QLatin1String' is not a literal type
4>C:\Qt\5.15.2\msvc2019_64\include\QtCore/qregularexpression.h(55,7): message : type 'QLatin1String' is not a literal type because it is not an aggregate type, a closure type, or does not have a constexpr constructor that is not a copy or move constructor
4>C:\Users\dhdam\Downloads\klogg-master\src\versioncheck\src\versionchecker.cpp(56,5): error C2127: '`anonymous-namespace'::VERSION_URL': illegal initialization of 'constexpr' entity with a non-constant expression
4>C:\Qt\5.15.2\msvc2019_64\include\QtCore/qregularexpression.h(55,7): message : failure was because type 'QLatin1String' is not a literal type
4>C:\Qt\5.15.2\msvc2019_64\include\QtCore/qregularexpression.h(55,7): message : type 'QLatin1String' is not a literal type because it is not an aggregate type, a closure type, or does not have a constexpr constructor that is not a copy or move constructor
4>Generating Code...
4>Done building project "klogg_versioncheck.vcxproj" -- FAILED.
6>------ Build started: Project: klogg_ui, Configuration: Release x64 ------
6>Automatic MOC and UIC for target klogg_ui
6>cl : command line warning D9025: overriding '/external:W4' with '/external:W0'
6>abstractlogview.cpp
6>C:\Qt\5.15.2\msvc2019_64\include\QtCore/qfloat16.h(75,39): error C2220: the following warning is treated as an error
6>C:\Qt\5.15.2\msvc2019_64\include\QtCore/qfloat16.h(75,39): warning C4242: 'initializing': conversion from 'int' to 'quint16', possible loss of data
6>crawlerwidget.cpp
6>C:\Users\dhdam\Downloads\klogg-master\src\regex\include\regularexpressionpattern.h(89,43): error C2027: use of undefined type 'std::atomic<uint>'
6>C:\Users\dhdam\Downloads\klogg-master\src\regex\include\regularexpressionpattern.h(89): message : see declaration of 'std::atomic<uint>'
6>C:\Users\dhdam\Downloads\klogg-master\src\regex\include\regularexpressionpattern.h(90,62): error C2676: binary '++': 'std::atomic<uint>' does not define this operator or a conversion to a type acceptable to the predefined operator
6>highlightersdialog.cpp
6>C:\Users\dhdam\Downloads\klogg-master\src\ui\src\highlightersdialog.cpp(56,45): error C2127: 'DEFAULT_NAME': illegal initialization of 'constexpr' entity with a non-constant expression
6>C:\Qt\5.15.2\msvc2019_64\include\QtCore\qregularexpression.h(55,7): message : failure was because type 'QLatin1String' is not a literal type
6>C:\Qt\5.15.2\msvc2019_64\include\QtCore\qregularexpression.h(55,7): message : type 'QLatin1String' is not a literal type because it is not an aggregate type, a closure type, or does not have a constexpr constructor that is not a copy or move constructor
6>highlightersetedit.cpp
6>C:\Users\dhdam\Downloads\klogg-master\src\ui\src\highlightersetedit.cpp(52,48): error C2127: '`anonymous-namespace'::DEFAULT_PATTERN': illegal initialization of 'constexpr' entity with a non-constant expression
6>C:\Qt\5.15.2\msvc2019_64\include\QtCore\qregularexpression.h(55,7): message : failure was because type 'QLatin1String' is not a literal type
6>C:\Qt\5.15.2\msvc2019_64\include\QtCore\qregularexpression.h(55,7): message : type 'QLatin1String' is not a literal type because it is not an aggregate type, a closure type, or does not have a constexpr constructor that is not a copy or move constructor
6>mainwindow.cpp
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(28,64): error C2131: expression did not evaluate to a constant
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(28,64): message : failure was caused by call of undefined function or one not declared 'constexpr'
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(28,64): message : see usage of 'QLatin1String::QLatin1String'
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(29,71): error C2131: expression did not evaluate to a constant
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(29,71): message : failure was caused by call of undefined function or one not declared 'constexpr'
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(29,71): message : see usage of 'QLatin1String::QLatin1String'
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(30,60): error C2131: expression did not evaluate to a constant
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(30,60): message : failure was caused by call of undefined function or one not declared 'constexpr'
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(30,60): message : see usage of 'QLatin1String::QLatin1String'
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(31,61): error C2131: expression did not evaluate to a constant
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(31,61): message : failure was caused by call of undefined function or one not declared 'constexpr'
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(31,61): message : see usage of 'QLatin1String::QLatin1String'
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(32,62): error C2131: expression did not evaluate to a constant
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(32,62): message : failure was caused by call of undefined function or one not declared 'constexpr'
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(32,62): message : see usage of 'QLatin1String::QLatin1String'
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(33,64): error C2131: expression did not evaluate to a constant
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(33,64): message : failure was caused by call of undefined function or one not declared 'constexpr'
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(33,64): message : see usage of 'QLatin1String::QLatin1String'
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(35,59): error C2131: expression did not evaluate to a constant
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(35,59): message : failure was caused by call of undefined function or one not declared 'constexpr'
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(35,59): message : see usage of 'QLatin1String::QLatin1String'
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(36,59): error C2131: expression did not evaluate to a constant
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(36,59): message : failure was caused by call of undefined function or one not declared 'constexpr'
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(36,59): message : see usage of 'QLatin1String::QLatin1String'
6>optionsdialog.cpp
6>C:\Qt\5.15.2\msvc2019_64\include\QtCore/qfloat16.h(75,39): error C2220: the following warning is treated as an error
6>C:\Qt\5.15.2\msvc2019_64\include\QtCore/qfloat16.h(75,39): warning C4242: 'initializing': conversion from 'int' to 'quint16', possible loss of data
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(28,64): error C2131: expression did not evaluate to a constant
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(28,64): message : failure was caused by call of undefined function or one not declared 'constexpr'
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(28,64): message : see usage of 'QLatin1String::QLatin1String'
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(29,71): error C2131: expression did not evaluate to a constant
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(29,71): message : failure was caused by call of undefined function or one not declared 'constexpr'
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(29,71): message : see usage of 'QLatin1String::QLatin1String'
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(30,60): error C2131: expression did not evaluate to a constant
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(30,60): message : failure was caused by call of undefined function or one not declared 'constexpr'
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(30,60): message : see usage of 'QLatin1String::QLatin1String'
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(31,61): error C2131: expression did not evaluate to a constant
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(31,61): message : failure was caused by call of undefined function or one not declared 'constexpr'
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(31,61): message : see usage of 'QLatin1String::QLatin1String'
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(32,62): error C2131: expression did not evaluate to a constant
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(32,62): message : failure was caused by call of undefined function or one not declared 'constexpr'
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(32,62): message : see usage of 'QLatin1String::QLatin1String'
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(33,64): error C2131: expression did not evaluate to a constant
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(33,64): message : failure was caused by call of undefined function or one not declared 'constexpr'
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(33,64): message : see usage of 'QLatin1String::QLatin1String'
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(35,59): error C2131: expression did not evaluate to a constant
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(35,59): message : failure was caused by call of undefined function or one not declared 'constexpr'
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(35,59): message : see usage of 'QLatin1String::QLatin1String'
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(36,59): error C2131: expression did not evaluate to a constant
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(36,59): message : failure was caused by call of undefined function or one not declared 'constexpr'
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(36,59): message : see usage of 'QLatin1String::QLatin1String'
6>quickfind.cpp
6>C:\Qt\5.15.2\msvc2019_64\include\QtCore/qfloat16.h(75,39): error C2220: the following warning is treated as an error
6>C:\Qt\5.15.2\msvc2019_64\include\QtCore/qfloat16.h(75,39): warning C4242: 'initializing': conversion from 'int' to 'quint16', possible loss of data
6>tabbedcrawlerwidget.cpp
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(28,64): error C2131: expression did not evaluate to a constant
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(28,64): message : failure was caused by call of undefined function or one not declared 'constexpr'
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(28,64): message : see usage of 'QLatin1String::QLatin1String'
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(29,71): error C2131: expression did not evaluate to a constant
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(29,71): message : failure was caused by call of undefined function or one not declared 'constexpr'
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(29,71): message : see usage of 'QLatin1String::QLatin1String'
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(30,60): error C2131: expression did not evaluate to a constant
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(30,60): message : failure was caused by call of undefined function or one not declared 'constexpr'
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(30,60): message : see usage of 'QLatin1String::QLatin1String'
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(31,61): error C2131: expression did not evaluate to a constant
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(31,61): message : failure was caused by call of undefined function or one not declared 'constexpr'
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(31,61): message : see usage of 'QLatin1String::QLatin1String'
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(32,62): error C2131: expression did not evaluate to a constant
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(32,62): message : failure was caused by call of undefined function or one not declared 'constexpr'
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(32,62): message : see usage of 'QLatin1String::QLatin1String'
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(33,64): error C2131: expression did not evaluate to a constant
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(33,64): message : failure was caused by call of undefined function or one not declared 'constexpr'
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(33,64): message : see usage of 'QLatin1String::QLatin1String'
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(35,59): error C2131: expression did not evaluate to a constant
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(35,59): message : failure was caused by call of undefined function or one not declared 'constexpr'
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(35,59): message : see usage of 'QLatin1String::QLatin1String'
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(36,59): error C2131: expression did not evaluate to a constant
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(36,59): message : failure was caused by call of undefined function or one not declared 'constexpr'
6>C:\Users\dhdam\Downloads\klogg-master\src\settings\include\styles.h(36,59): message : see usage of 'QLatin1String::QLatin1String'
6>C:\Users\dhdam\Downloads\klogg-master\src\ui\src\tabbedcrawlerwidget.cpp(42,33): error C2127: '`anonymous-namespace'::PathKey': illegal initialization of 'constexpr' entity with a non-constant expression
6>C:\Qt\5.15.2\msvc2019_64\include\QtCore/qregularexpression.h(55,7): message : failure was because type 'QLatin1String' is not a literal type
6>C:\Qt\5.15.2\msvc2019_64\include\QtCore/qregularexpression.h(55,7): message : type 'QLatin1String' is not a literal type because it is not an aggregate type, a closure type, or does not have a constexpr constructor that is not a copy or move constructor
6>C:\Users\dhdam\Downloads\klogg-master\src\ui\src\tabbedcrawlerwidget.cpp(43,35): error C2127: '`anonymous-namespace'::StatusKey': illegal initialization of 'constexpr' entity with a non-constant expression
6>C:\Qt\5.15.2\msvc2019_64\include\QtCore/qregularexpression.h(55,7): message : failure was because type 'QLatin1String' is not a literal type
6>C:\Qt\5.15.2\msvc2019_64\include\QtCore/qregularexpression.h(55,7): message : type 'QLatin1String' is not a literal type because it is not an aggregate type, a closure type, or does not have a constexpr constructor that is not a copy or move constructor
6>decompressor.cpp
6>C:\Qt\5.15.2\msvc2019_64\include\QtCore/qfloat16.h(75,39): error C2220: the following warning is treated as an error
6>C:\Qt\5.15.2\msvc2019_64\include\QtCore/qfloat16.h(75,39): warning C4242: 'initializing': conversion from 'int' to 'quint16', possible loss of data
6>Done building project "klogg_ui.vcxproj" -- FAILED.
7>------ Build started: Project: klogg, Configuration: Release x64 ------
7>Automatic MOC for target klogg
7>Automatic RCC for klogg.qrc
7>Automatic RCC for ../../generated/documentation.qrc
7>
7>AutoRcc subprocess error
7>------------------------
7>The rcc process failed to compile
7>  "SRC:-BUILD/generated/documentation.qrc"
7>into
7>  "SRC:-BUILD/src/app/klogg_autogen/include_Debug/G2ZEMYGGGB/qrc_documentation_CMAKE_.cpp"
7>
7>Command
7>-------
7>C:/Qt/5.15.2/msvc2019_64/bin/rcc.exe -name documentation -o C:/Users/dhdam/Downloads/klogg-master-BUILD/src/app/klogg_autogen/include_Debug/G2ZEMYGGGB/qrc_documentation_CMAKE_.cpp C:/Users/dhdam/Downloads/klogg-master-BUILD/generated/documentation.qrc
7>
7>Output
7>------
7>RCC: Error in 'C:/Users/dhdam/Downloads/klogg-master-BUILD/generated/documentation.qrc': Cannot find file 'documentation.html'
7>
7>
7>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: Custom build for 'C:\Users\dhdam\Downloads\klogg-master-BUILD\CMakeFiles\05e1a13ba4338e7c05e5914c719fa01d\qrc_klogg.cpp.rule;C:\Users\dhdam\Downloads\klogg-master-BUILD\CMakeFiles\261c9a203530ce3ddd1ec62ed6774890\qrc_documentation.cpp.rule;C:\Users\dhdam\Downloads\klogg-master\src\app\CMakeLists.txt' exited with code 1.
7>Done building project "klogg.vcxproj" -- FAILED.
========== Build: 2 succeeded, 5 failed, 22 up-to-date, 0 skipped ==========

**Comment by ArsMasiuk** [comment]
Have tested with Qt 5.13.2 + MSVC 2017.
The issue looks to be gone for now :)

**Comment by variar** [comment]
That's strange. What exact version of MSVC c++ compiler was used in failed build case? Klogg builds fine on GitHub build agents. Here is some output from configure step:
```
-- The C compiler identification is MSVC 19.29.30133.0
-- The CXX compiler identification is MSVC 19.29.30133.0
-- The ASM compiler identification is MSVC
-- Found assembler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe
...
Qt version 5.15.2
```

**Comment by variar** [comment]
Moved build failure to separate issue for bookkeeping.
