### ISSUE TITLE
Opening file in klogg not working

### ISSUE THREAD

**Issue by BCurbs** [variar/klogg#403]
Details for the issue
--------------------

#### What did you do?
I tried to open a sql file with klogg through my os dialogue and not through the klogg open screen. 
(like right click on file and then open with klogg)
-------------------------
Crash id
d9a40c7a-103c-4a02-b64c-fb75b52b3afe
-------------------------
Useful extra information
-------------------------
> Klogg version 20.12.0.813 (built from commit 576b91d) [built for x86_64-little_endian-lp64]
> running on Ubuntu 20.04.3 LTS (linux/5.11.0-34-generic) [x86_64]
> and Qt 5.12.8

**Comment by variar** [comment]
Hi, sorry for that. Is that sql file very large? Are there any very long lines? Could you try latest [builds](https://github.com/variar/klogg/releases/tag/continuous-linux)? Large file handling has been improved a lot since 20.12 release.

**Comment by 1552937** [comment]
The file opens perfectly when opening klogg then pressing open a file. Its when i use my file manager to open the file in klogg that it has a problem.
________________________________

**Comment by variar** [comment]
Thanks for the info, I'll try to investigate it further

**Comment by variar** [comment]
This looks like an issue #329, that was fixed in 3rdparty library and merged into dev builds of klogg.
