### ISSUE TITLE
Scoop installation support

### ISSUE THREAD

**Issue by tan-wei** [variar/klogg#404]
Since `glogg` is marked deprecated in Scoop, it will be nice to add `klogg` as a replacement. :-P

**Comment by variar** [comment]
Hi, there is a manifest for klogg here https://github.com/variar/klogg/blob/master/packaging/windows/scoop/klogg.json 

And there is a PR to add it into scoop-extras, but looks like something need to fixed and I'm not sure how to do it.
https://github.com/lukesampson/scoop-extras/pull/6738

**Comment by tan-wei** [comment]
Great. Thank you.

**Comment by variar** [comment]
PR merged into scoop-extras master

**Comment by tan-wei** [comment]
Wow!!! Great!!!
