### ISSUE TITLE
Crashing report

### ISSUE THREAD

**Issue by SaitDev** [variar/klogg#405]
Details for the issue
--------------------

#### What did you do?
Searching on a large file

-------------------------
Crash id
025b43be-84c7-4872-b6ce-b689fc4aca73
-------------------------
Useful extra information
-------------------------
> Klogg version 20.12.0.813 (built from commit 576b91d) [built for x86_64-little_endian-lp64]
> running on macOS 11.6 (darwin/20.6.0) [x86_64]
> and Qt 5.15.2

**Comment by variar** [comment]
Thanks for the feedback. Looks like this crash has been fixed in [the latest builds](https://github.com/variar/klogg/releases/tag/continuous-osx). They should be stable for every day use
