### ISSUE TITLE
Feature request: Add a way to send selected text to scratch pad quickly.

### ISSUE THREAD

**Issue by xaljer** [variar/klogg#408]
Such as:
- add a new option in context menu.
- add a shortcut for it.
- show a small window always on the top(something like float window), so that every selection can be sent to scratch pad in real time and results can be shown.

**Comment by variar** [comment]
Added to 21.12.0.1186

**Comment by xaljer** [comment]
A bug: I send a hex number to scratch pad, and "from hex" is not shown. I try to type it manually, it works fine.
A suggestion: If scratch pad is not opened or active when send to it, pop the scratch pad window.

**Comment by variar** [comment]
@xaljer both issues should be fixed in 22.03.0.1211

**Comment by xaljer** [comment]
I think may be old data in scratch pad should be cleared before add new data, otherwise user can't get the correct result for current data. @variar

**Comment by variar** [comment]
That should be a different action: replace data in scratchpad. The use cases are different. Adding data allows to collect some information for future analysis, replacing -- to do transformations.

**Comment by variar** [comment]
Added a separate action to replace data in scratchpad in 22.04.0.1220
