### ISSUE TITLE
Feature request: count and show number of selected lines or characters

### ISSUE THREAD

**Issue by xaljer** [variar/klogg#416]

**Comment by variar** [comment]
Works in 23.06

**Comment by xaljer** [comment]
This feature seems broken on the latest version @variar @Abay11

**Comment by nowhszh** [comment]
@xaljer 导致不能显示已选择的行和字符数量的问题已修复，你可以在[这里](https://github.com/variar/klogg/actions/runs/5456603222#artifacts)下载CI后的产物进行体验，或等待预发行版本发布
