### ISSUE TITLE
Suggestion: use git submodules or some c++ dependency manager

### ISSUE THREAD

**Issue by feliwir** [variar/klogg#419]
Hello,

i noticed that a lot the sourcecode in "3rdparty" is a plain copy of other repository. This makes it hard to track the exact version of the dependencies in use & increases the repository size. I like the concept of "git submodules" and use them regularly. If this is something you can think of aswell i'd happily do a PR to do the switch to use submodules for thirdparty code.

Thanks for your opinion :)

**Comment by variar** [comment]
@feliwir I've switched to CPM to get external dependencies. It is a cmacke-based solution, but it is flexible enough to handle dependencies that don't provide their own cmake build environment. Also this allows to search for locally installed libraries and avoid compilation of hyperscan and tbb.

**Comment by variar** [comment]
#347 should be considered together with this issue

**Comment by variar** [comment]
For 22.04 milestone I consider this done. Sentry is still packed with klogg, but upgrading it will be done in next releases
