### ISSUE TITLE
opening sql dump file crashed klogg immediately

### ISSUE THREAD

**Issue by vmachacek** [variar/klogg#421]
Details for the issue
--------------------

#### What did you do?

opened sql dump file, 
size: 450Mb
when browsing crash dump record window freezes

-------------------------
Crash id
9732d166-9d5c-4721-bd99-b3318dd1394f
-------------------------
Useful extra information
-------------------------
> Klogg version 20.12.0.813 (built from commit 576b91d) [built for x86_64-little_endian-llp64]
> running on Windows 10 Version 2009 (winnt/10.0.19043) [x86_64]
> and Qt 5.15.2

**Comment by variar** [comment]
Could you try latest dev version? There were many changes in handling files with long lines.

**Comment by vmachacek** [comment]
yes, that helped, thanks!
