### ISSUE TITLE
Test Buiilds doesn't automatic update document in klogg

### ISSUE THREAD

**Issue by foordeluxe** [variar/klogg#422]
When I load a document in Klogg, and new text is added automatic to the document I have loaded. It should automatic update this document I have loaded in Klogg.

**In 20.12** This works like it should.

**In Test Builds** This doesn't work.

I wonder if this is removed in Test builds? Because I love to use this feature which is inside 20.12.
I could also say I use Linux with Ubuntu 20.04.03.

**Comment by variar** [comment]
Thanks for reporting this. That should work in dev builds (actually there are tests for basic file updates that are run for each build). Could you double check that file change monitoring is enabled in settings? Also could you enable logging in the advanced options page, then open a file with "follow" mode enabled and try to update the file and attach logs here? Klogg logs should be in /tmp

**Comment by foordeluxe** [comment]
Didn't know about file change monitoring. Now it works. Looks like this was enabled at the first time when using the stable version.
