### ISSUE TITLE
Build 21.9.0.0, Windows 10: "Mark" is applied only after "Find next.." is executed.

### ISSUE THREAD

**Issue by ArsMasiuk** [variar/klogg#423]
When a user selects a word and runs "Mark" action from the context menu, then nothing happens.
If the user chooses "Find next..." from the menu afterwards, then the selected word gets highlighted.
It looks like a regression issue.

**Comment by variar** [comment]
I'm not entirely sure what is wrong here. `Mark` action adds a line to a filtered view, that adds and arrow near the line number but does not highlight anything. `Find next...` invokes a quickfind that indeed does highlight matches. Could you provide more information?

**Comment by variar** [comment]
Also build number suggests that this is a version of klogg that was built locally.
