### ISSUE TITLE
error

### ISSUE THREAD

**Issue by tizzybacym** [variar/klogg#424]
Details for the issue
--------------------

#### What did you do?

-------------------------
Crash id:
dcd235fa-757e-41b7-b220-7d11c11792d0
-------------------------
Useful extra information
-------------------------
> Klogg version 21.08.0.1101 (built on 2021-08-18 from commit c6f506d) [built for x86_64-little_endian-lp64]
> running on macOS 10.15 (darwin/19.6.0) [x86_64]
> and Qt 5.15.2

**Comment by variar** [comment]
Could you check latest dev build? Also some information about what was happening at the moment of crash could help

**Comment by variar** [comment]
Could be fixed in new builds
