### ISSUE TITLE
QuickFind using Fixed Strings selected in options interprets [Error] as regex

### ISSUE THREAD

**Issue by jpsv** [variar/klogg#427]
What version of Klogg are you using? 21.09.0.1165
What operating system are you using? Windows 10
What did you do? QuickFind is highlighting every letter in "[Error]" as if it were looking for regex.
What did you expect to see? Only the string "[Error]" highlighted whereever it is found.
What did you see instead? Every upper case "E", lower-case "r", or lower-case "o" was highlighted.

As a workaround, I've suggested to the colleague that found this bug to escape QuickFinds beginning with open brackets, i.e.
`\[Error]`. Not very ideal but does work(ish)

**Comment by variar** [comment]
That is definetly a bug in quickfind, those `[` `]` should be escaped internally by klogg. I'll look into it

**Comment by variar** [comment]
Should be fixed in 21.12.0.1188

**Comment by jpsv** [comment]
> Should be fixed in 21.12.0.1188

It does appear to be fixed! After a short testing period. Thank you so much.

**Comment by variar** [comment]
Closing for now
