### ISSUE TITLE
Help Appreciated: Can't find option to change default font 

### ISSUE THREAD

**Issue by truebucha** [variar/klogg#428]
Hi! I use the version for Mac.

Several releases ago font option disappeared from the Preferences. Since then I used it as is until I got a new mac. for it's screen size default font is too small.

Can User change a font or at least select a different size for it for the mac app?

Really need your advice,
Thank you!

**Comment by variar** [comment]
Hi, font options should be there. They should be in Options dialog View tab. Could you add a screenshot of this dialog on you system?

**Comment by truebucha** [comment]
When I choose preferences
<img width="198" alt="Screenshot 2021-11-24 at 10 29 46" src="https://user-images.githubusercontent.com/16370048/143211754-135e817f-1be3-4de9-9aeb-e14181026626.png">
I see this window
<img width="969" alt="Screenshot 2021-11-24 at 10 27 23" src="https://user-images.githubusercontent.com/16370048/143211626-8518128a-51a2-44b8-83ab-f9ebbbc1d1d3.png">

**Comment by variar** [comment]
Oh, looks like MacOs chooses wrong dialog to show as a preferences.

**Comment by truebucha** [comment]
No, only tools
<img width="174" alt="Screenshot 2021-11-30 at 11 23 38" src="https://user-images.githubusercontent.com/16370048/144029873-86058395-430a-420b-969b-020eba12dbbd.png">
s

**Comment by variar** [comment]
That's even worse than I thought :(. I have a fix but can't create a build because of some issues with code signing in my github actions pipeline. Working on it...

**Comment by EngleVV** [comment]
Command+mouse wheel can change font size, it works for me.

**Comment by variar** [comment]
I've managed to solve codesigning issues on Mac. Could you try new release from dev https://github.com/variar/klogg/releases/tag/continuous-osx?

**Comment by variar** [comment]
> Command+mouse wheel can change font size, it works for me.

Thanks @EngleVV! Completely forgot about that workaround :)

**Comment by truebucha** [comment]
> I've managed to solve codesigning issues on Mac. Could you try new release from dev https://github.com/variar/klogg/releases/tag/continuous-osx?

It woks as Expected! Thank you guys!
