### ISSUE TITLE
issue with Combining search

### ISSUE THREAD

**Issue by mmarkowski437** [variar/klogg#429]
https://klogg.filimonov.dev/docs/news/boolean_combination/
this feaure doesn't work with me.

The only way I was able to use it was to make this search
`(.*) and (.*)`
I assumed  this will mark every line, but that is not a case. It shows every 3 lines.

For example if I do this
`(.*1.*) and (.*)`
I get 0 results and I have a lot of 1 in logs.

Does this feature even work ?
If it does can you share some working examples ?

even better example is 
(1) works
(1) and (1) doesn't
"1" and "1" doesn't
(1) and (2) doesn't

This looks like amazing feature, I'd love to know how to use it.

**Comment by variar** [comment]
Hi, that is indeed a poorly documented feature. Recent dev build has more descriptive error messages. The patterns in this mode must be enclosed in `"`, so `"1" and "1"` should work. `()` can be used to combine complex logic expressions.

https://user-images.githubusercontent.com/1620716/142937664-d2abef7f-57a7-450a-bfb1-433c8b538be3.mp4

.

**Comment by mmarkowski437** [comment]
@variar it doesn't work for me. it don't know how its done, I get same result as before.

can you show example how you select year, month, day. something like (2021) and (-11)  and (-24) ?
from log 
2021-11-24 info

I get 0 results.

**Comment by mmarkowski437** [comment]
I get it now, I have version from scoop and I need development version.
Website doesn't tell in what version this was added in. I assumed it was old feature.

**Comment by variar** [comment]
Oh, my bad. I should have asked about the version you are using. I'll try to mention correct version in future site news.
