### ISSUE TITLE
How to change global background color and text color?

### ISSUE THREAD

**Issue by speeeeed** [variar/klogg#430]
I am using klogg 21.09.0.1165 on Windows 11.  The built-in dark style is not looking good on Windows. So I want to customize the background color and text color of the main log view, but I cannot find the setting entry, is this feature supported now?

By the way, thanks for your great work!

**Comment by variar** [comment]
Thanks. Unfortunately, the colors for dark theme are hardcoded. I can make klogg read them from configuration file, that will allow some experiments with colors

**Comment by variar** [comment]
Starting from 21.12.0.1175 the dark palette colors are read from configuration file `klogg.conf`. Default colors are:
```
[dark]
ActiveButton=#303030
AlternateBase=#353535
Base=#282828
Button=#353535
ButtonText=#FFFFFF
DisabledButtonText=#757575
DisabledLight=#353535
DisabledText=#808080
DisabledWindowText=#808080
Highlight=#2a82da
HighlightedText=#212121
Link=#2a82da
Text=#FFFFFF
ToolTipBase=#2a82da
ToolTipText=#FFFFFF
Window=#353535
WindowText=#FFFFFF
```

If some color is not specified in configuration then the default will be used. To make colors appear in configuration file for the first time you need to change some settings to make klogg write changes to the file.

**Comment by PetbkA** [comment]
@variar
**21.12.0.1175 x64 on Windows 10 version 1809 LTSC x64** - thanks for this! Unfortunately, I don't see klogg.**conf** file neither in installation path nor in `%AppData%` - only klogg.**ini** in the latter, but it doesn't contain the mentioned parameters

**Comment by variar** [comment]
Try adding section with colors from previous comments to `klogg.ini` manually.

**Comment by PetbkA** [comment]
**21.02.0.1192 x64** - indeed, editing INI file changes the colors. [Works like charm](https://user-images.githubusercontent.com/22843816/151922779-09de4344-90e7-49bc-8061-b634ab392f10.png)! Thank you!

But it seems that not all of the UI elements are changing their colors after first restart. For example, I've changed all #303030 colors to #101010, but some elements, e.g. background of menu toolbar, were still in this color after restarting. Then I've changed `DisabledButtonText` and `DisabledLight` colors to #101010 too and suddenly menu toolbar changed its color to #101010. But when I reverted tha latter parameters to their default values and restarted klogg, nothing has changed, so I guess there was some "lag" in applying colors to all UI elements

**Comment by PetbkA** [comment]
Ooops, sorry, it seems that I was just in a hurry. Reconfigured color scheme from the default values again, and everything's fine and clear :)

**Comment by variar** [comment]
Closing this for this milestone. Feel free to create a new issue for left sidebar

**Comment by ashishsawant4u** [comment]
How do we change color in mac for klogg
