### ISSUE TITLE
Feature request: encoding auto detection can be disabled

### ISSUE THREAD

**Issue by xaljer** [variar/klogg#431]
I only use UTF-8 encoding log file, but I found that some log file may be detected as other encoding. Since UTF-8 has fast-path of searching, I need change it manually.
So it would be better to provide an option to disable the auto detection.

**Comment by variar** [comment]
I was thinking to add this but didn't have time to work on klogg for a while.

**Comment by variar** [comment]
I've added an option to set deafult encoding for new files, it should be in `File` tab in 21.12.0.1174.
