### ISSUE TITLE
[Search Results]: add "Copy with line numbers" option

### ISSUE THREAD

**Issue by PetbkA** [variar/klogg#434]
Lines from search results are copied without line numbers. It would be nice to have such option (may be with customizable hotkey, e.g. Ctrl + Shift + C).

Preferrable output is like in Notepad++: `Line <LineNum>:<Space><Line>`

Don't know if it'll be useful to also copy file path

**Comment by variar** [comment]
Great idea! I've added it to a backlog.

**Comment by variar** [comment]
Should be in 23.06
