### ISSUE TITLE
Soft-wrap opened files

### ISSUE THREAD

**Issue by davideboschetto** [variar/klogg#437]
Details for the issue
--------------------

#### What did you do?
Opened a pandas dataframe exported to json format

#### What did you expect to see?
Line wrapping

#### What did you see instead?
One huge line

Useful extra information
-------------------------
> Klogg version 20.12.0.813 (built on 2020-12-24 from commit 576b91d) [built for x86_64-little_endian-llp64]
> running on Windows 10 Version 1809 (winnt/10.0.17763) [x86_64]
> and Qt 5.15.2

**Comment by variar** [comment]
Yes, that's a feature that should be there. There's a request for it #99. However, not easy to implement.

**Comment by variar** [comment]
Closing as duplicate
