### ISSUE TITLE
Multiple line selection not possible via keyboard

### ISSUE THREAD

**Issue by Max1234-Ita** [variar/klogg#441]
Details for the issue
--------------------
A user should be able to select a range of text lines by clicking the first one with his/her mouse and then extending the selection to the lines below/above by holding down the Shift key and pressing the corresponding cursor key (Down/Up).

This should happen in both the upper and lower text pane.

#### What did you do?
Inside a text pane, I selected a line, then pressed Shift+Cursor Down in order to extend the selection.

#### What did you expect to see?
Selection should have extended, including the line I clicked before and the one below.

#### What did you see instead?
Selection did not change.

-------------------------
Useful extra information
-------------------------
> Klogg version 21.12.0.1188 (built on 2021-12-19 from commit 3efcf69) [built for x86_64-little_endian-llp64]
> running on Windows 10 Version 1909 (winnt/10.0.18363) [x86_64]
> and Qt 5.15.2

**Comment by variar** [comment]
Should be better in 23.06 builds
