### ISSUE TITLE
crashed to open 1G file

### ISSUE THREAD

**Issue by xuayan-nokia** [variar/klogg#442]
Details for the issue
--------------------

#### What did you do?

-------------------------
Crash id
4244a5ca-c4e2-4c3f-8463-596fc3df377c
-------------------------
Useful extra information
-------------------------
> Klogg version 20.12.0.813 (built from commit 576b91d) [built for x86_64-little_endian-lp64]
> running on Ubuntu 18.04.6 LTS (linux/5.4.0-86-generic) [x86_64]
> and Qt 5.9.5

**Comment by variar** [comment]
Please try latest 21.12 builds. They should be more stable compared to 20.12. I'm going to make a new stable release as soon as documentation is ready.
