### ISSUE TITLE
On Ubuntu File menu is disappeared when multifile files opened

### ISSUE THREAD

**Issue by adlingepa** [variar/klogg#443]

**Comment by variar** [comment]
Hi, @adlingepa  could you make a screenshot of the problem? And which version of klogg are you using?

**Comment by adlingepa** [comment]
@variar  Thanks for attention, I am using klogg build 21.12.0.1191
Also attaching the screenshot of problem.

![image](https://user-images.githubusercontent.com/32295474/152431245-f6e27805-ebbf-421f-b10a-563a4954ba53.png)

**Comment by variar** [comment]
Thanks for the screenshot. Which Ubuntu version are you using? I'll try to get a virtual machine with it installed.

**Comment by rcaimi** [comment]
Hi, I noticed it recently too...

I'm on 20.04.1-Ubuntu

I moved my content of ~/.config/klogg and opened it, this is the result:

![image](https://github.com/variar/klogg/assets/22914221/f7ab43be-48ab-41dd-895f-cd2ef626bf41)

Best regards

**Comment by rcaimi** [comment]
Just found out that this is happening with another programs, so it does not seem to be a klogg issue!

My LibreOffice has the same problem.. Found no fix yet...

Thanks

**Comment by variar** [comment]
Good to know! Thank you for sharing.
