### ISSUE TITLE
Crash report (automatically generated) 

### ISSUE THREAD

**Issue by afarah1** [variar/klogg#446]
Details for the issue
--------------------

#### What did you do?

Opened a file. I cannot attach the file as it contains sensitive information.

-------------------------
Crash id
0609aa05-e6f7-4d5f-847f-b0b65f01316d
-------------------------
Useful extra information
-------------------------
> Klogg version 20.12.0.813 (built from commit 576b91d) [built for x86_64-little_endian-llp64]
> running on Windows 10 Version 2009 (winnt/10.0.19043) [x86_64]
> and Qt 5.15.2

**Comment by variar** [comment]
Please try recent dev builds, they should be stable enough for most use-cases

**Comment by variar** [comment]
Not enough info to investigate the root cause
