### ISSUE TITLE
Text selection using mouse drag does not work properly when it contains 2-byte characters

### ISSUE THREAD

**Issue by GW-Kang** [variar/klogg#448]
Details for the issue
--------------------

#### What did you do?
I tried to select text using Mouse Drag in a document containing 2-byte characters.

#### What did you expect to see?
Characters from the start position to the end position of Mouse Drag must be selected accurately.

#### What did you see instead?
If you refer to the attached screenshots, you can see that the selected character is quite inaccurate.
It doesn't seem to handle that 2-byte characters are wider than 1-byte characters.

Useful extra information
-------------------------
> Klogg version 20.12.0.813 (built on 2020-12-24 from commit 576b91d) [built for x86_64-little_endian-llp64]
> running on Windows 10 Version 2009 (winnt/10.0.19044) [x86_64]
> and Qt 5.15.
[EUC-KR encoded 2-byte chars.Log](https://github.com/variar/klogg/files/8001147/EUC-KR.encoded.2-byte.chars.Log)
[UTF-8 encoded 2-byte chars.Log](https://github.com/variar/klogg/files/8001148/UTF-8.encoded.2-byte.chars.Log)
![Before select](https://user-images.githubusercontent.com/35767468/152495337-193a764e-2945-4927-83eb-449342884ff7.png)
![Error after select 1](https://user-images.githubusercontent.com/35767468/152495349-1b2e780e-cd19-4142-a815-79a0b5d5f700.png)
![Error after select 2](https://user-images.githubusercontent.com/35767468/152495359-dcaf4e7b-3415-4abc-9fa0-7d9f04266f57.png)
2

**Comment by variar** [comment]
Try using latest dev builds. They should be stable enough and have some fixes for multibyte encodings.

**Comment by GW-Kang** [comment]
I installed and tested klogg-21.02.0.1192-x64-setup.exe and it seems to work perfectly.
