### ISSUE TITLE
Crash id 630eb906-1607-4021-ad7e-b17c5d6c13b0

### ISSUE THREAD

**Issue by Hesamp** [variar/klogg#450]
Details for the issue
--------------------

just click to open

-------------------------
Crash id
630eb906-1607-4021-ad7e-b17c5d6c13b0
-------------------------
Useful extra information
-------------------------
> Klogg version 20.12.0.813 (built from commit 576b91d) [built for x86_64-little_endian-llp64]
> running on Windows Server 2016 Version 1809 (winnt/10.0.17763) [x86_64]
> and Qt 5.15.2

**Comment by variar** [comment]
Looks like klogg crashed at exit and on next start could not show crash reporting dialog. Could you try latest pre-release?
