### ISSUE TITLE
Need option in klogg to set font size to weight to 15 and 16

### ISSUE THREAD

**Issue by ciscohack** [variar/klogg#453]
Hi Team,

First thanks for such a great tool but can you please add option to increase font size weight to 15 or 16 or 17 and we should also have to add option for font facetype(regular/medium/bold/semibod). currently it follow font size like 10/11/12/14  but for my screen 18 is too big and 14 is too small and it's good to have such basic options. Thanks

**Comment by variar** [comment]
Available font sizes are reported by Qt and are different for each font family. I'll add additional sizes between 10 and 20, but they might not work as expected for some fonts.

**Comment by ciscohack** [comment]
Thanks

**Comment by variar** [comment]
Should be available in 22.04.0.1216+

**Comment by ciscohack** [comment]
> Should be available in 22.04.0.1216+

Give one thanks

**Comment by variar** [comment]
Seems to be working fine
