### ISSUE TITLE
logs

### ISSUE THREAD

**Issue by JaimeNA03** [variar/klogg#455]
Details for the issue
--------------------

#### What did you do?

-------------------------
Exception:
PartialIndexOperation failed: invalid vector subscript
-------------------------
Useful extra information
-------------------------
> Klogg version 22.02.0.1199 (built on 2022-02-20 from commit 4e40303) [built for x86_64-little_endian-llp64]
> running on Windows 10 Version 2009 (winnt/10.0.19044) [x86_64]
> and Qt 5.15.2

**Comment by variar** [comment]
Thanks for reporting this. Looks like the same issue as #451 Will track progress there
