### ISSUE TITLE
QuickFind Ignore case setting is not preserved from one run to the next

### ISSUE THREAD

**Issue by drventure** [variar/klogg#461]
Details for the issue
--------------------

#### What did you do?
Press Control-F to open the Quickfind

#### What did you expect to see?
The Ignore case option setting isn't preserved from one run to the next of KLOGG

Alternately, would be good to have a setting to control the default initial state of that setting, but I believe it'd be better to just remember the last state the user left it it.

That seems to happen during a single run of the app.

#### What did you see instead?
Each time you run KLOGG, the Ignore case option resets to OFF.

-------------------------
Useful extra information
-------------------------
> Klogg version 21.09.0.1165 (built on 2021-09-27 from commit 9fade8b) [built for x86_64-little_endian-llp64]
> running on Windows 10 Version 1909 (winnt/10.0.18363) [x86_64]
> and Qt 5.15.2

**Comment by variar** [comment]
Thanks! I don't really use quickfind that much myself. I agree that quickfind case sensitivity should be preserved in the same way as all optios for regex search.

**Comment by variar** [comment]
Saving ignore case option should work fine in 22.04.0.1216+

**Comment by drventure** [comment]
Awesome!

Thanks for having a look at that

Darin

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
