### ISSUE TITLE
QuickFind is really slow -- try switching to hyperscan

### ISSUE THREAD

**Issue by drventure** [variar/klogg#462]
Details for the issue
--------------------

#### What did you do?
Perform a quick find on a large-ish (say 20mb) file.

#### What did you expect to see?
The match search in Regexp mode is virtually instantaneous. The matched lines show up in the search results almost instantly.

However, perform a Quickfind in the same file to find a line toward the middle of the file, and it takes several (as in around 7) seconds. Doesn't make any sense. I've tried quickfind in plain text and Regexp mode, same delay. Whereas regular match search is very fast (using the hyperscan option anyway, haven't messed with the QT option).

#### What did you see instead?
The QuickFind search takes +seconds+ to perform, whereas the normal match search is almost instant

-------------------------
Useful extra information
-------------------------
> Klogg version 21.09.0.1165 (built on 2021-09-27 from commit 9fade8b) [built for x86_64-little_endian-llp64]
> running on Windows 10 Version 1909 (winnt/10.0.18363) [x86_64]
> and Qt 5.15.2

**Comment by variar** [comment]
Thanks for reporting this. Quickfind uses Qt regular expressions engine. Hyperscan is not that great in reporting the exact region that caused the match and needs to be highlighed. For the highlighers klogg repeats search with Qt only in visible area and uses that to do the colorization. This is not the case for quickfind. However, I think that the same trick can be used for this case. I've renamed the issue accordingly

**Comment by variar** [comment]
It turned out that hyperscan for quickfind was already mentioned in #326. Will close this one.

**Comment by drventure** [comment]
Sounds good. I'll watch that other ticket then. Thanks!
