### ISSUE TITLE
Klogg crashed on file reading

### ISSUE THREAD

**Issue by kindacute** [variar/klogg#466]
Details for the issue
--------------------

With enabled polling and opened file for reading, started to write into file.

-------------------------
Exception:
PartialIndexOperation failed: vector
-------------------------
Useful extra information
-------------------------
> Klogg version 22.04.0.1216 (built on 2022-04-16 from commit 45dc027) [built for x86_64-little_endian-lp64]
> running on macOS 12.3 (darwin/21.4.0) [x86_64]
> and Qt 5.15.2

**Comment by variar** [comment]
Thank for reporting this. That exception looks familiar, but I can't reproduce it in my Linux or Windows environments. I'll try to reproduce it in mac vm.

**Comment by variar** [comment]
That is the same as #451, adds more reproduction steps. Let's track the issue in that ticket.
