### ISSUE TITLE
Multiple file open

### ISSUE THREAD

**Issue by ShapedTime** [variar/klogg#469]
Details for the issue
--------------------

#### What did you do?
I selected 7 files each around 200MB and opened them at once with klogg which resulted in error.

-------------------------
Crash id
1ac5698f-fb08-4c78-89e9-b09e86c21770
-------------------------
Useful extra information
-------------------------
> Klogg version 20.12.0.813 (built from commit 576b91d) [built for x86_64-little_endian-llp64]
> running on Windows 10 Version 2009 (winnt/10.0.19042) [x86_64]
> and Qt 5.15.2

**Comment by variar** [comment]
This looks like issue https://github.com/variar/klogg/issues/329 and should be fixed in current dev builds. Please try to use the new build -- https://github.com/variar/klogg/releases/tag/continuous-win
