### ISSUE TITLE
Search for selected text keyboard shortcuts don't seem to be working

### ISSUE THREAD

**Issue by pabloh84** [variar/klogg#470]
Details for the issue
--------------------

#### What did you do?

- Select any text
- Press any of:
--- \* or . to search for the next occurrence of the currently selected text 
--- / or , to search for the previous occurrence of the currently selected text 
 
#### What did you expect to see?
In released version, all occurrences of selected text where highlighted and you could move up and down using the shortcuts

#### What did you see instead?
No text is highlighted and shortcuts don't seem to be working. 
They don't work even after performing a search with "Ctrl+F"

-------------------------
Useful extra information
-------------------------
> Klogg version 22.04.0.1234 (built on 2022-04-26 from commit ) [built for x86_64-little_endian-lp64]
> running on Ubuntu 21.10 (linux/5.13.0-40-generic) [x86_64]
> and Qt 5.9.5
> Spanish keyboard layout

**Comment by variar** [comment]
Thank you for reporting this! Could you check what shortcuts are configured for these actions in settings dialog? By default it should be like this:
![image](https://user-images.githubusercontent.com/1620716/165367486-319d18c6-a6ed-4c86-a60e-8c29e2fc5a9c.png)

**Comment by pabloh84** [comment]
Same as in your screenshot: 

![image](https://user-images.githubusercontent.com/7147388/165368174-9a12de0b-e018-4c14-82b6-e0fa022ed4c2.png)

I've tried resetting them, both to the same and to different keys. For example:

![image](https://user-images.githubusercontent.com/7147388/165368924-169bf1ac-5a7e-46a2-acd8-f005b9a6c520.png)

**Still not working**

As an additional note I already did notice this with previous build (klogg-22.04.0.1220-x86_64) but didn't report at the time hoping it would be temporary error, these being pre-release builds and all.

**Comment by pabloh84** [comment]
I've realized that it's not only those the shortcut not workings, those are simply the ones I use the most. I've tested all documented. Most of them are not working

### **Not working**
- Arrows: **Not working**
- G jump to the first line of the file (selecting it) : **Not working**
- Shift+G  jump to the last line of the file (selecting it) **Not working**
- Alt+G show jump to line dialog **Not working**
- ' or " start a quickfind search in the current screen **Not working**
- n or N repeat the previous quickfind search forward/backward **Not working**
- m put a mark on current selected line **Not working**
- \[ or \] jump to previous or next marked line **Not working**
- + or - decrease/increase filtered view size **Not working**
- v switch filtered view visibility mode  (Marks and Matches -> Marks -> Matches) **Not working**

### **Working** 

- f activate 'follow' mode, which keep the display as the tail of the **Working** 
- F5 reload current file **Working**
- Ctrl+S Set focus to search string edit box **Working**
- Ctrl+Shift+O Open dialog to switch to another file **Working**

**Comment by variar** [comment]
Thanks for more testing. Unfortunately, I can't reproduce the problem, so we'll have to dig deeper. Could you enable logging, then restart klogg, try some shortcuts and attach the logs here? What desktop environment are you using? Is it X11 or Wayland session? 

It seems unlikely to help but could you try en layout?

**Comment by pabloh84** [comment]
Sorry for the delay. Please find attached requested logs:
[klogg_debug.log](https://github.com/variar/klogg/files/8580843/klogg_debug.log)

I am using GNOME under X11

I have tried switching to EN keyboard layout and the problem persists

**Comment by pabloh84** [comment]
I can confirm the previous comment to some extent.. I've installed from deb package and the issue does not reproduce.

**Comment by pabloh84** [comment]
Qt 5.15.2 obtained from Ubuntu package manager.

This morning I've updated to 22.04 and Qt has been updated to 5.15.3. Installation from deb package is still working.

**Comment by variar** [comment]
I've changed the proces of creating packages. AppImage is now built with Qt 5.15 and hotkeys seem to be working fine.

**Comment by pabloh84** [comment]
Fixed! I've just tested and it works! Great job! 

The only thing I've encountered is that Ubuntu 22.04 has moved away from FUSE2 into FUSE3 and therefore you need to install the necessary package to enable compatibility with FUSE2. 

`sudo apt install libfuse2`

As indicated by this link from the official appimage documentation: https://docs.appimage.org/user-guide/troubleshooting/fuse.html#setting-up-fuse-2-x-alongside-of-fuse-3-x-on-recent-ubuntu-22-04-debian-and-their-derivatives

You may want to address it in documentation or in your release notes

**Comment by variar** [comment]
Thanks @pabloh84!  I could probably build AppImages for each Ubuntu LTS release. If I understand the docs correctly, the AppImage built on 22.04 will be using fuse3 and thus users won't have to do anything. CI uses docker containers to build packages for Linux, adding one more build configuration should be relatively easy.  However, testing all of the packages will require more work.

**Comment by pabloh84** [comment]
As you see fit. 

My guess is that for the time being installing the package could be acceptable since its only a few extra KB. 

Another matter would be if at some point some future release discontinues compatibility with fuse2 but I don't think that will happen in the foreseeable future since it would break lot's of AppImage overnight 

Thanks again for taking a look into this issue and for the great maintaining with this tool.

**Comment by variar** [comment]
Building appimage for 22.04 proved to be more difficult than expected. I've updated documentation.
