### ISSUE TITLE
Search result is incorrect when there are many null chars in a line

### ISSUE THREAD

**Issue by onionhead0708** [variar/klogg#471]
Issue: Accidentally my program generated a log with many null characters in a line, and using the klogg to search, the matched lines shown in the result panel give an incorrect result. I used back the glogg and have no problem on that. 

Following is the screen cap of the issue:
![image](https://user-images.githubusercontent.com/3008619/166459667-da220ac0-b762-4ff4-aaad-ccf04ef19a48.png)

Following is the log files that i used for reproducing the issue:
[test_log.zip](https://github.com/variar/klogg/files/8610666/test_log.zip)

Version of klogg: 22.04.0.1234
OS: Windows 10

**Comment by variar** [comment]
Thanks for reporting. Caused by attempt to fix #459

**Comment by variar** [comment]
I've reverted a commit which tried to skip big ranges of null characters. Search works as expected with the test file.
