### ISSUE TITLE
cash when deleting large number of lines

### ISSUE THREAD

**Issue by hardik-desai-kcl** [variar/klogg#474]
Details for the issue
--------------------

#### What did you do?
selected around 3m lines and press delete button it crashed immediately 

-------------------------
Crash id
64d3eead-523e-45ed-ab31-c5721d00b02f
-------------------------
Useful extra information
-------------------------
> Klogg version 20.12.0.813 (built from commit 576b91d) [built for x86_64-little_endian-llp64]
> running on Windows 10 Version 2009 (winnt/10.0.19044) [x86_64]
> and Qt 5.15.2

**Comment by variar** [comment]
Thanks for the report. Could you provide some more details? Klogg doesn't support any file editing. Are you trying to view file in klogg and use some other editor to delete lines from it?

If the issue can be easily reproduced, please try latest builds: https://github.com/variar/klogg/releases/tag/continuous-win
