### ISSUE TITLE
My laptop crashed and klogg displayed an error report after I started it again

### ISSUE THREAD

**Issue by MGelbana-Incorta** [variar/klogg#475]
Details for the issue
--------------------

#### What did you do?
My laptop crashed and I just restarted it.

-------------------------
Crash id
e024afb7-9e7a-43c8-8df0-5e8d8f4eadff
-------------------------
Useful extra information
-------------------------
> Klogg version 20.12.0.813 (built from commit 576b91d) [built for x86_64-little_endian-lp64]
> running on Ubuntu 20.04.4 LTS (linux/5.13.0-41-generic) [x86_64]
> and Qt 5.12.8

**Comment by variar** [comment]
Thanks for reporting this. Klogg 20.12 has several known crash issues. This looked like one of them. Should be fixed in next release.
