### ISSUE TITLE
Current CPU is not supported. SSE2 and SSSE3 are required.

### ISSUE THREAD

**Issue by avmaksimov** [variar/klogg#476]
Unfortunately, I can't use your program due this incompatibility. But CPU-Z show that my processor has this ability.

BTW, I see the mistake (SSSE3).

![image](https://user-images.githubusercontent.com/2793938/170835700-c8030c4b-b2fc-4cf0-9173-7b3628e1cf7a.png)

**Comment by avmaksimov** [comment]
I mean this release: https://github.com/variar/klogg/releases/tag/continuous-win

Ver 20.12 works good with it.

**Comment by variar** [comment]
Hi, thanks for reporting this. Klogg has switched to [hyperscan](hyperscan.io) regular expression matching engine. This library requires  CPU with support for  [Supplemental Streaming SIMD Extensions 3 (SSSE3)](https://en.m.wikipedia.org/wiki/SSSE3) instructions. AMD 'barcelona' based processors do not support these. 

You can try using latest build for x86 (32-bit) as it doesn't use hyperscan. Should work fine unless you have huge log files. 

I'll consider building a separate package for 64-bit without hyperscan. My main concern is that having too many package variants will be confusing for users.

**Comment by avmaksimov** [comment]
Thank you. I'll try later. I respect your position but may be better to give an option to choose regex core in the App? And if my processor can't work with hyperscan, the program has to be change the option to another and write the explanation.

**Comment by avmaksimov** [comment]
Thank you. It works fine!
