### ISSUE TITLE
Cannot compile klogg from sources on Mac OS Monterey 12.4 with Qt6

### ISSUE THREAD

**Issue by kindacute** [variar/klogg#481]
Compilation is not possible using Qt6 on Mac OS Monterey:

 In file included from /Users/user/Downloads/klogg/klogg/src/ui/src/optionsdialog.cpp:46:
 /Users/user/Downloads/klogg/klogg/src/ui/include/fontutils.h:34:23: error: 'QFontDatabase' is deprecated: Call the static functions instead [-Werror,-Wdeprecated-declarations]
         QFontDatabase database;
                       ^
 /usr/local/Cellar/qt/6.3.0/lib/QtGui.framework/Headers/qfontdatabase.h:113:5: note: 'QFontDatabase' has been explicitly marked deprecated here
     QT_DEPRECATED_VERSION_X_6_0("Call the static functions instead") explicit QFontDatabase() = default;
     ^
 /usr/local/Cellar/qt/6.3.0/lib/QtCore.framework/Headers/qglobal.h:423:44: note: expanded from macro 'QT_DEPRECATED_VERSION_X_6_0'
 define QT_DEPRECATED_VERSION_X_6_0(text) QT_DEPRECATED_X(text)
                                            ^
 /usr/local/Cellar/qt/6.3.0/lib/QtCore.framework/Headers/qglobal.h:335:33: note: expanded from macro 'QT_DEPRECATED_X'
  define QT_DEPRECATED_X(text) Q_DECL_DEPRECATED_X(text)
                                 ^
 /usr/local/Cellar/qt/6.3.0/lib/QtCore.framework/Headers/qcompilerdetection.h:1111:36: note: expanded from macro 'Q_DECL_DEPRECATED_X'
  define Q_DECL_DEPRECATED_X(x) [[deprecated(x)]]
                                    ^
 In file included from /Users/maksim.belinskiy/Downloads/klogg/klogg/src/ui/src/optionsdialog.cpp:46:
 /Users/maksim.belinskiy/Downloads/klogg/klogg/src/ui/include/fontutils.h:49:23: error: 'QFontDatabase' is deprecated: Call the static functions instead [-Werror,-Wdeprecated-declarations]
         QFontDatabase database;
                       ^
 /usr/local/Cellar/qt/6.3.0/lib/QtGui.framework/Headers/qfontdatabase.h:113:5: note: 'QFontDatabase' has been explicitly marked deprecated here
     QT_DEPRECATED_VERSION_X_6_0("Call the static functions instead") explicit QFontDatabase() = default;
     ^
 /usr/local/Cellar/qt/6.3.0/lib/QtCore.framework/Headers/qglobal.h:423:44: note: expanded from macro 'QT_DEPRECATED_VERSION_X_6_0'
  define QT_DEPRECATED_VERSION_X_6_0(text) QT_DEPRECATED_X(text)
                                            ^
 /usr/local/Cellar/qt/6.3.0/lib/QtCore.framework/Headers/qglobal.h:335:33: note: expanded from macro 'QT_DEPRECATED_X'
   define QT_DEPRECATED_X(text) Q_DECL_DEPRECATED_X(text)
                                 ^
 /usr/local/Cellar/qt/6.3.0/lib/QtCore.framework/Headers/qcompilerdetection.h:1111:36: note: expanded from macro 'Q_DECL_DEPRECATED_X'
   define Q_DECL_DEPRECATED_X(x) [[deprecated(x)]]
                                    ^
 2 errors generated.
 [538/584] Building CXX object src/ui/CMakeFiles/klogg_ui.dir/src/mainwindow.cpp.o
 ninja: build stopped: subcommand failed.

**Comment by variar** [comment]
Thanks! Looks like `QFontDatabase` constructor is deprecated now. Should be easy to fix. 
Meanwhile you can try setting cmake option `WARNINGS_AS_ERRORS` to OFF. This should allow to get more things compiling. I'm very interested to know if it builds :) I did some basic Qt6 support for Linux but never tried building on other systems.

**Comment by variar** [comment]
QFontDatabase usage is fixed with ugly #Ifdefs. 
As for linking error, klogg will now by default rely on cmake to figure out macOS version. As far as I know usually it uses build host version.  It is possible to override macOS target with cmake option `KLOGG_OSX_DEPLOYMENT_TARGET`

**Comment by variar** [comment]
@kindacute thank you for the inspiration! I've added MacOS Qt build to CI workflow to avoid breaking build in future.

**Comment by kindacute** [comment]
Klogg compiled successfully from sources. You may close the issue. 
I will test packages tomorrow
