### ISSUE TITLE
Cannot install latest package (klogg-22.06.0.1269-focal.deb) in Ubuntu 22.04 due to unmet dependencies

### ISSUE THREAD

**Issue by pabloh84** [variar/klogg#483]
Hello, 

It seems that some dependencies have change and I cannot install latest [continous-linux](https://github.com/variar/klogg/releases/tag/continuous-linux) release klogg-22.06.0.1269-focal.deb in Ubuntu 22.04 (Jammy Jellyfish)

Previous installed package (klogg-22.05.0.1243-focal.deb) installed seamlessly
### Error log:
<pre><font color="#26A269"><b>pablo@pablo-prestige</b></font>:<font color="#12488B"><b>~/apps/klogg</b></font>$ sudo apt install ./klogg-22.06.0.1269-focal.deb 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting &apos;klogg&apos; instead of &apos;./klogg-22.06.0.1269-focal.deb&apos;
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 klogg : Depends: libssl1.1 (&gt;= 1.1.0) but it is not installable
<font color="#C01C28"><b>E: </b></font>Unable to correct problems, you have held broken packages.
</pre>

### OS information:
<pre><font color="#26A269"><b>pablo@pablo-prestige</b></font>:<font color="#12488B"><b>~/apps/klogg</b></font>$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION=&quot;Ubuntu 22.04 LTS&quot;
<font color="#26A269"><b>pablo@pablo-prestige</b></font>:<font color="#12488B"><b>~/apps/klogg</b></font>$ cat /etc/os-release 
PRETTY_NAME=&quot;Ubuntu 22.04 LTS&quot;
NAME=&quot;Ubuntu&quot;
VERSION_ID=&quot;22.04&quot;
VERSION=&quot;22.04 LTS (Jammy Jellyfish)&quot;
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL=&quot;https://www.ubuntu.com/&quot;
SUPPORT_URL=&quot;https://help.ubuntu.com/&quot;
BUG_REPORT_URL=&quot;https://bugs.launchpad.net/ubuntu/&quot;
PRIVACY_POLICY_URL=&quot;https://www.ubuntu.com/legal/terms-and-policies/privacy-policy&quot;
UBUNTU_CODENAME=jammy
<font color="#26A269"><b>pablo@pablo-prestige</b></font>:<font color="#12488B"><b>~/apps/klogg</b></font>$ uname -a
Linux pablo-prestige 5.15.0-37-generic #39-Ubuntu SMP Wed Jun 1 19:16:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
</pre>

**Comment by variar** [comment]
Thanks! 22.04 switched to libssl3. And klogg started to be more precise with dependencies. I'm working on building a separate package for 22.04. The main blocker is a tool that generates debug symbols. For some reason it crashes on 22.04.

**Comment by pabloh84** [comment]
Ok, thanks! I'll be all ears for new releases

**Comment by variar** [comment]
@pabloh84 this should be fixed with build 22.06.0.1282. I've created a separate package for jammy.

**Comment by pabloh84** [comment]
Worked like a charm!! Many thanks!!

Tested with klogg-22.06.0.1282-jammy.deb
