### ISSUE TITLE
klogg UX text not scaling properly on Windows

### ISSUE THREAD

**Issue by bannus** [variar/klogg#485]
Details for the issue
--------------------

#### What did you do?
Open klogg on Windows machine with 3840x2400 display with scaling set to 300% (recommended default). Note: the automatic Windows version info below is wrong, I'm on Windows 11 21H2, build 22000.675.

#### What did you expect to see?
Text in klogg UX similarly sized to log file text.

#### What did you see instead?
Text in klogg UX tiny, nearly unreadable:

![image](https://user-images.githubusercontent.com/1330640/173602398-7f65e6cf-70ee-41fb-9b18-51460632be57.png)

-------------------------
Useful extra information
-------------------------
> Klogg version 22.06.0.1288 (built on 2022-06-12 from commit 4c53f67) [built for x86_64-little_endian-llp64]
> running on Windows 10 Version 2009 (winnt/10.0.22000) [x86_64], concurrency 8
> Qt 5.15.2, tbb 2021.7

**Comment by variar** [comment]
Thanks for reporting this. Qt5 is not that great with high dpi screens so there are some settings that could be changed by hand:
![image](https://user-images.githubusercontent.com/1620716/173613546-1f0f1130-c2ee-4e14-8775-3ff379cf716b.png)

Could you try them? Changes are applied after restart.

If that doesn't help try klogg build with Qt6, Qt6 has better high dpi support.

**Comment by bannus** [comment]
The "Enable Qt High DPI support" setting was already enabled for that screenshot (and "Scale rounding" was set to "Round"). I just tried the Qt6 build and the issue does not repro. Thanks for the tip!
