### ISSUE TITLE
"Report issue..." link is broken

### ISSUE THREAD

**Issue by bannus** [variar/klogg#486]
Details for the issue
--------------------

#### What did you do?
Hit Help > Report Issue...

#### What did you expect to see?
GitHub new issue page.

#### What did you see instead?
GitHub error page (500). I tried https://github.com/variar/klogg/issues/new?body=test which works but https://github.com/variar/klogg/issues/new?labels=type:%20bug does not, so it's probably related to permissions for labeling.

![image](https://user-images.githubusercontent.com/1330640/173604797-5e6c7bf3-2af0-47ff-b0a5-86293caa7f97.png)

-------------------------
Useful extra information
-------------------------
> Klogg version 22.06.0.1288 (built on 2022-06-12 from commit 4c53f67) [built for x86_64-little_endian-llp64]
> running on Windows 10 Version 2009 (winnt/10.0.22000) [x86_64], concurrency 8
> Qt 5.15.2, tbb 2021.7

**Comment by variar** [comment]
Thanks! Indeed now adding labels doesn't work for users without access to the project. Looks like I'll have to update release builds to fix that link.
