### ISSUE TITLE
Confusing end of line

### ISSUE THREAD

**Issue by castortech** [variar/klogg#489]
Just upgraded to 22.06 on Windows/QT6 and noticing a large gap on the right side of both the main view and filtered view. At first I even missed realizing that there was more text on the line as shown in the attached image between the blue lines. 

I know this is not major but would provide better feedback and show a bit more info as well.

Thanks
Alai
![Klogg gap](https://user-images.githubusercontent.com/85858/174805048-9d5203e4-750d-4a0e-aa69-41f7a386dfd5.PNG)
n

**Comment by ttimasdf** [comment]
+1, and Qt5 version has the same problem

**Comment by nowhszh** [comment]
This issue seems to have been fixed in the latest commit

**Comment by variar** [comment]
Should be fixed in 23.06.0.1479+
