### ISSUE TITLE
Scratchpad function Format Json does not handle Json arrays

### ISSUE THREAD

**Issue by FrankKlappe** [variar/klogg#490]
I tried formatting the following json:

[{"ReceiptLines": [{"LineNumber": 1}],"Description": ""}]

This results in:

{
    "Description": "",
    "ReceiptLines": [
        {
            "LineNumber": 1
        }
    ]
}

Expected:

[
  {
    "ReceiptLines": [
      {
        "LineNumber": 1
      }
    ],
    "Description": ""
  }
]

**Comment by variar** [comment]
Thanks for reporting this. That is a side effect of being able to process these text:
```
some date | log leve | {"ReceiptLines": [{"LineNumber": 1}],"Description": ""}
```
It looks for first valid json object and extracts it. So top level arrays are indeed broken.

**Comment by variar** [comment]
Can be tested in 23.06.0.1500+
