### ISSUE TITLE
[Qt6][Multiple Displays]: menu contents are always showing on the display where klogg was launched

### ISSUE THREAD

**Issue by PetbkA** [variar/klogg#498]
**OS:** Windows 10 LTSC 2021 (version 21H2) x64
**klogg:** 22.06.0.1288 x64

Recently I've received second display so I have [two](https://user-images.githubusercontent.com/22843816/179915615-1b5d32d3-7e33-43f7-a65f-a252af744421.png) now - left (1st and primary) and right (2nd).

Due to Windows problems, klogg is now always opening at the 2nd display, even if I'll close and reopen it on the 1st.

I'm always moving it to 1st after opening, but today I opened a menu and haven't seen it's contents. After some time I realised that they're always being shown at the 2nd display where klogg was started.

Here's the [video](https://user-images.githubusercontent.com/22843816/179916241-2e8aafcc-1828-4bbf-a61a-122a1ed2c8f7.mp4)

**Comment by PetbkA** [comment]
The problem isn't just with main menu - search hints and right click menus are affected too

**Comment by variar** [comment]
Hi, thanks for reporting this. It looks like some Qt issue. Are you using Qt5 or Qt6 build?

**Comment by PetbkA** [comment]
> Hi, thanks for reporting this. It looks like some Qt issue. Are you using Qt5 or Qt6 build?

Qt 6.2.4

**Comment by PetbkA** [comment]
**klogg-22.06.0.1289-Win-x64-Qt5 (Qt 5.15.2)** - Qt 5 is OK. Moreover, there's no problems with constant launch on the 2nd display - app launches on the one where it's been closed

**Comment by variar** [comment]
Thanks for testing this! I expected Qt6 to behave better in modern multimonitor environments. Maybe the next stable version of Qt will be fine. They did release Qt6.3, so Qt 6.2.4 defined as "LTS" will not be updated anymore for open source users, and  so I'll switch klogg ci builds to Qt 6.3 at some point.

**Comment by PetbkA** [comment]
**23.06.0.1518 x64 Qt6** - fixed
