### ISSUE TITLE
Help with importing highlighters

### ISSUE THREAD

**Issue by jima80525** [variar/klogg#499]
I sincerely apologize if I'm just missing something here.  I'm trying to create a set of highlighters for a team.  I've exported these to a file, but the exporter gives no hint as to what filename extension it wants.  I've tried just using a name in the hopes it would provide what it wanted for an extension, no luck.  (i.e. if I saved "fred", the file was just named "fred", not "fred.whatever_extension_means_highlighter")

When I go to import the highlighters, the file open dialog insists on only showing "Highlighters" - there is no option for "all files" or something similar.  It does not see the files I've saved. 

I'm certain there's a simple answer, and, again, I definitely feel like I'm missing something obvious, but I'm not seeing this in the documentation. 

I'm on ubuntu 20.04 using version 22.06.0.1289

Thanks for any help (I suspect the help will be "use this extension" which is perfect) and thanks for providing a great tool!

**Comment by variar** [comment]
Hi, sorry for confusion. Try adding `.conf` extension. I'll try to figure out why it is not added automatically during export.

**Comment by jima80525** [comment]
AWESOME!  Thanks for the quick response!  Works like a charm

**Comment by jima80525** [comment]
I'll  try to do a PR to add this to the documents :)

**Comment by Abay11** [comment]
Hi all,
I've done a little research. It should be the peculiarity of the native file dialogs on some systems.
Here is more information: https://stackoverflow.com/questions/9822177/is-there-a-way-to-automatically-add-extensions-to-a-file-using-qfiledialog-on-li

I've create a PR with fixes. https://github.com/variar/klogg/pull/536

**Comment by variar** [comment]
23.06 builds should behave better for this case
