### ISSUE TITLE
As glogg, automate Windows distro installation, use chocolatey

### ISSUE THREAD

**Issue by jeffjensen** [variar/klogg#50]
Using a choco installation makes installing updates automatic and painless (like yum/apt for Windows).

This is glogg's page: https://chocolatey.org/packages/glogg

**Comment by variar** [comment]
Thanks for the link. I'll definitely make a package for klogg after a stable release.

**Comment by variar** [comment]
I've submitted package to chocolatey. Waiting for moderators to approve it

**Comment by jeffjensen** [comment]
Fantastic!  Thank you very much... two of us have successfully installed and using Klogg via choco.

**Comment by variar** [comment]
Great news! Thanks for testing the package.

**Comment by variar** [comment]
Package has been approved. 
https://chocolatey.org/packages/klogg
