### ISSUE TITLE
[Shortcuts]: add hotkey to focus on the "main" search field

### ISSUE THREAD

**Issue by PetbkA** [variar/klogg#525]
**OS:** Windows 10 LTSC 2021 (version 21H2) EN
**Klogg:** 22.06.0.1289 x64

There's only hotkey for _Open Quick Find_, but no such for "main" search. It would be nice to have one

**Comment by variar** [comment]
I think there is a shortcut for this:
![image](https://user-images.githubusercontent.com/1620716/212417005-f4d006c2-aeab-4ccc-af69-1aa52370426b.png)

**Comment by PetbkA** [comment]
Indeed, sorry :)
