### ISSUE TITLE
Please add a button allowing to quickly clean up the Filter textbox

### ISSUE THREAD

**Issue by Max1234-Ita** [variar/klogg#544]
Not a bug, but a feature request:
I use a lot the string filtering feature , both with and without RegEx to analyse script execution logs. 

Unfortunately, when I need to type a new, different filter string, I have to manually select and delete the previous one.
It would be very useful to have a little button, i.e. to the right of the textbox, allowing to clean it up automatically on click. 

I think such a button would improve the usability. Can that be done? (please :-) ) 

Thanks in advance,
Max

![image](https://user-images.githubusercontent.com/15315381/198073976-080150a0-fc93-45f9-8515-4cdda9f51a72.png)

**Comment by PetbkA** [comment]
@Max1234-Ita 
Why don't you use `Ctrl+S` to focus on search text box? If I'm not mistaken, it'll select all text so you'll just type your new request - it'll replace the previous one.

UI button would be nice, of course, but it's a slower method than the above

**Comment by variar** [comment]
The button is there in 23.06 builds
