### ISSUE TITLE
sudden crash after open large log for a while

### ISSUE THREAD

**Issue by Yossarian0916** [variar/klogg#545]
Details for the issue
--------------------

#### What did you do?

-------------------------
Crash id:
5f31d190-85a8-48f9-98a2-6b495de6376b
-------------------------
Useful extra information
-------------------------
> Klogg version 22.06.0.1289 (built on 2022-06-14 from commit 6340d94) [built for x86_64-little_endian-llp64]
> running on Windows 10 Version 1809 (winnt/10.0.17763) [x86_64], concurrency 12
> Qt 5.15.2, tbb 2021.7

**Comment by variar** [comment]
Might be fixed in 23.07 builds after multiple fixes in large files handling.
