### ISSUE TITLE
Context menu always shown on primary monitor

### ISSUE THREAD

**Issue by PrimosK** [variar/klogg#547]
Details for the issue
--------------------

#### What did you do?
Just open up Klogg in dual monitor setup. Drag the Klogg window to non-primary monitor and try to open one of the menus (e.g. File).

#### What did you expect to see?
The menu to be opened below the menu item.

#### What did you see instead?
The menu being opened on primary monitor despite Klogg window is being shown in the second monitor.

Demonstration:
![dual-monitor](https://user-images.githubusercontent.com/1519324/226326391-2e131c2e-6901-4645-8a91-2aedb63d8ac3.gif)

Side note:
- on the left there is primary monitor
- on the right there is secondary monitor

Please let me know if any further information is needed.

-------------------------
Useful extra information
-------------------------
> Klogg version 22.06.0.1289 (built on 2022-06-14 from commit 6340d94) [built for x86_64-little_endian-llp64]
> running on Windows 10 Version 2009 (winnt/10.0.19045) [x86_64], concurrency 12
> Qt 6.2.4, tbb 2021.7

**Comment by PetbkA** [comment]
Same as #498, I guess

**Comment by variar** [comment]
Yes, most likely. I'll try to update Qt6 in CI and release new testing builds.

**Comment by variar** [comment]
I've updated Qt to 6.4 in CI builds. This might be fixed in https://github.com/variar/klogg/releases/tag/continuous-win

**Comment by nowhszh** [comment]
My colleague told me that this problem still exists in the windows platform Qt6 version of the application. This problem is very bad for the experience, but I don't have a suitable windows computer to solve this problem.

**Comment by variar** [comment]
I think I know how to fix it.

**Comment by nowhszh** [comment]
@variar  Thank you！ this fix is verified to work in Windows

**Comment by variar** [comment]
The same issue is #498.

**Comment by ecnepsnai** [comment]
This issue is still occurring for me on the latest release, but the opposite - klogg always opens on my secondary monitor, and context menus also open only on the secondary monitor.

**Comment by PetbkA** [comment]
> This issue is still occurring for me on the latest release

You are using latest *release*, i.e. [22.06.0.1289](https://github.com/variar/klogg/releases/tag/v22.06.0.1289) or the latest *continuous*, currently it's 23.0.1580?

#498 hasn't been fixed in *release*, try continuous instead. And specify your *klogg* version including architecture, OS and Qt version next time
