### ISSUE TITLE
LogFile clean up/removal

### ISSUE THREAD

**Issue by shvez** [variar/klogg#56]
Hi, there

I have some feature request.

As a developer, I do quite often one thing. I develop and try. During 'try' I check logs, then fix something try again and again check logs. In order to not be confused by old logs, I often either remove them or clean up files using notepad++. 

It would be good to have something like cleanup/clean up all in the application, maybe even with hotkeys, so that I could quickly clean up files and restart tests

Also, it would be good to have different close options when you click on the tab header

Thank you for good tool
best,
ilya

**Comment by variar** [comment]
Deleting contents of opened file is possible using "Clear file" from "Edit" menu. No hotkey yet. I'm thinking of refactoring hotkey and menu system to make toolbars and hotkeys configurable by user.

Closing all/all but this is on todo list for next release.

**Comment by shvez** [comment]
Thank you. good news

**Comment by variar** [comment]
Mentioned ui for hotkey configuration in #26. Everything else discussed here is in latest builds.
