### ISSUE TITLE
colors do not show up in the  (color label) context menu

### ISSUE THREAD

**Issue by burg1ar** [variar/klogg#569]
![image](https://github.com/variar/klogg/assets/3461895/27668a6b-ea91-4691-81c7-ee8639272b2e)

klogg version: klogg 22.06.0.1289
os: ubuntu 22.04

this seems to be a bug according to https://github.com/variar/klogg/issues/270

**Comment by variar** [comment]
Unfortunately, this seems to be a Qt 5 issue in Linux. For Qt6 it works fine, so I've enabled it for Qt6 builds

**Comment by nowhszh** [comment]
https://github.com/variar/klogg/blob/26b39ea5947085276fa4fc99ad00e727120d180e/src/ui/src/abstractlogview.cpp#L694-L701
I do not understand the problem, comment out lines 699 and 701, using Qt5.12 compile, the color display is normal

**Comment by nowhszh** [comment]
I will verify this again using branch tag v22.06.0.1289

**Comment by nowhszh** [comment]
@variar  https://github.com/variar/klogg/blob/f96f35d5e64fb2c07995d3b4c0193506eee9e9b4/src/ui/src/abstractlogview.cpp#L494-L501
The code in tag v22.06 only displays color icons in klogg for Windows platform. [`setIconVisibleInMenu`](https://doc.qt.io/qt-6/qaction.html#iconVisibleInMenu-prop) function was introduced in Qt4.4, I actually tested in Mac and Ubuntu are working properly, why is it enabled only in Windows?

**Comment by nowhszh** [comment]
> I will verify this again using branch tag v22.06

After commenting out the code it works fine

**Comment by variar** [comment]
There were some rendering issues with Qt5 and KDE setup. If I remember correctly there were black squares instead of colors. I can't reproduce it anymore, something in my system got updated and fixed the issue. I guess it could be enabled back on older versions of Qt.

**Comment by nowhszh** [comment]
@variar I also have no problems with multiple computers, and I also think I can re-enable

**Comment by variar** [comment]
Enabled for all builds in 23.06.0.1538+
