### ISSUE TITLE
Garbage characters are sometimes displayed

### ISSUE THREAD

**Issue by wiz0u** [variar/klogg#57]
With some files, klogg display garbage characters temporarily:
![image](https://user-images.githubusercontent.com/11647984/53229087-887cb280-3683-11e9-9545-67cfd9df4e5d.png)

It goes away and displays correctly when I scroll down or when the file is refreshed because some lines are added.
When the issue happens on a file, I can click on another file tab, then click back on this file tab and the garbage reappears consistently. (but only if I'm at the beginning of the file, it seems)

Notes: My log files are plain ASCII text file.
I have "Enable Polling" & "Keep file closed" enabled

**Comment by wiz0u** [comment]
Also note that my log files are on a network shared folder.

**Comment by wiz0u** [comment]
Some updates:
- the garbage only reappears when I switch to a specific 2nd file tab (not any files) then switch back to the 1st file
- after I copied the 2 offending log files on my local hard drive, the issue still happens, so it's not related to network shares.

**Comment by variar** [comment]
Thanks for report and excluding some possible reasons. I'll look into it as soon as possible

**Comment by variar** [comment]
Looks like thread_local  for compressed line storage cache was a mistake, as UI thread can use cache from one tab to draw lines in another.

**Comment by variar** [comment]
This bug might have been introduced in 66499b762357714c768736a36012e10e20762a75. Profiling data indicated that ThreadPrivateStore was slow to access and switching to c++ thread_local did improve performance. But after that a single instance of thread_local cache of last read line position was used for all files in UI thread. Usually after switching tabs the cache for ui thread became invalid and not reused. However, if opened files were somewhat similar, the cache from one tab might have been considered valid and reused, which resulted in garbage output.

Switching back to using one cache per file per thread should fix the issue. Now using Intel Threading Building Blocks for this, and performance seems to stay the same.

@wiz0u could you test build 19.3.0.369 if you still have files that produced garbage output?

**Comment by wiz0u** [comment]
I confirm the bug has disappeared with this build

**Comment by wiz0u** [comment]
BTW, could you put "About" below "About QT"? It's unusual for the "about this program" to not be the last item in the Help menu

**Comment by variar** [comment]
Thanks.

Move About to be last (should be in build >=19.03.0.379).
