### ISSUE TITLE
Building from AUR broken

### ISSUE THREAD

**Issue by Bodyash** [variar/klogg#570]
Half a year ago it was fine, but now I can't build klogg from AUR

https://gist.github.com/Bodyash/b273387809e35779a42bf1f5f7290022

CMake Error: The INTERFACE_QT_MAJOR_VERSION property of "Qt5::Core" does
not agree with the value of QT_MAJOR_VERSION already determined
for "klogg_ui".

CMake Error: The INTERFACE_QT_MAJOR_VERSION property of "Qt5::Core" does
not agree with the value of QT_MAJOR_VERSION already determined
for "klogg".

CMake Error: The INTERFACE_QT_MAJOR_VERSION property of "Qt5::Core" does
not agree with the value of QT_MAJOR_VERSION already determined
for "klogg_portable".

I have qt5-base and qt6-base installed.
That's the first problem.

Second problem - Forcing it to build with qt5 doesn't help at all:

![image](https://github.com/variar/klogg/assets/2454569/7b21f853-3a22-49d6-8d42-fad447db0b29)

Please, update https://aur.archlinux.org/packages/klogg PKGBUILD. Thanks a lot!

**Comment by variar** [comment]
I'm somewhat busy at the moment, but I'll check if my container for aur builds is still working probably this week

**Comment by Bodyash** [comment]
Do you need any help to test aur build?

Someone created klogg-continuous-bin (based on releases page). It's also not working, because PKGBUILD is expecting older version and needs to be updated frequently, so now it fails on download stage. Saying it just in case, I know that you don't have any control on this AUR repo.

**Comment by variar** [comment]
@Bodyash I've added a couple of patches to https://aur.archlinux.org/packages/klogg to fix build issues. It builds now in arch docker container for qt5 and qt6.

**Comment by variar** [comment]
@SoftExpert I've checked ksnip-git example and added [klogg-git](https://aur.archlinux.org/packages/klogg-git) and [klogg-bin-git](https://aur.archlinux.org/packages/klogg-bin-git).

First one builds klogg from source from the latest ci release and second just grabs the prebuilt binary from release artifacts.

To get the version number I've added a klogg_version.txt file to release artifacts.

**Comment by Bodyash** [comment]
@variar I've tested aur packages:

1. Installed klogg-bin-git. System thinks I've installed klogg-git (because PKGBUILD file for klogg-bin-git have pkgname=klogg-git). It should be fixed, because klogg-git is different package.

2. as @SoftExpert said - it's missing some files, like .desktop file and others.

**Comment by variar** [comment]
I've fixed klogg-bin-git package. Should have correct name and all the files from corresponding deb. 

@SoftExpert we can let go of klogg-continuous-bin.  

Unfortunately, I don't know of any way to provide checksums. The very nature of `-git` packages is that their sources are constantly changing. So one can't add their checksum to PKGBUILD. Adding a signing key is an option, but from documentation it seems that users have to somehow grab public keys from key-servers manually, that is inconvinient.

I'll move providing gpg signatures to CI builds to a separate issue.

**Comment by variar** [comment]
As far as I understand the point of keeping checksum inside PKGBUILD file is to separate the expected checksum from the place where the source files are stored. That way in case source files are modified, they would fail a checksum verification.  From this angle downloading checksum files from the same place as source files doesn't make package any more secure than skipping the signature check.

**Comment by variar** [comment]
Looks like the trick from rust-nightly to download checksums works for klogg_version.txt. I'll chage klogg_bin.tar.gz to klogg-$version-bin.tar.gz. That way the file name will be unique and downloaded every time

**Comment by variar** [comment]
Builds seem to work fine now. Feel free to ropen or create new issue.
