### ISSUE TITLE
VirusTotal flags some file as malicious. False positive?

### ISSUE THREAD

**Issue by alexetgus** [variar/klogg#573]
What is this "gist.github.com" address hardcoded to a file that can be executed and modified at will?
A Russian coder who hides code, it's really not the season !...
[https://www.virustotal.com/gui/file/6c39d52024ced90ba48f366c633b5dbecafbdcff90a609c5e1f9703d3a523f1d?nocache=1](https://www.virustotal.com/gui/file/6c39d52024ced90ba48f366c633b5dbecafbdcff90a609c5e1f9703d3a523f1d?nocache=1)

**Comment by GermanAizek** [comment]
@alexetgus, what kind binary file did u send to VT?

**Comment by variar** [comment]
Hi, 
Could you be more specific? Hard to tell which file you checked from this 
![image](https://github.com/variar/klogg/assets/1620716/ac044bc1-6ae5-499e-aaea-981573158621)

There are two mentions of `gist.github.com` in source code:
```
3rdparty/sentry/dump_syms/package_syms.py:#https://gist.github.com/luser/2ad32d290f224782fcfc#file-packagesymbols-py
src/settings/include/configuration.h:    // based on https://gist.github.com/QuantumCD/6245215
```
Both are in comments, so not executable. 

Pre-built packages have documentation file in HTML format, but that doesn't have any js.

**Comment by variar** [comment]
There are html files in gh-pages branch for klogg.filimonov.dev. The site is generated using `hugo` static site generator. I'll check if something suspicious is there.

**Comment by variar** [comment]
@alexetgus could you provide requested information? Without knowing what files you checked it is impossible to investigate the issue further.

**Comment by variar** [comment]
Closing as klogg doesn't have html files with php code. Feel free to reopen with more specific information
