### ISSUE TITLE
TranslationUtils.cmake can not work in Ubuntu and Mac OS

### ISSUE THREAD

**Issue by nowhszh** [variar/klogg#579]
In Ubuntu 
`QT_DIR` is `/usr/lib/x86_64-linux-gnu/cmake/Qt${QT_VERSION_MAJOR}`, but translations file in `/usr/share/qt${QT_VERSION_MAJOR}/translations`
In Mac OS
`QT_DIR` is `/usr/local/lib/cmake/Qt${QT_VERSION_MAJOR}`, but translation file in `/usr/local/share/qt/translations`
So line 50 of file [https://github.com/variar/klogg/blob/master/cmake/TranslationUtils.cmake#L50](https://github.com/variar/klogg/blob/master/cmake/TranslationUtils.cmake#L50) does not work in Ubuntu and Mac. I've also tested it in manjaro, and it doesn't work either.

**Comment by nowhszh** [comment]
The command `qmake -query "QT_INSTALL_TRANSLATIONS"`  prints the correct path.
```shell
# In Ubuntu
$ qmake -query "QT_INSTALL_TRANSLATIONS"
/usr/share/qt5/translations
# In MacOS
$ qmake -query "QT_INSTALL_TRANSLATIONS"
/usr/local/share/qt/translations
```

**Comment by variar** [comment]
Thanks for PR #580! I've merged it and added Qt translations to build containers and Mac/Win build agents setup. Translations show up in build logs now

**Comment by nowhszh** [comment]
I have verified that it works fine in `Ubuntu20.04` and `MacOS`.
The following versions were verified:
[packages-focal](https://github.com/variar/klogg/suites/13284004784/artifacts/724944105)
[packages-macos-qt5](https://github.com/variar/klogg/suites/13284004784/artifacts/724944107)
