### ISSUE TITLE
klogg would like to access my reminders

### ISSUE THREAD

**Issue by aivarannamaa** [variar/klogg#582]
I receveid macOS notification "klogg would like to access your reminders".

Why would it want to do this?

**Comment by variar** [comment]
Honestly, I've no idea. Most likely packaging for macOS is messed up, somewhere there must be a section describing app permissions that has more entries than required. Is it coming from `dmg` or `pkg` package?

I don't have macOS environment at the moment to test this, packaging is done by github CI pipeline.

**Comment by nowhszh** [comment]
@variar  What can I do with this issue

**Comment by variar** [comment]
My guess is that something (Qt, crashpad?) is trying to get this authorization https://developer.apple.com/documentation/bundleresources/information_property_list/nsremindersfullaccessusagedescription.

Docs say that app bundle plist must explicitly mention the reason for asking such permissions if app wants to get it. 

@nowhszh could you maybe check what permissions are granted to klogg in your setup?

**Comment by variar** [comment]
@aivarannamaa what version of klogg did you try? Was it downloaded from github? Dmg or pkg installer? Or was it installed from homebrew?

**Comment by nowhszh** [comment]
@variar Access to files and folders only

**Comment by variar** [comment]
I've bumped Qt and crashpad. Hopefully these permission questions issue is resolved in 24.11.0.1631+

**Comment by variar** [comment]
Can't get this request for recent 24.11.0.1681+ builds. Feel free to reopen if this appears again.
