### ISSUE TITLE
klogg crashed on network change

### ISSUE THREAD

**Issue by kindacute** [variar/klogg#583]
Details for the issue
--------------------

#### What did you do?

-------------------------
Crash id:
633306bd-47b0-4e40-8d94-2c43e5e42d06
-------------------------
Useful extra information
-------------------------
> Klogg version 22.06.0.1289 (built on 2022-06-14 from commit 6340d94) [built for x86_64-little_endian-lp64]
> running on macOS 13.4 (darwin/22.5.0) [x86_64], concurrency 12
> Qt 6.2.4, tbb 2021.7

**Comment by variar** [comment]
Unfortunately, there is not much information in sentry crash report. Could you describe what was happening? Was there a file open from network share during network change?
