### ISSUE TITLE
Crash on opening file with empty lines and Unix line endings

### ISSUE THREAD

**Issue by PetbkA** [variar/klogg#584]
Details for the issue
--------------------

#### What did you do?
1. Open [FailTest.log](https://github.com/variar/klogg/files/11651032/FailTest.log)
2. klogg will crash while trying to process _empty_ string with _Unix_ line endings (`LF`)

Presumably bug appeared in **23.06.0.1400 Qt5 x64**. Was OK on **23.04.0.1331 Qt5 x64**.

-------------------------
Crash id:
b18ed515-099b-4a61-9bd1-4e2e2f6254a0
-------------------------
Useful extra information
-------------------------
> Klogg version 23.06.0.1400 (built on 2023-06-03 from commit 833142e) [built for x86_64-little_endian-llp64]
> running on Windows 10 Version 2009 (winnt/10.0.19044) [x86_64], concurrency 4
> Qt 5.15.2, tbb 2021.7

**Comment by variar** [comment]
Thanks! Found the issue. Will do some more checks in other parts changed for text wrap to avoid similar crashes.

**Comment by variar** [comment]
This should be fixed in 23.06.1405+

**Comment by PetbkA** [comment]
**23.06.0.1405 Qt5 x64 Windows** - fixed
