### ISSUE TITLE
Crashing on horizontal scroll without word wrap

### ISSUE THREAD

**Issue by variar** [variar/klogg#586]
**23.06.0.1405 Qt5 x64 Windows** - if word wrap is disabled, _horizontal_ scrolling beyond the visible area of the _hightlighted_ line crashes klogg (Sentry report `356b2557-876d-468c-80eb-29f04d3dea76`). Workaround - disable highlighter for this string or enable word wrap.

_Originally posted by @PetbkA in https://github.com/variar/klogg/issues/99#issuecomment-1578419500_

**Comment by variar** [comment]
Should be fixed in 23.06.0.1407

**Comment by PetbkA** [comment]
**23.06.0.1407 x64 Qt5 Windows** - fixed
