### ISSUE TITLE
[Options][Word wrap]: leave only "global" option or add menu button and hot key for it

### ISSUE THREAD

**Issue by PetbkA** [variar/klogg#587]
**OS**: Windows 10 LTSC 2021 (version 21H2) x64 EN
**klogg**: 23.06.0.1407 Qt5 x64

After "global" option for word wrap has been added in #99, there's a strange situiation in terms if UI:
1. In **menu → View** and hotkeys there's only "per-file" option;
2. In **Preferences→ View** there's global option.

IMHO leaving one, "global", option is better as it's done in e.g. Notepad++.

But if two options should be, it would be nice to change state of "global" also via menu or hot keys. Of course, both options should be renamed to reflect their meaning

**Comment by variar** [comment]
They behave the same way as "follow fike on load" global option and "follow file" option for current view.  Renaming global one two something like "Enable text wrap by default" should make it less confusing.

**Comment by variar** [comment]
In 23.06.0.1419 I've changed the global option to apply only to new open files. It now doesn't do anything with files opened before changing the option. Renamed the global option to avoid confusion.

**Comment by PetbkA** [comment]
**23.06.0.1419 x64 Qt5 Windows** - [fixed](https://github.com/variar/klogg/assets/22843816/1a3cb79b-e058-4581-a4c3-6136188a57db):
1. Global option renamed to _Enable text wrap **on file open**_;
2. Global option isn't being changed via hotkey, which is pretty logical as you rarely change global behavior
