### ISSUE TITLE
[Word Wrap]: lines at the bottom of the view are hidden when word wrap is enabled

### ISSUE THREAD

**Issue by PetbkA** [variar/klogg#589]
**OS:** Windows 10 LTSC 2021 (version 21H2) x64 EN
**klogg:** 23.06.0.1407 Qt5 x64

When word wrap is **en**abled, lines at the bottom of log frame or search results frame are [doublecmd_2023-06-08_10-57-29](https://github.com/variar/klogg/assets/22843816/f1b782d2-ebfd-43ca-a255-dc8129fdf242). Disabling and enabling word wrap again doesn't fix the problem

**Comment by variar** [comment]
Related to #99. Vertical scroll bar needs to be adjusted based on wrapped lines height

**Comment by PetbkA** [comment]
**23.06.0.1413 Qt5 x64 Windows** - fixed. Checked with both default states and changing from default and back
