### ISSUE TITLE
[Word wrap]: word wrap state returns to "global" after switching between files

### ISSUE THREAD

**Issue by PetbkA** [variar/klogg#591]
**OS**: Windows 10 LTSC 2021 (version 21H2) x64 EN
**klogg**: 23.06.0.1407 Qt5 x64

**Steps to Reproduce:**
1. Open two files;
2. Change _Wrap text_ option for file 1 so it would differ from global option being set in _Preferences → View_;
3. Change tab to file 2 and back to file 1 - **NOK**, 'cause word wrap state returned to global setting while it should save state set in step 2

**Comment by variar** [comment]
In 23.06.0.1419 I've changed the global option to apply only to new open files. It now doesn't do anything with files opened before changing the option.

**Comment by PetbkA** [comment]
**23.06.0.1419 x64 Qt5 Windows** - fixed
