### ISSUE TITLE
Open icon is misleading

### ISSUE THREAD

**Issue by czlitony** [variar/klogg#596]
I'm using klogg the first time, the open icon is misleading to me, it looks like a new file icon instead of open icon
![image](https://github.com/variar/klogg/assets/20141496/d2035bda-d6a0-4887-acb6-d6d37799d875)

**Comment by variar** [comment]
I guess it could be like this:
![image](https://github.com/variar/klogg/assets/1620716/699e4036-3e06-45f8-ace2-0194576a8078)

Is this more intuitive?

**Comment by czlitony** [comment]
Yes, this is intuitive.
