### ISSUE TITLE
[Feature Request] Show marks in a tab

### ISSUE THREAD

**Issue by czlitony** [variar/klogg#597]
Currently, we can choose the "Marks" option in the dropdown list, since the marks function is used frequently, suggest show marks in a tab that can be viewed with a single click.
![image](https://github.com/variar/klogg/assets/20141496/9b37b5ec-0838-4088-bcf1-fb43a8f48cfa)

The JEdit design is good:
![image](https://github.com/variar/klogg/assets/20141496/58087329-6488-451c-a976-4f579a55a103)

**Comment by variar** [comment]
There is a shortcut that allows to switch mode of the bottom view. Isn't that even faster than tabs?

**Comment by variar** [comment]
Is this implemented in #599?

**Comment by czlitony** [comment]
Yes, the shortcut is faster. I'm new to klogg, I didn't notice there is a shortcut to switch bottom view.

**Comment by czlitony** [comment]
Close this jira as there is a shortcut `V` to switch bottom view.
