### ISSUE TITLE
[Feature Request] Open klogg in terminal on macOS

### ISSUE THREAD

**Issue by guangyya** [variar/klogg#619]
On Linux, we can open a log file by using 

```shell
$ klogg logfile.log
```

However, on macOS, we cannot do that, klogg was not installed to the path.

**Comment by nowhszh** [comment]
The way to launch the app on the command line in mac is as follows
```shell
# launch by  App name
$ open -a <App name> --args <args...>

# launch by App path
$ open <App path> --args <args...>
```
I often use the path way to start `open /Applications/klogg.app`

**Comment by guangyya** [comment]
@nowhszh  thanks for the answer! It's working!
I am wondering whether we could make it aligned with Linux platforms, as I have some shell scripts running on Linux, I want to reuse it as much as possible without making anything platform related.

**Comment by nowhszh** [comment]
This is the standard way to start the app in mac, you can write this command as a shell script or configure it with the alias command, so the behavior will be the same in both platforms

**Comment by guangyya** [comment]
Thanks! @nowhszh

**Comment by czlitony** [comment]
@guangyya `/Applications/klogg.app/Contents/MacOS/klogg CMakeLists.txt` also works.

```
➜  klogg /Applications/klogg.app/Contents/MacOS/klogg -h
Usage: /Applications/klogg.app/Contents/MacOS/klogg [options]
Klogg log viewer

Options:
  -h, --help                 Displays help on commandline options.
  --help-all                 Displays help including Qt specific options.
  -v, --version              Displays version information.
  -d, --debug <debug_level>  output more debug (increase number for more
                             verbosity)
  -m, --multi                allow multiple instance of klogg to run
                             simultaneously (use together with -s)
  -s, --load-session         load the previous session (default when no file is
                             passed)
  -n, --new-session          do not load the previous session (default when a
                             file is passed)
  -l, --log                  save the log to a file
  -f, --follow               follow initial opened files
  --window-width <1024>      new window width
  --window-height <768>      new window height
```

**Comment by guangyya** [comment]
> @guangyya `/Applications/klogg.app/Contents/MacOS/klogg CMakeLists.txt` also works.
> 
> ```
> ➜  klogg /Applications/klogg.app/Contents/MacOS/klogg -h
> Usage: /Applications/klogg.app/Contents/MacOS/klogg [options]
> Klogg log viewer
> 
> Options:
>   -h, --help                 Displays help on commandline options.
>   --help-all                 Displays help including Qt specific options.
>   -v, --version              Displays version information.
>   -d, --debug <debug_level>  output more debug (increase number for more
>                              verbosity)
>   -m, --multi                allow multiple instance of klogg to run
>                              simultaneously (use together with -s)
>   -s, --load-session         load the previous session (default when no file is
>                              passed)
>   -n, --new-session          do not load the previous session (default when a
>                              file is passed)
>   -l, --log                  save the log to a file
>   -f, --follow               follow initial opened files
>   --window-width <1024>      new window width
>   --window-height <768>      new window height
> ```

great news, then I think I only need to add a soft link to /Applications/klogg.app/Contents/MacOS/klogg

**Comment by guangyya** [comment]
Thank you all for the help! Problem solved, here is what I did. 

```shell
$ sudo ln -s /Applications/klogg.app/Contents/MacOS/klogg /usr/local/bin/klogg
$ klogg --help
```
<img width="667" alt="image" src="https://github.com/variar/klogg/assets/18567693/68f6fdd9-ed4f-4909-a402-5981cbab71ae">
