### ISSUE TITLE
[Bug] klogg crash on Ubuntu20.04 

### ISSUE THREAD

**Issue by nowhszh** [variar/klogg#622]
Details for the issue
--------------------

#### What did you do?

-------------------------
Crash id:
4ce43d91-6c9e-4698-b82d-0e97a9f9e4cc
-------------------------
Useful extra information
-------------------------
> Klogg version 23.06.0.1479 (built on 2023-06-25 from commit ) [built for x86_64-little_endian-lp64]
> running on Ubuntu 20.04.6 LTS (linux/5.15.0-73-generic) [x86_64], concurrency 12
> Qt 5.12.8, tbb 2021.7

**Comment by nowhszh** [comment]
The open file display also has an exception， I have found the cause of the problem and I will fix it later
![image](https://github.com/variar/klogg/assets/31587297/f1391cd9-eea1-43ce-8d4f-c22dbe0e8008)

**Comment by variar** [comment]
should be fixed in 23.06.0.1500

**Comment by nowhszh** [comment]
Horizontal scrolling also shows errors and crash
![image](https://github.com/variar/klogg/assets/31587297/a8a79851-74a4-42f6-9ed9-ebfd8fd342c0)

**Comment by nowhszh** [comment]
I did not have a similar problem today using klogg. I will close this issue if the problem does not appear by next week

**Comment by nowhszh** [comment]
Fixed and problem is not recurring
