### ISSUE TITLE
Features suggestions:  Reorder tab context menu

### ISSUE THREAD

**Issue by pabloh84** [variar/klogg#639]
First of all thank you for the great work. I apologize if this is not the correct way to report this, but I have a few proposals to improve the usability of the app regarding the tab context menu

![image](https://github.com/variar/klogg/assets/7147388/b22579b9-b5ab-449d-9821-7512bdb64596)

### 1. Change the order for the closing options of the context context menu on tabs:

The first ones are the ones about closing the file which causes that sometimes tab is closed by error, losing all the work done (specifically color labels and marks)

### 2. Allow for side by side working. I have two proposals: 

- **Option A**. Add an "Open in new Window" option to that menu to allow sending the file (and its corresponding marks, highlighters, color labels, etc..)  and filters to a new window. This would be most useful to allow side by side comparison of two files

- **Option B**.  Alternatively (but I imagine that harder to implement) allow a column layout, allowing to have 2 (or more) files side by side. Ideally this layout should allow to apply the same filters, highlighters and color labels, etc. to both files at the same time. 

Again thanks for the great work. Have a nice day. 

-------------------------
Useful extra information
-------------------------
> Klogg version 23.06.0.1524 (built on 2023-07-05 from commit ) [built for x86_64-little_endian-lp64]
> running on Ubuntu 23.04 (linux/6.2.0-24-generic) [x86_64], concurrency 12
> Qt 5.15.8, tbb 2021.7

**Comment by variar** [comment]
Thank you! All proposals are welcome :) 
The tab context menu ordering is inspired by VSCode. I guess closing options could go to the bottom of the menu.

Side by side working is already possible.  There is an option to enable multiple windows:
![image](https://github.com/variar/klogg/assets/1620716/ab0da921-f94a-490c-b4e9-d55c17086f85)

An option to open file in a new window is a nice addition to that feature.

**Comment by pabloh84** [comment]
Thank you a lot for your feedback.

About the the tab context menu ordering: You are right: Other IDEs have the same ordering (VSCode / Sublime Text)... However I do work with both and have not experience this issue. 

I have realized that after right clicking most of the times "Close This" gets selected by default and just releasing the button causes the tab to close (likely due to an involuntary mouse movement and the way Qt renders the context menu). 

On that topic I dare suggest you consider any (or both) of the following (to avoid the reordering): 

- Sublime Text approach: Context menu appears on "button released" instead of "button pressed" This way you avoid unwanted actions on right button release. 
- Check if the filter panel is "dirty" (marks, a current search, color labels applied, etc...) and ask for confirmation before closing to avoid losing work

On the "side by side working" topic, I was already aware of the option to enable multiple windows (and I use it frequently). My suggestions were more on the line of improving the user experience for that use case. This are the things I miss the most (and the bottom line for my suggestion):

- It would be great if it were possible to move the current file AND all its current work (color labels, marks, search history, etc...) to a new window. My common use case is that I am working on two files on the same window and at some point I realize that I would like to see them side by side. 
- It would be GREATER if you could apply the same actions to two files at the same time (filters, color labels, etc...) in order to quickly find/visualize the same things in both files.

**Comment by xaljer** [comment]
I vote for the "Open in new window" option and windows (of one file) could sync actions in the past and feature.

**Comment by variar** [comment]
Looks like opening context menu on mouse press is default for Qt.  I've added a change to open tab context menu on mouse release. Not going to change all other context menus as they are not so destructive

**Comment by pabloh84** [comment]
Great! I will test and provide feedback on next continuous release!

**Comment by variar** [comment]
@pabloh84 I've moved "side-by-side" feature to a separate issue. It is easier to keep track of things.

**Comment by variar** [comment]
Fix for tab context menu is in 23.06.0.1538+

**Comment by pabloh84** [comment]
> @pabloh84 I've moved "side-by-side" feature to a separate issue. It is easier to keep track of things.

Perfect, I'll change the title in this one for further clarity


> Fix for tab context menu is in 23.06.0.1538+

Tested and fixed in 23.06.0.1538
