### ISSUE TITLE
"Save selected to file" does not work when using "Set selection start" and "Set selection end"

### ISSUE THREAD

**Issue by pabloh84** [variar/klogg#644]
Details for the issue
--------------------

#### What did you do?
- Open a file
- Use "Set selection start"
- Use "Set selection end"
- Use "Save selected to file"

#### What did you expect to see?
- All the selected lines should be dumped to the selected file 

#### What did you see instead?
- Only one line (the last selected one) is dumped into file. 

If selection is done with mouse / keyboard it works as expected. 

-------------------------
Useful extra information
-------------------------
> Klogg version 23.06.0.1524 (built on 2023-07-05 from commit ) [built for x86_64-little_endian-lp64]
> running on Ubuntu 23.04 (linux/6.2.0-24-generic) [x86_64], concurrency 12
> Qt 5.15.8, tbb 2021.7

**Comment by variar** [comment]
Fix is in 23.06.0.1538+

**Comment by pabloh84** [comment]
Tested and working with 23.06.0.1538
