### ISSUE TITLE
What instruction set does hyperscan use in klogg on the Windows platform？

### ISSUE THREAD

**Issue by Stevenkop** [variar/klogg#656]
I noticed that on Linux, klogg uses the fat runtime for hyperscan, but when decompiling on Windows, it seems that the fat mode is not used. I would like to know what instruction set is used for hyperscan in klogg on Windows. Does it only use SSSE3 to ensure compatibility, or does it use more advanced instruction sets such as SSE4.2, AVX2, or AVX512 with some clever techniques? Are they also supported in the same way as the fat runtime?

**Comment by variar** [comment]
There is nothing clever going on in klogg builds. CI is building with SSSE3 and popcnt support. I've considered building several versions of hyperscan as shared libraries and then load the best one on startup, but haven't tried to implement it yet.
