### ISSUE TITLE
a complete word cannot be displayed

### ISSUE THREAD

**Issue by log1pt03** [variar/klogg#659]
When the word wrap is turned on, a complete word cannot be displayed, that is, a complete word will be separated

for example:
klogg:
![1691041376544.jpg](https://github.com/variar/klogg/assets/65451470/3941f48c-922d-43a5-9d67-e2176cc51b9d)

VSCode:
![1691041379467.jpg](https://github.com/variar/klogg/assets/65451470/ed4a6ba3-f077-46b3-a76f-2fb5f73e95f2)

**Comment by variar** [comment]
Indeed, klogg currently does simple line wrap and doesn't respect word boundaries. The proper word wrap is planned a bit later.

**Comment by variar** [comment]
Should be better in 24.11.0.1631+
