### ISSUE TITLE
Unneccesary consecutive config-file reads & writes

### ISSUE THREAD

**Issue by gin-ahirsch** [variar/klogg#66]
I've noticed that on startup and shutdown `klogg.conf` gets read (and written respectively) thrice (twice without version checking).
This is because `MainWindow::{read,write}Settings()` synchronizes multiple persistables.
This is a very minor issue (especially because the file is very likely cached in RAM due to the very small delay between accesses), but ideally we'd `saveToStorage` each persistable without `settings_.sync()` and then only do a single `settings_.sync()` afterwards.

I also found it surprising that `Configuration` and `VersionCheckerConfig` are synchronized on shutdown instead of after applying new settings via the `OptionsDialog`. What's the reason for this? Most other things are synchronized immediately I think.

**Comment by variar** [comment]
Saving configuration is now done on apply.
