### ISSUE TITLE
Loading  a file throws errror.

### ISSUE THREAD

**Issue by prakashsvmx** [variar/klogg#670]
Details for the issue
--------------------
Loading  a file throws errror.

#### What did you do?
![image](https://github.com/variar/klogg/assets/23444145/cfb179e5-3548-4b50-9d54-f53194a30bf3)

#### What did you expect to see?
It could be specific to a line may be

#### What did you see instead?
Error was displayed.

-------------------------
Useful extra information
-------------------------
> Klogg version 22.06.0.1289 (built on 2022-06-14 from commit ) [built for x86_64-little_endian-lp64]
> running on Ubuntu 20.04.6 LTS (linux/5.15.0-79-generic) [x86_64], concurrency 12
> Qt 5.12.8, tbb 2021.7

**Comment by nowhszh** [comment]
From the prompt, it means that the file is too big, normally Qt5 only supports files up to 2GB, if your file is not that big, it might be a bug.

**Comment by variar** [comment]
The 2Gb limit is not for the total file size but for the length of each line in the file. Qt6 builds don't have this limitation.

**Comment by variar** [comment]
I've added Qt6 build for ubuntu 24.04. Not much can be done for Qt5 builds.
