### ISSUE TITLE
[feature request] Copy specified range of lines

### ISSUE THREAD

**Issue by Abay11** [variar/klogg#684]
I think this would be very useful feature.
I often copy many lines of text and I need to sit and select lines and scroll it down manually.
If you think too it would be useful, I can open a PR with changes

**Comment by Abay11** [comment]
Or let's implement selection with Shift + PgUp/PgDown for quicker selection

**Comment by nowhszh** [comment]
This feature seems to already exist
![Peek 2023-10-27 15-38](https://github.com/variar/klogg/assets/31587297/68150579-38ba-45f9-937a-2c7fb887fbe4)

**Comment by Abay11** [comment]
@nowhszh, oh, thanks for response. I didn't know about it

**Comment by nowhszh** [comment]
You can also select by shortcut keys, first click the left mouse button to select the start line, then press the shift button and click the left mouse button to select the end line at the same time.
