### ISSUE TITLE
Added link on Alternativeto.net

### ISSUE THREAD

**Issue by zielot** [variar/klogg#69]
I haven't been able to find a way to contact Anton Filimonov and/or the developers. This is for your information and a note of thanks.
* I discovered klogg in the review for glogg. glogg is great but they are no longer providing Windows builds and it seems that you have added a couple of new features.
* I created an entry on [alternativeto.net](https://alternativeto.net/software/klogg/) though it hasn't been approved as of the time of this writing.
Regards,
Justin

**Comment by variar** [comment]
Thanks
