### ISSUE TITLE
crash on arrow key press

### ISSUE THREAD

**Issue by michalmoc** [variar/klogg#697]
### Error

```
/usr/include/c++/13.1.1/optional:484: constexpr const _Tp& std::_Optional_base_impl<_Tp, _Dp>::_M_get() const [with _Tp = LineNumber; _Dp = std::_Optional_base<LineNumber, true, true>]: Assertion 'this->_M_is_engaged()' failed.
```

### Steps to reproduce

1. open log file
2. select any line
3. press up or down arrow

### Version
Built from AUR package "klogg-git", self described as "klogg 23.06.0.1419" and "Built 2023-06-13 from d4af926"

**Comment by variar** [comment]
Can't reproduce this in current builds. Might have been fixed
