### ISSUE TITLE
Automatic line wrapping 

### ISSUE THREAD

**Issue by flcker** [variar/klogg#698]
Displays wrap when a line is too long

**Comment by Junbo-Zheng** [comment]
@flcker 
klogg already supports the **wrap** function, it is an optional feature, you can select it through `View` -> `Wrap text`, refer to here 
![img_v2_b7ab34fb-3083-4ce1-b0c1-f3a80d4a26al](https://github.com/variar/klogg/assets/19257159/0f26db77-187f-4791-97ec-4c1c1ef8ba55)

Of course, you can also **select** or **unselect** through shortcut keys **w**, depending on which method you want.

**Comment by flcker** [comment]
![image](https://github.com/variar/klogg/assets/7287246/6d971168-4b74-41d6-89bd-0d36d62b09dd)

Which version? The version I'm using doesn't have this feature yet.

**Comment by Junbo-Zheng** [comment]
> ![image](https://private-user-images.githubusercontent.com/7287246/290067870-6d971168-4b74-41d6-89bd-0d36d62b09dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NDkwNjcsIm5iZiI6MTcwMjQ0ODc2NywicGF0aCI6Ii83Mjg3MjQ2LzI5MDA2Nzg3MC02ZDk3MTE2OC00Yjc0LTQxZDYtODliZC0wZDM2ZDYyYjA5ZGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTNUMDYyNjA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODgwMGY1OGE4MzQ1Njg1NTU4NThhYmQzMjE2OTBiYmY4YWVjMjc0YTViYzJmMGU3Yzc3ZmQ3ODJjNmE1OGFmNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JawYSicXBnpxoLgOBmCYDWGxHUPXlhKVuDopacRWpEo)
> 
> Which version? The version I'm using doesn't have this feature yet.

@flcker 

Please try downloading the **pre-release** version from https://github.com/variar/klogg/releases, you can choose the corresponding version according to your computer.
- continuous-linux: https://github.com/variar/klogg/releases/tag/continuous-linux
- continuous-osx: https://github.com/variar/klogg/releases/tag/continuous-osx
- continuous-win: https://github.com/variar/klogg/releases/tag/continuous-win

Reference:
- feat: add experimental support for text wrap https://github.com/variar/klogg/commit/e6aa7dae0c444dc0b8d517c3f8719a379a3d7906
- https://github.com/variar/klogg/issues/99

**Comment by flcker** [comment]
ok thanks
