### ISSUE TITLE
"Copy this line" include an extra \r

### ISSUE THREAD

**Issue by wiz0u** [variar/klogg#70]
Right-clicking a line and selecting "Copy this line" put this line in the clipboard with an extra \r at the end.
It should be removed.

**Comment by wiz0u** [comment]
Also, Ctrl-C is a shortcut for this Copy action.
It would be nice to support the older classical clipboard shortcut for Copy as well : Ctrl-Insert
(very used by left-handed people like me)

**Comment by variar** [comment]
Thanks, will do when return from Japan in mid-May.

**Comment by variar** [comment]
Fixed line endings for copying from both main and filterd view. 
Added all bindings for copy key sequence (Ctrl+Ins/Shift+Ins should work)

Should be in Build 19.07.0.424

**Comment by wiz0u** [comment]
Works fine now. Thanks
