### ISSUE TITLE
Feature Request: Keyboard Shortcut to go forward or back to the next highlighter

### ISSUE THREAD

**Issue by niwred** [variar/klogg#722]
I have defined some useful highlighters for easier navigation in very large log files with a lot of noise. It would be nice if I could just step through the highlighted parts of the file. Or am I missing something?

**Comment by variar** [comment]
The "quickfind" feature has something like this. But not for the highlighters.

**Comment by niwred** [comment]
Thanks! I now use a work-around by defining a set of predefined filters that match the highlighters regexes. Then I select the filter(s) that I'm interested in. Easier to navigate in the filter result window. (Version 23.08)
