### ISSUE TITLE
ERRRORR

### ISSUE THREAD

**Issue by TATAjiHAU** [variar/klogg#737]
Details for the issue
--------------------

#### What did you do?

-------------------------
Crash id:
a6de6433-993c-4ca7-bae1-44e1f4f394ed
-------------------------
Useful extra information
-------------------------
> Klogg version 22.06.0.1289 (built on 2022-06-14 from commit 6340d94) [built for x86_64-little_endian-llp64]
> running on Windows 10 Version 2009 (winnt/10.0.22621) [x86_64], concurrency 16
> Qt 5.15.2, tbb 2021.7

**Comment by variar** [comment]
Might be fixed in recent builds 24.11.0.1662+
