### ISSUE TITLE
Multiple files on command line

### ISSUE THREAD

**Issue by shvez** [variar/klogg#74]
Hi, there

Just checked and it is turned out that at least portable version (19.06.0.401) does not accept multiple files from the command line. Moreover, it does not even start in this case. 
if I pass to it only one file, then it starts to work

best,
ilya

**Comment by variar** [comment]
should be fixed in 7b3fdd5562740482d2b2bddd8b4b61eef1426594

**Comment by shvez** [comment]
I will test, thank you

**Comment by shvez** [comment]
it works. thank you
