### ISSUE TITLE
Duplication of search results

### ISSUE THREAD

**Issue by shvez** [variar/klogg#78]
hi, there

With version 19.7.0.407 I started to see an issue when klogg gives me last found result twice

![image](https://user-images.githubusercontent.com/7521076/61026827-c8370300-a3b4-11e9-8234-7d982ad0be99.png)

Here is result after reload

![image](https://user-images.githubusercontent.com/7521076/61026862-e997ef00-a3b4-11e9-94f3-ad6fc5a3ed83.png)

I believe that the way to reproduce is next.

Open log file which is updated from outside. Start the search for some line. Then stop to update and clear file content using klogg menu. After that start to update file. Newfound matches will be duplicated in search results.

klogg 19.7.0.407 on windows 10

best,
ilya

**Comment by variar** [comment]
Looks like regression after merging #67

**Comment by variar** [comment]
Could you check on latest CI build?

**Comment by shvez** [comment]
sure

**Comment by shvez** [comment]
build 409 or there is a newer one?

**Comment by shvez** [comment]
build 410 works as expected
