### ISSUE TITLE
Suggestion: Better highlight for current file tab

### ISSUE THREAD

**Issue by wiz0u** [variar/klogg#80]
It would be nice if the currently selected file tab is highlighted in some way (blue text? lighter background?)
because I find it hard to distinguish in a glance which tab is currently active.

**Comment by variar** [comment]
In build 19.07.0.423 I've changed qt to use more modern style. Current tab is more visible now. Also current tab has colored "close" button whereas inactive tabs have grey button. 

 @wiz0u could you check the new style. I'll look into changing background color of inactive tab to something more dark if current colors are still not distinguishable enough.

**Comment by wiz0u** [comment]
The new tab highlight seems fine to me. Thanks
