### ISSUE TITLE
"Active" Search pane?

### ISSUE THREAD

**Issue by wiz0u** [variar/klogg#81]
Is the search pane supposed to be actively updated when new lines match the pattern?

When the "Follow file" option is checked, there is yellow/gray stripes below the main window AND below the search pane, which seems to mean it also follows new matching lines.

But it doesn't.

If it is normal that it is not updated, you can remove the yellow/gray stripes.

Seen on 19.7.0.421 with default options.

**Comment by variar** [comment]
Seems like it should. Not sure if it worked in earlier builds but need to be fixed

**Comment by variar** [comment]
This was broken after introducing limiting search to part of file. By default search was limited from start to end of file, but after data refresh the end line limit was not changed.

Should be fixed in >=19.07.0.431

**Comment by wiz0u** [comment]
I think the yellow/gray stripes below the search pane should appear only when "Auto-refresh" is checked (even if the main window is not on "Follow file" mode)

**Comment by variar** [comment]
moved stripes problem to separate issue
