### ISSUE TITLE
Minor: Ctrl-End doesn't refresh correctly on last page

### ISSUE THREAD

**Issue by wiz0u** [variar/klogg#82]
Go to bottom of a non-changing file.
Click on a line in the middle. That selected line is highlighted.
Press Ctrl-End.
The selected line doesn't seem to change for the last line of the file.

(although if you scroll with the mouse wheel or press Ctrl-C you realize the selected line was really changed but the window was not redrawn)

**Comment by variar** [comment]
Done in builds >= 505
