### ISSUE TITLE
Show log from clipboard

### ISSUE THREAD

**Issue by Reyhn3** [variar/klogg#85]
It would be nice if the File-menu had an item like "New from clipboard" that takes any text in the clipboard and presents it so I don't have to manually save the clipboard to a temporary file and then open it.

**Comment by variar** [comment]
Thanks for suggestion. 

I've added a menu item for this. Also Ctrl+V or Shift+Insert shortcuts should work if focus is not in input fields. Should be in builds >= 19.08.0.442.

That is really handy not only for described use case but also when repeatedly narroing search results -- just select all search results, copy to clipboard, paste it back and klogg will open new temp file where one can continue searching. Can be somehow used for nickbnf/glogg#266 with negative lookahead patterns

**Comment by Reyhn3** [comment]
Nicely done! It works very well.
Much appreciated! (:
👍
