### ISSUE TITLE
shortcut for 'Clear file'

### ISSUE THREAD

**Issue by dia-susca** [variar/klogg#86]
It would be useful to have a shortcut keys combination to the Edit -> Clear file action, to be able to easily clear the log file.
Or maybe a button somewhere?

Thanks!

**Comment by variar** [comment]
This is dangerous action so it is hard to execute. I'm thinking of some way for shortcuts confiuration (UI or just text file #26) and add all actions there.

**Comment by variar** [comment]
Assigned standard "cut" shortcut in builds >=19.11.0.505
