### ISSUE TITLE
Unable to set marks in FilteredView while viewing MatchesOnly

### ISSUE THREAD

**Issue by gin-ahirsch** [variar/klogg#89]
When setting the visibility of the `FilteredView` to `MatchesOnly`, the mark-bullets do not show anymore and attempting to set or remove marks will not work.
Additionally, the error-message `10:47:42.641 ERROR [8116] [Marks::addMark@69] Trying to add an existing mark at line 19` appears for lines, which are already marked.

`LogFilteredData` contains fastpaths for when only one type of filtered lines are displayed, which leads it to pretend as though no lines are marked and results in the buggy behavior. It'd probably also be good to display the mark-bullets in the `FilteredView` even for `MatchesOnly` when a matched line is also marked.

This could be easily solved by implementing `FilteredView::lineType()` analogous to `LogMainView::lineType()`, which uses `LogFilteredData::isLineMarked()` and `LogFilteredData::isLineInMatchingList()` instead of `LogFilteredData::filteredLineTypeByIndex()` to figure out the line-type (Normal | Marked | Match).
However maybe the fastpaths in `LogFilteredData` should just be removed in favor of a single code-path always using the `filteredItemsCache_`. `AbstractLogView::LineType` would become flags, just like `LogFilteredData::FilteredLineType` (the former should probably just become a typedef of the latter), and the `FilteredView` as well as the `LogMainView` would both use `LogFilteredData::filteredLineTypeByIndex()` and `LogFilteredData::filteredLineTypeByLine()` (new) respectively.
Apart from the impact of always updating the `filteredItemsCache_` (which we need to do when viewing `MarksAndMatches` anyways, probably the usual configuration), `FilteredView::lineType()` would behave mostly identical, while `LogMainView::lineType()` would only ever need a single lookup (searching in `filteredItemsCache_`) instead of potentially needing to search two lists (`LogFilteredData::isLineMarked()` and `LogFilteredData::isLineInMatchingList()`).

I'm willing to implement a resolution and open a PR, though I wanted to present the two implementation variants I can imagine and await the decision.

**Comment by variar** [comment]
Can this be combined with PR #75 about eager cache fill? This way we will always have up to date filteredItemsCache_ and can use it for all line type checks. I don't believe that fastpaths provide that much of performance improvements in daily use and they do increase code complexity.

Maybe we should do it in two steps, first merging PR #75 and then creating new PR on top of it.
I'll try to update PR branch today to resolve current conflicts with master. I'm willing to trade some performance for latency and more clear code paths.

We can show marked lines in MatchesOnly view with something like read arrow. I think this way it is harder to be confused about current filtered view mode.

**Comment by gin-ahirsch** [comment]
It'd work independently of #75. Merge-conflicts should be localized to `LogFilteredData::filteredLineTypeByIndex()` and just involve the `filteredItemsCacheDirty_` check.

**Comment by gin-ahirsch** [comment]
> We can show marked lines in MatchesOnly view with something like read arrow. I think this way it is harder to be confused about current filtered view mode.

Maybe lines that are marked and matched should always get the red arrow, independent of the visibility-mode? If we change to using flags for `AbstractLogView::LineType` as well, doing this would be trivial.

**Comment by variar** [comment]
> Maybe lines that are marked and matched should always get the red arrow, independent of the visibility-mode? If we change to using flags for `AbstractLogView::LineType` as well, doing this would be trivial.

Yes, that could work. However, I think that color for Marked&Matched line arrow should be different from red circle match. Some kind of darker red or purple migth do

**Comment by variar** [comment]
Implemented the most simple fix using `LogFilteredData::isLineMarked()` in `FilteredView::lineType()`

Proper code cleanup for single code path is still desired.
