### ISSUE TITLE
Close of application in few seconds after removal of all opened log files

### ISSUE THREAD

**Issue by shvez** [variar/klogg#92]
hi, there.

Found an issue in the last build on Windows 10

if I remove all opened files from disk, in one or two seconds the application is closed automatically

klogg version is 19.8.0.444

**Comment by variar** [comment]
Hi, seems like build is crashing silently. Could you enable logs (from options) and attach them to the issue? Logs are saved to %TEMP% folder.

**Comment by shvez** [comment]
done, I hope
[klogg_2019-08-21_17-41-12_14516.log](https://github.com/variar/klogg/files/3526199/klogg_2019-08-21_17-41-12_14516.log)

**Comment by variar** [comment]
Thanks, I'll look into it after returning to Moscow next week. Meanwhile older builds can be downloaded from appveyor. I think this one should be without this bug https://ci.appveyor.com/project/variar/klogg/builds/26671074/job/tvi2agup6ggfddy7/artifacts

**Comment by variar** [comment]
fixed in 19.08.0.446. @shvez could you try new build?

**Comment by shvez** [comment]
it looks like it works as expected.

thank you
