### ISSUE TITLE
Cannot delete directory containing file Klogg has open

### ISSUE THREAD

**Issue by jeffjensen** [variar/klogg#93]
Running on Windows 10.  Currently Klogg 19.8.0.447-portable.

Klogg has not locked the file for many releases, so we can successfully delete or overwrite it. 
 However, a problem remains that the file's directory is locked by Klogg and prevents the directory's deletion.

This is a problem when the log file resides in the build output's directory - residing there so it is removed with a clean build.  The build's clean operation completes successfully but the directory still exists - it has been "mostly" deleted.  The problem is we cannot view the directory's contents and the build cannot create the directory so it fails; both encounter access denied.

Exiting Klogg causes the final removal of the directory and the build can successfully create it again.

Wondering if this can be eliminated by Klogg code change; hoping it is not an OS issue.

**Comment by variar** [comment]
This might be caused by code watching for file changes in that directory. I'll check if disabling OS file monotoring api in favour of simple polling resolves the issue. If it does help, I'll add yet another option to advanced settings.

**Comment by variar** [comment]
I've added an option to control native file watching in build 19.8.0.448. For some reason file watching library that klogg uses doesn't release directories when files are removed from watch list, so you need to restart klogg after disabling native file watching.

**Comment by jeffjensen** [comment]
Thank you!  448 allows clean build to work as it no longer holds the directory.
