### ISSUE TITLE
Move recent files and open file settings from klogg.conf

### ISSUE THREAD

**Issue by shvez** [variar/klogg#94]
hi, there

Here is one more feature request. we use portable version of klogg on windows. this portable version checked in to svn repo. every time when klogg opens files it updates this config file also that changes should not be checked in to svn repo.  From another point of view if we change some options then we need to check it in to have common config.

Is it possible to move recent files and other temporary stuff out from klogg.conf to some other file which we could add to ignore?

or maybe there is other way around this issue?

best,
Ilya

**Comment by variar** [comment]
Moved changing data to klogg_session.conf in 19.09.0.451

**Comment by shvez** [comment]
seems like it does what We need.

Thank you

**Comment by jeffjensen** [comment]
I easily see Open Files only maintained in klogg_session.conf, wondering which other sections to remove from klogg.conf too, as only maintained in klogg_session.conf?

**Comment by variar** [comment]
These keys and sections are changed in runtime by klogg and are moved to klogg_session.conf

> [General]
> geometry=
> versionchecker.nextDeadline=
> [OpenFiles]
> [SavedSearches]

All other settings are changed manually and stay in klogg.conf

**Comment by variar** [comment]
I've added cleanup code that will take care of keys in both klogg.conf and klogg_session.conf on first start.

**Comment by jeffjensen** [comment]
Very nice, thank you.
