### ISSUE TITLE
File truncated on disk, previous search results are not valid anymore

### ISSUE THREAD

**Issue by variar** [variar/klogg#98]
I see a major issue with 19.9.0.454 with default settings :
When I search for a string, it seems to work, but after every 2 seconds (polling time), the search pane clears up with the error "File truncated on disk, previous search results are not valid anymore."
Note that the file I'm viewing is a log file that gets new line appended continuously.

The issue is so problematic, I might have to revert to a previous version of klogg until this is fixed.

```` 
[General]
version=1
mainFont.family=Consolas
mainFont.size=8
regexpType.main=0
regexpType.quickfind=2
quickfind.incremental=true
nativeFileWatch.enabled=true
polling.enabled=true
polling.intervalMs=2000
session.loadLast=true
logging.enableLogging=false
logging.verbosity=4
versionchecker.enabled=true
perf.useParallelSearch=true
perf.useSearchResultsCache=true
perf.searchResultsCacheLines=1000000
perf.indexReadBufferSizeMb=16
perf.searchReadBufferSizeLines=5000
perf.searchThreadPoolSize=0
perf.keepFileClosed=false
perf.useLineEndingCache=true
view.overviewVisible=true
view.lineNumbersVisibleInMain=false
view.lineNumbersVisibleInFiltered=true
view.minimizeToTray=false
defaultView.searchAutoRefresh=false
defaultView.searchIgnoreCase=false
defaultView.splitterSizes=400, 100
````

_Originally posted by @wiz0u in https://github.com/variar/klogg/issues/83#issuecomment-530273282_

**Comment by variar** [comment]
@wiz0u how fast does new lines get to log file? There might be an issue when new lines get to log while index is updated, seeing klogg logs could help. I'll investigate as soon as possible.

**Comment by wiz0u** [comment]
New lines are not appended very fast.. one per second in general.. sometimes 4 per second

In the following log, R:\ is a network share.
[klogg_2019-09-11_14-13-28_5808.log](https://github.com/variar/klogg/files/3600703/klogg_2019-09-11_14-13-28_5808.log)

**Comment by variar** [comment]
Builds 19.9.0.456 should have the fix for this annoying issue

**Comment by wiz0u** [comment]
Seems fine now. You can close
Thx
