### ISSUE TITLE
Add word wrap

### ISSUE THREAD

**Issue by valentijnpeters** [variar/klogg#99]
1 log line is approximately 1000 characters. So it's not possible to read everything. we have to scroll to the right too much.

Is there a way to configurate when there is a line break and the rest of the logline is put on the next so it's possible to read further in case desired. 

more flexible and options/possibilities would be very comfortable.

**Comment by valentijnpeters** [comment]
![image](https://user-images.githubusercontent.com/49692812/64687070-19817280-d48a-11e9-951a-a4831962d571.png)

**Comment by valentijnpeters** [comment]
can't read:
![image](https://user-images.githubusercontent.com/49692812/64687148-37e76e00-d48a-11e9-8342-099e8e1b239b.png)

**Comment by valentijnpeters** [comment]
![image](https://user-images.githubusercontent.com/49692812/64689365-8434ad00-d48e-11e9-8633-f2cc20db5cca.png)

**Comment by valentijnpeters** [comment]
![image](https://user-images.githubusercontent.com/49692812/64689444-a9292000-d48e-11e9-8ce2-0d447ee62cf9.png)

**Comment by valentijnpeters** [comment]
![image](https://user-images.githubusercontent.com/49692812/64689485-ba722c80-d48e-11e9-9285-60278fcbcb4e.png)

**Comment by sken130** [comment]
Please put the button on the toolbar, so that we can quickly switch between having word wrap and not having word wrap.

**Comment by dennis-siden** [comment]
Is there a large text editor with word wrap as fast and neat and compact as klogg??

**Comment by variar** [comment]
For windows there is EmEditor, but it is not free. 

I am making some progress on word wrap, but no clear timeline yet

**Comment by Issomane** [comment]
> For windows there is EmEditor, but it is not free.
> 
> I am making some progress on word wrap, but no clear timeline yet

Thanks @variar!  This would be a huge lifesaver feature. 
Keep up the good work!

**Comment by variar** [comment]
In CI builds 23.06+ I've enabled experimental text wrap feature. It is in the `view` menu, and can be toggled with `W` key. Currently the wrapping algorithm is very basic, it doesn't check for word boundaries and just wraps lines at the edge of visible area. It is a building block for a more user friendly "word wrap" mode that will be implemented later.

There are a few drawing bugs, but selection, highlighters, marks, jumping from filtered view to main view should work.

**Comment by PetbkA** [comment]
**23.06.0.1400 Qt5 x64** - works pretty fine and fast. The only problem I would notice is that selection rectangle height [doesn't adjust](https://github.com/variar/klogg/assets/22843816/4ca3bc80-38fc-411d-a88d-03fb2b83feb6) adjust to line's height

**Comment by variar** [comment]
For now text wrap is disabled on restarts to avoid scenario when enabling it leads to repeated crashes on startup

It definetely should be either a global setting or a per-file setting. Not sure which is better.

**Comment by PetbkA** [comment]
> It definetely should be either a global setting or a per-file setting

Global is better. Besides, I don't remember any text editor which kept it per-file

**Comment by variar** [comment]
> **23.06.0.1400 Qt5 x64** - found another bug: Search Results [are being cut](https://github.com/variar/klogg/assets/22843816/44b98616-fcf5-4fe2-852f-bf8fef91b347) beyond results frame when wrap is disabled.


Might be fixed in 23.06.0.1405

**Comment by PetbkA** [comment]
**23.06.0.1405 Qt5 x64 Windows** - if word wrap is disabled, scrolling beyond the visible area of the _hightlighted_ line crashes klogg (Sentry report `356b2557-876d-468c-80eb-29f04d3dea76`). Workarund - disable highlighter for this string or enable word wrap.

BTW, can you add flag for enabling/disabling word wrap for all files to klogg.ini/klogg.conf?
